//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace CAS.SmartFactory.CW.Interoperability.DocumentsFactory.StatementContent {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/Statement" +
        "Content.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/Statement" +
        "Content.xsd", IsNullable=false)]
    public partial class StatementContent {
        
        private System.DateTime documentDateField;
        
        private OneSADDeclaration[] sADDocumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DocumentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("SADDeclarations", IsNullable=false)]
        public OneSADDeclaration[] SADDocuments {
            get {
                return this.sADDocumentsField;
            }
            set {
                this.sADDocumentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/Statement" +
        "Content.xsd")]
    public partial class OneSADDeclaration {
        
        private double noField;
        
        private string introducingSADNoField;
        
        private System.DateTime introducingSADDateField;
        
        private string sADDocumentNoField;
        
        private System.DateTime sADDocumentDateField;
        
        /// <remarks/>
        public double No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string IntroducingSADNo {
            get {
                return this.introducingSADNoField;
            }
            set {
                this.introducingSADNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime IntroducingSADDate {
            get {
                return this.introducingSADDateField;
            }
            set {
                this.introducingSADDateField = value;
            }
        }
        
        /// <remarks/>
        public string SADDocumentNo {
            get {
                return this.sADDocumentNoField;
            }
            set {
                this.sADDocumentNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SADDocumentDate {
            get {
                return this.sADDocumentDateField;
            }
            set {
                this.sADDocumentDateField = value;
            }
        }
    }
}
