//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.18052
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace CAS.SmartFactory.CW.Interoperability.ERP {
    using System.Xml.Serialization;
    
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/smartfactory/cw/disposalrequest.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cas.eu/schemas/smartfactory/cw/disposalrequest.xsd", IsNullable=true)]
    public partial class DisposalRequest {
        
        private DisposalRequestDisposalRequestContent[] disposalRequestContentField;
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("DisposalRequestContent")]
        public DisposalRequestDisposalRequestContent[] DisposalRequestContent {
            get {
                return this.disposalRequestContentField;
            }
            set {
                this.disposalRequestContentField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/smartfactory/cw/disposalrequest.xsd")]
    public partial class DisposalRequestDisposalRequestContent {
        
        private string materialNoField;
        
        private string descriptionField;
        
        private string batchNoField;
        
        private decimal qtyToClearField;
        
        private decimal totalStockField;
        
        private decimal totalStockToClearField;
        
        private decimal totalStockOnHandField;
        
        private string uoMField;
        
        private decimal addedKgField;
        
        /// <uwagi/>
        public string MaterialNo {
            get {
                return this.materialNoField;
            }
            set {
                this.materialNoField = value;
            }
        }
        
        /// <uwagi/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <uwagi/>
        public string BatchNo {
            get {
                return this.batchNoField;
            }
            set {
                this.batchNoField = value;
            }
        }
        
        /// <uwagi/>
        public decimal QtyToClear {
            get {
                return this.qtyToClearField;
            }
            set {
                this.qtyToClearField = value;
            }
        }
        
        /// <uwagi/>
        public decimal TotalStock {
            get {
                return this.totalStockField;
            }
            set {
                this.totalStockField = value;
            }
        }
        
        /// <uwagi/>
        public decimal TotalStockToClear {
            get {
                return this.totalStockToClearField;
            }
            set {
                this.totalStockToClearField = value;
            }
        }
        
        /// <uwagi/>
        public decimal TotalStockOnHand {
            get {
                return this.totalStockOnHandField;
            }
            set {
                this.totalStockOnHandField = value;
            }
        }
        
        /// <uwagi/>
        public string UoM {
            get {
                return this.uoMField;
            }
            set {
                this.uoMField = value;
            }
        }
        
        /// <uwagi/>
        public decimal AddedKg {
            get {
                return this.addedKgField;
            }
            set {
                this.addedKgField = value;
            }
        }
    }
}
