//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.5456
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CAS.SmartFactory.xml.DocumentsFactory.CigaretteExportForm {
    using System.Xml.Serialization;
    
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/CigaretteExportForm.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/CigaretteExportForm.xsd", IsNullable=true)]
    public partial class CigaretteExportFormCollection {
        
        private CigaretteExportForm[] cigaretteExportFormsField;
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CigaretteExportForm[] CigaretteExportForms {
            get {
                return this.cigaretteExportFormsField;
            }
            set {
                this.cigaretteExportFormsField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/CigaretteExportForm.xsd")]
    public partial class CigaretteExportForm {
        
        private string productFormatField;
        
        private double dustKgField;
        
        private double sHMentholKgField;
        
        private double wasteKgField;
        
        private double portionField;
        
        private ProductType productField;
        
        private Ingredient[] ingredientsField;
        
        /// <uwagi/>
        public string ProductFormat {
            get {
                return this.productFormatField;
            }
            set {
                this.productFormatField = value;
            }
        }
        
        /// <uwagi/>
        public double DustKg {
            get {
                return this.dustKgField;
            }
            set {
                this.dustKgField = value;
            }
        }
        
        /// <uwagi/>
        public double SHMentholKg {
            get {
                return this.sHMentholKgField;
            }
            set {
                this.sHMentholKgField = value;
            }
        }
        
        /// <uwagi/>
        public double WasteKg {
            get {
                return this.wasteKgField;
            }
            set {
                this.wasteKgField = value;
            }
        }
        
        /// <uwagi/>
        public double Portion {
            get {
                return this.portionField;
            }
            set {
                this.portionField = value;
            }
        }
        
        /// <uwagi/>
        public ProductType Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(IPRIngredient), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(RegularIngredient), IsNullable=false)]
        public Ingredient[] Ingredients {
            get {
                return this.ingredientsField;
            }
            set {
                this.ingredientsField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/CigaretteExportForm.xsd")]
    public enum ProductType {
        
        /// <uwagi/>
        Cutfiller,
        
        /// <uwagi/>
        Cigarette,
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/CigaretteExportForm.xsd")]
    public partial class IPRIngredient : Ingredient {
        
        private string documentNoumberField;
        
        private System.DateTime dateField;
        
        private double tobaccoUnitPriceField;
        
        private double tobaccoValueField;
        
        private ClearingType itemClearingTypeField;
        
        private string currencyField;
        
        private double dutyField;
        
        private double vATField;
        
        /// <uwagi/>
        public string DocumentNoumber {
            get {
                return this.documentNoumberField;
            }
            set {
                this.documentNoumberField = value;
            }
        }
        
        /// <uwagi/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <uwagi/>
        public double TobaccoUnitPrice {
            get {
                return this.tobaccoUnitPriceField;
            }
            set {
                this.tobaccoUnitPriceField = value;
            }
        }
        
        /// <uwagi/>
        public double TobaccoValue {
            get {
                return this.tobaccoValueField;
            }
            set {
                this.tobaccoValueField = value;
            }
        }
        
        /// <uwagi/>
        public ClearingType ItemClearingType {
            get {
                return this.itemClearingTypeField;
            }
            set {
                this.itemClearingTypeField = value;
            }
        }
        
        /// <uwagi/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <uwagi/>
        public double Duty {
            get {
                return this.dutyField;
            }
            set {
                this.dutyField = value;
            }
        }
        
        /// <uwagi/>
        public double VAT {
            get {
                return this.vATField;
            }
            set {
                this.vATField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/CigaretteExportForm.xsd")]
    public enum ClearingType {
        
        /// <uwagi/>
        PartialWindingUp,
        
        /// <uwagi/>
        TotalWindingUp,
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegularIngredient))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IPRIngredient))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/CigaretteExportForm.xsd")]
    public abstract partial class Ingredient {
        
        private string tobaccoSKUField;
        
        private string tobaccoBatchField;
        
        private double tobaccoQuantityField;
        
        /// <uwagi/>
        public string TobaccoSKU {
            get {
                return this.tobaccoSKUField;
            }
            set {
                this.tobaccoSKUField = value;
            }
        }
        
        /// <uwagi/>
        public string TobaccoBatch {
            get {
                return this.tobaccoBatchField;
            }
            set {
                this.tobaccoBatchField = value;
            }
        }
        
        /// <uwagi/>
        public double TobaccoQuantity {
            get {
                return this.tobaccoQuantityField;
            }
            set {
                this.tobaccoQuantityField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/CigaretteExportForm.xsd")]
    public partial class RegularIngredient : Ingredient {
    }
}
