//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.18052
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace CAS.SmartFactory.CW.Interoperability.DocumentsFactory.Statement {
    using System.Xml.Serialization;
    
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/Statement" +
        "Content.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/Statement" +
        "Content.xsd", IsNullable=false)]
    public partial class StatementContent {
        
        private System.DateTime documentDateField;
        
        private string customsProcedureField;
        
        private Statement[] statementOfDutiesField;
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DocumentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
            }
        }
        
        /// <uwagi/>
        public string CustomsProcedure {
            get {
                return this.customsProcedureField;
            }
            set {
                this.customsProcedureField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Statement[] StatementOfDuties {
            get {
                return this.statementOfDutiesField;
            }
            set {
                this.statementOfDutiesField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/Statement" +
        "Content.xsd")]
    public partial class Statement {
        
        private int noField;
        
        private string referenceNumberField;
        
        private string sADDocumentNoField;
        
        private double dutyPerSettledAmountField;
        
        private double vATPerSettledAmountField;
        
        private double dutyAndVATField;
        
        /// <uwagi/>
        public int No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <uwagi/>
        public string ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <uwagi/>
        public string SADDocumentNo {
            get {
                return this.sADDocumentNoField;
            }
            set {
                this.sADDocumentNoField = value;
            }
        }
        
        /// <uwagi/>
        public double DutyPerSettledAmount {
            get {
                return this.dutyPerSettledAmountField;
            }
            set {
                this.dutyPerSettledAmountField = value;
            }
        }
        
        /// <uwagi/>
        public double VATPerSettledAmount {
            get {
                return this.vATPerSettledAmountField;
            }
            set {
                this.vATPerSettledAmountField = value;
            }
        }
        
        /// <uwagi/>
        public double DutyAndVAT {
            get {
                return this.dutyAndVATField;
            }
            set {
                this.dutyAndVATField = value;
            }
        }
    }
}
