//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace CAS.SmartFactory.CW.Dashboards.CheckListWebPart.Schema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/SmartFactory/CW/Dashboards/CheckListWebPart/Schema/CheckLis" +
        "t.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cas.eu/schemas/SmartFactory/CW/Dashboards/CheckListWebPart/Schema/CheckLis" +
        "t.xsd", IsNullable=false)]
    public partial class CheckList {
        
        private CheckListItemContentArray[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ContentArray", IsNullable=false)]
        public CheckListItemContentArray[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/SmartFactory/CW/Dashboards/CheckListWebPart/Schema/CheckLis" +
        "t.xsd")]
    public partial class CheckListItemContentArray {
        
        private string oGLNumberField;
        
        private System.DateTime oGLDateField;
        
        private string packageToClearField;
        
        /// <remarks/>
        public string OGLNumber {
            get {
                return this.oGLNumberField;
            }
            set {
                this.oGLNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime OGLDate {
            get {
                return this.oGLDateField;
            }
            set {
                this.oGLDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PackageToClear {
            get {
                return this.packageToClearField;
            }
            set {
                this.packageToClearField = value;
            }
        }
    }
}
