//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.5448
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CAS.SmartFactory.xml.erp {
    using System.Xml.Serialization;
    
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/jti/ipr/SKUCutfillerSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cas.eu/schemas/jti/ipr/SKUCutfillerSchema.xsd", IsNullable=true)]
    public partial class Cutfiller {
        
        private CutfillerMaterial[] materialField;
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("Material", IsNullable=true)]
        public CutfillerMaterial[] Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/jti/ipr/SKUCutfillerSchema.xsd")]
    public partial class CutfillerMaterial {
        
        private string plantField;
        
        private string materialField;
        
        private string materialDescriptionField;
        
        private string revision_LevelField;
        
        private string valid_from_Date_DDMMYYYYField;
        
        private string baseUnitOfMeasureField;
        
        private string base_Unit_Of_Measure_DescriptionField;
        
        private string old_Material_NumberField;
        
        private string extl__matl_groupField;
        
        private string divisionField;
        
        private string division_DescriptionField;
        
        private string product_allocationField;
        
        private string product_allocation_DescriptionField;
        
        private string product_HierarchyField;
        
        private string x_plant_matl_statusField;
        
        private string x_plant_matl_status_DescriptionField;
        
        private string genItemCatGroupField;
        
        private string genItemCatGroup_DescriptionField;
        
        private string authorization_groupField;
        
        private string authorization_group_DescriptionField;
        
        private string gross_WeightField;
        
        private string net_WeightField;
        
        private string weight_unitField;
        
        private string weight_unit_DescriptionField;
        
        private string volumeField;
        
        private string volume_UnitField;
        
        private string volume_Unit_DescriptionField;
        
        private string batch_Management_flagField;
        
        private string min__rem__shelf_lifeField;
        
        private string total_Shelf_lifeField;
        
        private string period_ind__for_SLEDField;
        
        private string rounding_rule_SLEDField;
        
        private string storage_percentageField;
        
        private string inspection_IntervalField;
        
        private string plant_sp_material_StsField;
        
        private string plant_sp_material_Sts__DescriptionField;
        
        private string languages_maintainedField;
        
        private string supplier_NoField;
        
        private string supplier_NameField;
        
        private string supplier_Name_DescriptionField;
        
        private string standard_Price_Company_Code_CurrencyField;
        
        private string currency_key_1Field;
        
        private string price_unit_1Field;
        
        private string standard_Price_Legal_ValuationField;
        
        private string currency_key_2Field;
        
        private string price_unit_2Field;
        
        private string standard_Price_Group_ValuationField;
        
        private string currency_key_3Field;
        
        private string price_unit_3Field;
        
        private string blend_GenerationField;
        
        private string blend_Generation_DescriptionField;
        
        private string blendPurposeField;
        
        private string blend_Purpose_DescriptionField;
        
        private string blend_RevisionField;
        
        private string blend_Revision_DescriptionField;
        
        private string project_CordField;
        
        private string project_Cord_DescriptionField;
        
        private string casing_Appl__Ratio_1__Bur_CasField;
        
        private string casing_Appl__Ratio_2__Bur_TopField;
        
        private string casing_Appl__Ratio_3__PartialField;
        
        private string casing_Appl__Ratio_4__TotalField;
        
        private string casing_Appl__Ratio_5__CuttingField;
        
        private string fumigationField;
        
        private string fumigation_DescriptionField;
        
        private string special_RemarksField;
        
        private string tDR_Application_RatioField;
        
        private string commodity_CodeField;
        
        private string legacy_NumberField;
        
        private string legacy_DescriptionField;
        
        private string flavor_TypeField;
        
        private string flavor_Type_DescriptionField;
        
        private string shelf_Life__DaysField;
        
        private string net_Weight2Field;
        
        private string minimum_bulker_ageing_timeField;
        
        private string blend_CodeField;
        
        private string blend_Code_DescriptionField;
        
        private string variantField;
        
        private string variant_DescriptionField;
        
        private string tobacco_NicotineField;
        
        private string cES_Dry_Weight_RatioField;
        
        private string eTB_Dry_Weight_RatioField;
        
        private string sR_Dry_Weight_RatioField;
        
        private string addback_GroupField;
        
        private string addback_Group_DescriptionField;
        
        private string moistureField;
        
        private string cigarette_Pack_MoistureField;
        
        private string cig_Pack_Moist_Warning_LimitsField;
        
        private string cig_Pack_Moist_Reject_LimitsField;
        
        private string l_B_Tracking_CodeField;
        
        private string c_F_Tracking_CodeField;
        
        private string blend_Specifics_1Field;
        
        private string blend_Specifics_2Field;
        
        private string blend_Specifics_3Field;
        
        private string filling_Capacity__ml_2_3_psiField;
        
        private string sieve_Results__CFTField;
        
        private string total_MentholField;
        
        private string process_Parameter_SetField;
        
        private string process_Parameter_Set_DescriptionField;
        
        private string dryer_ProcessField;
        
        private string dryer_Process_DescriptionField;
        
        private string cutting_MoistureField;
        
        private string cutting_Moist__Warning_LimitsField;
        
        private string cutting_Moist__Reject_LimitsField;
        
        private string cut_WidthField;
        
        private string exit_Tob_MoistureField;
        
        private string exit_Tob_Moist_Warning_LimitsField;
        
        private string exit_Tob_Moist_Reject_LimitsField;
        
        private string tDR_Exit_MoistureField;
        
        private string tDR_Exit_Moisture_Warning_LimsField;
        
        private string tDR_Exit_Moisture_Reject_LimsField;
        
        private string dryer_Input_MoistureField;
        
        private string dryer_Input_Moist__Warn_LimitsField;
        
        private string dryer_Input_Moist__Rej__LimitsField;
        
        private string dryer_Exit_MoistureField;
        
        private string dryer_Exit_Moist__Warn__LimitsField;
        
        private string dryer_Exit_Moisture_Rej_LimitsField;
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Plant {
            get {
                return this.plantField;
            }
            set {
                this.plantField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MaterialDescription {
            get {
                return this.materialDescriptionField;
            }
            set {
                this.materialDescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Revision_Level {
            get {
                return this.revision_LevelField;
            }
            set {
                this.revision_LevelField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Valid_from_Date_DDMMYYYY {
            get {
                return this.valid_from_Date_DDMMYYYYField;
            }
            set {
                this.valid_from_Date_DDMMYYYYField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BaseUnitOfMeasure {
            get {
                return this.baseUnitOfMeasureField;
            }
            set {
                this.baseUnitOfMeasureField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Base_Unit_Of_Measure_Description {
            get {
                return this.base_Unit_Of_Measure_DescriptionField;
            }
            set {
                this.base_Unit_Of_Measure_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Old_Material_Number {
            get {
                return this.old_Material_NumberField;
            }
            set {
                this.old_Material_NumberField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Extl__matl_group {
            get {
                return this.extl__matl_groupField;
            }
            set {
                this.extl__matl_groupField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Division {
            get {
                return this.divisionField;
            }
            set {
                this.divisionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Division_Description {
            get {
                return this.division_DescriptionField;
            }
            set {
                this.division_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_allocation {
            get {
                return this.product_allocationField;
            }
            set {
                this.product_allocationField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_allocation_Description {
            get {
                return this.product_allocation_DescriptionField;
            }
            set {
                this.product_allocation_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Product_Hierarchy {
            get {
                return this.product_HierarchyField;
            }
            set {
                this.product_HierarchyField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string X_plant_matl_status {
            get {
                return this.x_plant_matl_statusField;
            }
            set {
                this.x_plant_matl_statusField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string X_plant_matl_status_Description {
            get {
                return this.x_plant_matl_status_DescriptionField;
            }
            set {
                this.x_plant_matl_status_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GenItemCatGroup {
            get {
                return this.genItemCatGroupField;
            }
            set {
                this.genItemCatGroupField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GenItemCatGroup_Description {
            get {
                return this.genItemCatGroup_DescriptionField;
            }
            set {
                this.genItemCatGroup_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Authorization_group {
            get {
                return this.authorization_groupField;
            }
            set {
                this.authorization_groupField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Authorization_group_Description {
            get {
                return this.authorization_group_DescriptionField;
            }
            set {
                this.authorization_group_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gross_Weight {
            get {
                return this.gross_WeightField;
            }
            set {
                this.gross_WeightField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Net_Weight {
            get {
                return this.net_WeightField;
            }
            set {
                this.net_WeightField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Weight_unit {
            get {
                return this.weight_unitField;
            }
            set {
                this.weight_unitField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Weight_unit_Description {
            get {
                return this.weight_unit_DescriptionField;
            }
            set {
                this.weight_unit_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Volume_Unit {
            get {
                return this.volume_UnitField;
            }
            set {
                this.volume_UnitField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Volume_Unit_Description {
            get {
                return this.volume_Unit_DescriptionField;
            }
            set {
                this.volume_Unit_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Batch_Management_flag {
            get {
                return this.batch_Management_flagField;
            }
            set {
                this.batch_Management_flagField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Min__rem__shelf_life {
            get {
                return this.min__rem__shelf_lifeField;
            }
            set {
                this.min__rem__shelf_lifeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Total_Shelf_life {
            get {
                return this.total_Shelf_lifeField;
            }
            set {
                this.total_Shelf_lifeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Period_ind__for_SLED {
            get {
                return this.period_ind__for_SLEDField;
            }
            set {
                this.period_ind__for_SLEDField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Rounding_rule_SLED {
            get {
                return this.rounding_rule_SLEDField;
            }
            set {
                this.rounding_rule_SLEDField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Storage_percentage {
            get {
                return this.storage_percentageField;
            }
            set {
                this.storage_percentageField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Inspection_Interval {
            get {
                return this.inspection_IntervalField;
            }
            set {
                this.inspection_IntervalField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Plant_sp_material_Sts {
            get {
                return this.plant_sp_material_StsField;
            }
            set {
                this.plant_sp_material_StsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Plant_sp_material_Sts__Description {
            get {
                return this.plant_sp_material_Sts__DescriptionField;
            }
            set {
                this.plant_sp_material_Sts__DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Languages_maintained {
            get {
                return this.languages_maintainedField;
            }
            set {
                this.languages_maintainedField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Supplier_No {
            get {
                return this.supplier_NoField;
            }
            set {
                this.supplier_NoField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Supplier_Name {
            get {
                return this.supplier_NameField;
            }
            set {
                this.supplier_NameField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Supplier_Name_Description {
            get {
                return this.supplier_Name_DescriptionField;
            }
            set {
                this.supplier_Name_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Standard_Price_Company_Code_Currency {
            get {
                return this.standard_Price_Company_Code_CurrencyField;
            }
            set {
                this.standard_Price_Company_Code_CurrencyField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Currency_key_1 {
            get {
                return this.currency_key_1Field;
            }
            set {
                this.currency_key_1Field = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Price_unit_1 {
            get {
                return this.price_unit_1Field;
            }
            set {
                this.price_unit_1Field = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Standard_Price_Legal_Valuation {
            get {
                return this.standard_Price_Legal_ValuationField;
            }
            set {
                this.standard_Price_Legal_ValuationField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Currency_key_2 {
            get {
                return this.currency_key_2Field;
            }
            set {
                this.currency_key_2Field = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Price_unit_2 {
            get {
                return this.price_unit_2Field;
            }
            set {
                this.price_unit_2Field = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Standard_Price_Group_Valuation {
            get {
                return this.standard_Price_Group_ValuationField;
            }
            set {
                this.standard_Price_Group_ValuationField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Currency_key_3 {
            get {
                return this.currency_key_3Field;
            }
            set {
                this.currency_key_3Field = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Price_unit_3 {
            get {
                return this.price_unit_3Field;
            }
            set {
                this.price_unit_3Field = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Blend_Generation {
            get {
                return this.blend_GenerationField;
            }
            set {
                this.blend_GenerationField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Blend_Generation_Description {
            get {
                return this.blend_Generation_DescriptionField;
            }
            set {
                this.blend_Generation_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BlendPurpose {
            get {
                return this.blendPurposeField;
            }
            set {
                this.blendPurposeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Blend_Purpose_Description {
            get {
                return this.blend_Purpose_DescriptionField;
            }
            set {
                this.blend_Purpose_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Blend_Revision {
            get {
                return this.blend_RevisionField;
            }
            set {
                this.blend_RevisionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Blend_Revision_Description {
            get {
                return this.blend_Revision_DescriptionField;
            }
            set {
                this.blend_Revision_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Project_Cord {
            get {
                return this.project_CordField;
            }
            set {
                this.project_CordField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Project_Cord_Description {
            get {
                return this.project_Cord_DescriptionField;
            }
            set {
                this.project_Cord_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Casing_Appl__Ratio_1__Bur_Cas {
            get {
                return this.casing_Appl__Ratio_1__Bur_CasField;
            }
            set {
                this.casing_Appl__Ratio_1__Bur_CasField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Casing_Appl__Ratio_2__Bur_Top {
            get {
                return this.casing_Appl__Ratio_2__Bur_TopField;
            }
            set {
                this.casing_Appl__Ratio_2__Bur_TopField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Casing_Appl__Ratio_3__Partial {
            get {
                return this.casing_Appl__Ratio_3__PartialField;
            }
            set {
                this.casing_Appl__Ratio_3__PartialField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Casing_Appl__Ratio_4__Total {
            get {
                return this.casing_Appl__Ratio_4__TotalField;
            }
            set {
                this.casing_Appl__Ratio_4__TotalField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Casing_Appl__Ratio_5__Cutting {
            get {
                return this.casing_Appl__Ratio_5__CuttingField;
            }
            set {
                this.casing_Appl__Ratio_5__CuttingField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Fumigation {
            get {
                return this.fumigationField;
            }
            set {
                this.fumigationField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Fumigation_Description {
            get {
                return this.fumigation_DescriptionField;
            }
            set {
                this.fumigation_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Special_Remarks {
            get {
                return this.special_RemarksField;
            }
            set {
                this.special_RemarksField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TDR_Application_Ratio {
            get {
                return this.tDR_Application_RatioField;
            }
            set {
                this.tDR_Application_RatioField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Commodity_Code {
            get {
                return this.commodity_CodeField;
            }
            set {
                this.commodity_CodeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Legacy_Number {
            get {
                return this.legacy_NumberField;
            }
            set {
                this.legacy_NumberField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Legacy_Description {
            get {
                return this.legacy_DescriptionField;
            }
            set {
                this.legacy_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Flavor_Type {
            get {
                return this.flavor_TypeField;
            }
            set {
                this.flavor_TypeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Flavor_Type_Description {
            get {
                return this.flavor_Type_DescriptionField;
            }
            set {
                this.flavor_Type_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Shelf_Life__Days {
            get {
                return this.shelf_Life__DaysField;
            }
            set {
                this.shelf_Life__DaysField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Net_Weight2 {
            get {
                return this.net_Weight2Field;
            }
            set {
                this.net_Weight2Field = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Minimum_bulker_ageing_time {
            get {
                return this.minimum_bulker_ageing_timeField;
            }
            set {
                this.minimum_bulker_ageing_timeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Blend_Code {
            get {
                return this.blend_CodeField;
            }
            set {
                this.blend_CodeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Blend_Code_Description {
            get {
                return this.blend_Code_DescriptionField;
            }
            set {
                this.blend_Code_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Variant {
            get {
                return this.variantField;
            }
            set {
                this.variantField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Variant_Description {
            get {
                return this.variant_DescriptionField;
            }
            set {
                this.variant_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tobacco_Nicotine {
            get {
                return this.tobacco_NicotineField;
            }
            set {
                this.tobacco_NicotineField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CES_Dry_Weight_Ratio {
            get {
                return this.cES_Dry_Weight_RatioField;
            }
            set {
                this.cES_Dry_Weight_RatioField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ETB_Dry_Weight_Ratio {
            get {
                return this.eTB_Dry_Weight_RatioField;
            }
            set {
                this.eTB_Dry_Weight_RatioField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SR_Dry_Weight_Ratio {
            get {
                return this.sR_Dry_Weight_RatioField;
            }
            set {
                this.sR_Dry_Weight_RatioField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Addback_Group {
            get {
                return this.addback_GroupField;
            }
            set {
                this.addback_GroupField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Addback_Group_Description {
            get {
                return this.addback_Group_DescriptionField;
            }
            set {
                this.addback_Group_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Moisture {
            get {
                return this.moistureField;
            }
            set {
                this.moistureField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cigarette_Pack_Moisture {
            get {
                return this.cigarette_Pack_MoistureField;
            }
            set {
                this.cigarette_Pack_MoistureField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cig_Pack_Moist_Warning_Limits {
            get {
                return this.cig_Pack_Moist_Warning_LimitsField;
            }
            set {
                this.cig_Pack_Moist_Warning_LimitsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cig_Pack_Moist_Reject_Limits {
            get {
                return this.cig_Pack_Moist_Reject_LimitsField;
            }
            set {
                this.cig_Pack_Moist_Reject_LimitsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string L_B_Tracking_Code {
            get {
                return this.l_B_Tracking_CodeField;
            }
            set {
                this.l_B_Tracking_CodeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string C_F_Tracking_Code {
            get {
                return this.c_F_Tracking_CodeField;
            }
            set {
                this.c_F_Tracking_CodeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Blend_Specifics_1 {
            get {
                return this.blend_Specifics_1Field;
            }
            set {
                this.blend_Specifics_1Field = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Blend_Specifics_2 {
            get {
                return this.blend_Specifics_2Field;
            }
            set {
                this.blend_Specifics_2Field = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Blend_Specifics_3 {
            get {
                return this.blend_Specifics_3Field;
            }
            set {
                this.blend_Specifics_3Field = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Filling_Capacity__ml_2_3_psi {
            get {
                return this.filling_Capacity__ml_2_3_psiField;
            }
            set {
                this.filling_Capacity__ml_2_3_psiField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sieve_Results__CFT {
            get {
                return this.sieve_Results__CFTField;
            }
            set {
                this.sieve_Results__CFTField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Total_Menthol {
            get {
                return this.total_MentholField;
            }
            set {
                this.total_MentholField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Process_Parameter_Set {
            get {
                return this.process_Parameter_SetField;
            }
            set {
                this.process_Parameter_SetField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Process_Parameter_Set_Description {
            get {
                return this.process_Parameter_Set_DescriptionField;
            }
            set {
                this.process_Parameter_Set_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Dryer_Process {
            get {
                return this.dryer_ProcessField;
            }
            set {
                this.dryer_ProcessField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Dryer_Process_Description {
            get {
                return this.dryer_Process_DescriptionField;
            }
            set {
                this.dryer_Process_DescriptionField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cutting_Moisture {
            get {
                return this.cutting_MoistureField;
            }
            set {
                this.cutting_MoistureField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cutting_Moist__Warning_Limits {
            get {
                return this.cutting_Moist__Warning_LimitsField;
            }
            set {
                this.cutting_Moist__Warning_LimitsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cutting_Moist__Reject_Limits {
            get {
                return this.cutting_Moist__Reject_LimitsField;
            }
            set {
                this.cutting_Moist__Reject_LimitsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cut_Width {
            get {
                return this.cut_WidthField;
            }
            set {
                this.cut_WidthField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Exit_Tob_Moisture {
            get {
                return this.exit_Tob_MoistureField;
            }
            set {
                this.exit_Tob_MoistureField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Exit_Tob_Moist_Warning_Limits {
            get {
                return this.exit_Tob_Moist_Warning_LimitsField;
            }
            set {
                this.exit_Tob_Moist_Warning_LimitsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Exit_Tob_Moist_Reject_Limits {
            get {
                return this.exit_Tob_Moist_Reject_LimitsField;
            }
            set {
                this.exit_Tob_Moist_Reject_LimitsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TDR_Exit_Moisture {
            get {
                return this.tDR_Exit_MoistureField;
            }
            set {
                this.tDR_Exit_MoistureField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TDR_Exit_Moisture_Warning_Lims {
            get {
                return this.tDR_Exit_Moisture_Warning_LimsField;
            }
            set {
                this.tDR_Exit_Moisture_Warning_LimsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TDR_Exit_Moisture_Reject_Lims {
            get {
                return this.tDR_Exit_Moisture_Reject_LimsField;
            }
            set {
                this.tDR_Exit_Moisture_Reject_LimsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Dryer_Input_Moisture {
            get {
                return this.dryer_Input_MoistureField;
            }
            set {
                this.dryer_Input_MoistureField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Dryer_Input_Moist__Warn_Limits {
            get {
                return this.dryer_Input_Moist__Warn_LimitsField;
            }
            set {
                this.dryer_Input_Moist__Warn_LimitsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Dryer_Input_Moist__Rej__Limits {
            get {
                return this.dryer_Input_Moist__Rej__LimitsField;
            }
            set {
                this.dryer_Input_Moist__Rej__LimitsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Dryer_Exit_Moisture {
            get {
                return this.dryer_Exit_MoistureField;
            }
            set {
                this.dryer_Exit_MoistureField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Dryer_Exit_Moist__Warn__Limits {
            get {
                return this.dryer_Exit_Moist__Warn__LimitsField;
            }
            set {
                this.dryer_Exit_Moist__Warn__LimitsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Dryer_Exit_Moisture_Rej_Limits {
            get {
                return this.dryer_Exit_Moisture_Rej_LimitsField;
            }
            set {
                this.dryer_Exit_Moisture_Rej_LimitsField = value;
            }
        }
    }
}
