//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.5448
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAS.SmartFactory.Shepherd.Dashboards.Entities {
	using System;
	
	
	public partial class EntitiesDataContext : Microsoft.SharePoint.Linq.DataContext {
		
		#region Extensibility Method Definitions
		partial void OnCreated();
		#endregion
		
		public EntitiesDataContext(string requestUrl) : 
				base(requestUrl) {
			this.OnCreated();
		}
		
		/// <summary>
		/// Alarms and events List Instance
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="Alarms and events")]
		public Microsoft.SharePoint.Linq.EntityList<AlarmsAndEvents> AlarmsAndEvents {
			get {
				return this.GetList<AlarmsAndEvents>("Alarms and events");
			}
		}
		
		/// <summary>
		/// Country List Instance
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="Country")]
		public Microsoft.SharePoint.Linq.EntityList<Element> Country {
			get {
				return this.GetList<Element>("Country");
			}
		}
		
		/// <summary>
		/// Driver List Instance
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="Driver")]
		public Microsoft.SharePoint.Linq.EntityList<Driver> Driver {
			get {
				return this.GetList<Driver>("Driver");
			}
		}
		
		/// <summary>
		/// Drivers Team List Instance
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="Drivers Team")]
		public Microsoft.SharePoint.Linq.EntityList<ShippingDriversTeam> DriversTeam {
			get {
				return this.GetList<ShippingDriversTeam>("Drivers Team");
			}
		}
		
		/// <summary>
		/// JTI Partner List Instance
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="JTI Partner")]
		public Microsoft.SharePoint.Linq.EntityList<Partner> JTIPartner {
			get {
				return this.GetList<Partner>("JTI Partner");
			}
		}
		
		/// <summary>
		/// Load Description List Instance
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="Load Description")]
		public Microsoft.SharePoint.Linq.EntityList<LoadDescription> LoadDescription {
			get {
				return this.GetList<LoadDescription>("Load Description");
			}
		}
		
		/// <summary>
		/// Shiping List Instance
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="Shipping")]
		public Microsoft.SharePoint.Linq.EntityList<ShippingOperationInbound> Shipping {
			get {
				return this.GetList<ShippingOperationInbound>("Shipping");
			}
		}
		
		/// <summary>
		/// Shipping Point List Instance
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="Shipping Point")]
		public Microsoft.SharePoint.Linq.EntityList<ShippingPoint> ShippingPoint {
			get {
				return this.GetList<ShippingPoint>("Shipping Point");
			}
		}
		
		/// <summary>
		/// TimeSLot List Instance
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="TimeSlot")]
		public Microsoft.SharePoint.Linq.EntityList<TimeSlotTimeSlot> TimeSlot {
			get {
				return this.GetList<TimeSlotTimeSlot>("TimeSlot");
			}
		}
		
		/// <summary>
		/// Trailer List Instance
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="Trailer")]
		public Microsoft.SharePoint.Linq.EntityList<Trailer> Trailer {
			get {
				return this.GetList<Trailer>("Trailer");
			}
		}
		
		/// <summary>
		/// Truck List Instance
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="Truck")]
		public Microsoft.SharePoint.Linq.EntityList<Truck> Truck {
			get {
				return this.GetList<Truck>("Truck");
			}
		}
		
		/// <summary>
		/// Warehouse List Instance
		/// </summary>
		[Microsoft.SharePoint.Linq.ListAttribute(Name="Warehouse")]
		public Microsoft.SharePoint.Linq.EntityList<Warehouse> Warehouse {
			get {
				return this.GetList<Warehouse>("Warehouse");
			}
		}
	}
	
	/// <summary>
	/// Utwórz nowy element listy.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Element", Id="0x01")]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(AlarmsAndEvents))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Driver))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ShippingDriversTeam))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Partner))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(LoadDescription))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ShippingOperationInbound))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ShippingPoint))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Wydarzenie))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Trailer))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Truck))]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(Warehouse))]
	public partial class Element : Microsoft.SharePoint.Linq.ITrackEntityState, Microsoft.SharePoint.Linq.ITrackOriginalValues, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
		
		private System.Nullable<int> _identyfikator;
		
		private System.Nullable<int> _wersja;
		
		private string _ścieżka;
		
		private Microsoft.SharePoint.Linq.EntityState _entityState;
		
		private System.Collections.Generic.IDictionary<string, object> _originalValues;
		
		private string _tytuł;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion

		Microsoft.SharePoint.Linq.EntityState Microsoft.SharePoint.Linq.ITrackEntityState.EntityState {
			get {
				return this._entityState;
			}
			set {
				if ((value != this._entityState)) {
					this._entityState = value;
				}
			}
		}

		System.Collections.Generic.IDictionary<string, object> Microsoft.SharePoint.Linq.ITrackOriginalValues.OriginalValues {
			get {
				if ((null == this._originalValues)) {
					this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
				}
				return this._originalValues;
			}
		}
		
		public Element() {
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ID", Storage="_identyfikator", ReadOnly=true, FieldType="Counter")]
		public System.Nullable<int> Identyfikator {
			get {
				return this._identyfikator;
			}
			set {
				if ((value != this._identyfikator)) {
					this.OnPropertyChanging("Identyfikator", this._identyfikator);
					this._identyfikator = value;
					this.OnPropertyChanged("Identyfikator");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="owshiddenversion", Storage="_wersja", ReadOnly=true, FieldType="Integer")]
		public System.Nullable<int> Wersja {
			get {
				return this._wersja;
			}
			set {
				if ((value != this._wersja)) {
					this.OnPropertyChanging("Wersja", this._wersja);
					this._wersja = value;
					this.OnPropertyChanged("Wersja");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="FileDirRef", Storage="_ścieżka", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
		public string Ścieżka {
			get {
				return this._ścieżka;
			}
			set {
				if ((value != this._ścieżka)) {
					this.OnPropertyChanging("Ścieżka", this._ścieżka);
					this._ścieżka = value;
					this.OnPropertyChanged("Ścieżka");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Title", Storage="_tytuł", Required=true, FieldType="Text")]
		public virtual string Tytuł {
			get {
				return this._tytuł;
			}
			set {
				if ((value != this._tytuł)) {
					this.OnPropertyChanging("Tytuł", this._tytuł);
					this._tytuł = value;
					this.OnPropertyChanged("Tytuł");
				}
			}
		}
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanged(string propertyName) {
			if ((null != this.PropertyChanged)) {
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		protected virtual void OnPropertyChanging(string propertyName, object value) {
			if ((null == this._originalValues)) {
				this._originalValues = new System.Collections.Generic.Dictionary<string, object>();
			}
			if ((false == this._originalValues.ContainsKey(propertyName))) {
				this._originalValues.Add(propertyName, value);
			}
			if ((null != this.PropertyChanging)) {
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
	}
	
	/// <summary>
	/// Utwórz nowe spotkanie, termin ostateczny lub inne wydarzenie.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Wydarzenie", Id="0x0102")]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(TimeSlot))]
	public partial class Wydarzenie : Element {
		
		private string _lokalizacja;
		
		protected System.Nullable<System.DateTime> _startTime;
		
		private System.Nullable<System.DateTime> _endTime;
		
		private string _description;
		
		private System.Nullable<bool> _wydarzenieCałodzienne;
		
		private System.Nullable<bool> _cykl;
		
		private System.Nullable<bool> _obszarRoboczy;
		
		private System.Nullable<Kategoria> _kategoria;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public Wydarzenie() {
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Location", Storage="_lokalizacja", FieldType="Text")]
		public virtual string Lokalizacja {
			get {
				return this._lokalizacja;
			}
			set {
				if ((value != this._lokalizacja)) {
					this.OnPropertyChanging("Lokalizacja", this._lokalizacja);
					this._lokalizacja = value;
					this.OnPropertyChanged("Lokalizacja");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="StartDate", Storage="_startTime", Required=true, FieldType="DateTime")]
		public virtual System.Nullable<System.DateTime> StartTime {
			get {
				return this._startTime;
			}
			set {
				if ((value != this._startTime)) {
					this.OnPropertyChanging("StartTime", this._startTime);
					this._startTime = value;
					this.OnPropertyChanged("StartTime");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EndDate", Storage="_endTime", Required=true, FieldType="DateTime")]
		public System.Nullable<System.DateTime> EndTime {
			get {
				return this._endTime;
			}
			set {
				if ((value != this._endTime)) {
					this.OnPropertyChanging("EndTime", this._endTime);
					this._endTime = value;
					this.OnPropertyChanged("EndTime");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Comments", Storage="_description", FieldType="Note")]
		public virtual string Description {
			get {
				return this._description;
			}
			set {
				if ((value != this._description)) {
					this.OnPropertyChanging("Description", this._description);
					this._description = value;
					this.OnPropertyChanged("Description");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="fAllDayEvent", Storage="_wydarzenieCałodzienne", FieldType="AllDayEvent")]
		public virtual System.Nullable<bool> WydarzenieCałodzienne {
			get {
				return this._wydarzenieCałodzienne;
			}
			set {
				if ((value != this._wydarzenieCałodzienne)) {
					this.OnPropertyChanging("WydarzenieCałodzienne", this._wydarzenieCałodzienne);
					this._wydarzenieCałodzienne = value;
					this.OnPropertyChanged("WydarzenieCałodzienne");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="fRecurrence", Storage="_cykl", FieldType="Recurrence")]
		public virtual System.Nullable<bool> Cykl {
			get {
				return this._cykl;
			}
			set {
				if ((value != this._cykl)) {
					this.OnPropertyChanging("Cykl", this._cykl);
					this._cykl = value;
					this.OnPropertyChanged("Cykl");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WorkspaceLink", Storage="_obszarRoboczy", FieldType="CrossProjectLink")]
		public virtual System.Nullable<bool> ObszarRoboczy {
			get {
				return this._obszarRoboczy;
			}
			set {
				if ((value != this._obszarRoboczy)) {
					this.OnPropertyChanging("ObszarRoboczy", this._obszarRoboczy);
					this._obszarRoboczy = value;
					this.OnPropertyChanged("ObszarRoboczy");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Category", Storage="_kategoria", FieldType="Choice")]
		public virtual System.Nullable<Kategoria> Kategoria {
			get {
				return this._kategoria;
			}
			set {
				if ((value != this._kategoria)) {
					this.OnPropertyChanging("Kategoria", this._kategoria);
					this._kategoria = value;
					this.OnPropertyChanged("Kategoria");
				}
			}
		}
	}
	
	/// <summary>
	/// Utwórz nowy element listy.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="AlarmsAndEvents", Id="0x010049AA7238FCE34BE18336F419AE924845")]
	public partial class AlarmsAndEvents : Element {
		
		private Microsoft.SharePoint.Linq.EntityRef<ShippingOperationInbound> _shippingIndex;
		
		private Microsoft.SharePoint.Linq.EntityRef<Partner> _vendorName;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public AlarmsAndEvents() {
			this._shippingIndex = new Microsoft.SharePoint.Linq.EntityRef<ShippingOperationInbound>();
			this._shippingIndex.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound>>(this.OnShippingIndexSync);
			this._shippingIndex.OnChanged += new System.EventHandler(this.OnShippingIndexChanged);
			this._shippingIndex.OnChanging += new System.EventHandler(this.OnShippingIndexChanging);
			this._vendorName = new Microsoft.SharePoint.Linq.EntityRef<Partner>();
			this._vendorName.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Partner>>(this.OnVendorNameSync);
			this._vendorName.OnChanged += new System.EventHandler(this.OnVendorNameChanged);
			this._vendorName.OnChanging += new System.EventHandler(this.OnVendorNameChanging);
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="ShippingIndex", Storage="_shippingIndex", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Shipping")]
		public ShippingOperationInbound ShippingIndex {
			get {
				return this._shippingIndex.GetEntity();
			}
			set {
				this._shippingIndex.SetEntity(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="PartnerTitle", Storage="_vendorName", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="JTI Partner")]
		public Partner VendorName {
			get {
				return this._vendorName.GetEntity();
			}
			set {
				this._vendorName.SetEntity(value);
			}
		}
		
		private void OnShippingIndexChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("ShippingIndex", this._shippingIndex.Clone());
		}
		
		private void OnShippingIndexChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("ShippingIndex");
		}
		
		private void OnShippingIndexSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound> e) {
		}
		
		private void OnVendorNameChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("VendorName", this._vendorName.Clone());
		}
		
		private void OnVendorNameChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("VendorName");
		}
		
		private void OnVendorNameSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Partner> e) {
		}
	}
	
	/// <summary>
	/// Utwórz nowy element listy.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Driver", Id="0x0100B0982F01816047B1ABFF933B9F49B5DB")]
	public partial class Driver : Element {
		
		private string _identityDocumentNumber;
		
		private string _numerTelefonuKomórkowego;
		
		private Microsoft.SharePoint.Linq.EntityRef<Partner> _vendorName;
		
		private Microsoft.SharePoint.Linq.EntitySet<ShippingDriversTeam> _shippingDriversTeam;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public Driver() {
			this._vendorName = new Microsoft.SharePoint.Linq.EntityRef<Partner>();
			this._vendorName.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Partner>>(this.OnVendorNameSync);
			this._vendorName.OnChanged += new System.EventHandler(this.OnVendorNameChanged);
			this._vendorName.OnChanging += new System.EventHandler(this.OnVendorNameChanging);
			this._shippingDriversTeam = new Microsoft.SharePoint.Linq.EntitySet<ShippingDriversTeam>();
			this._shippingDriversTeam.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingDriversTeam>>(this.OnShippingDriversTeamSync);
			this._shippingDriversTeam.OnChanged += new System.EventHandler(this.OnShippingDriversTeamChanged);
			this._shippingDriversTeam.OnChanging += new System.EventHandler(this.OnShippingDriversTeamChanging);
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="IdentityDocumentNumber", Storage="_identityDocumentNumber", FieldType="Text")]
		public string IdentityDocumentNumber {
			get {
				return this._identityDocumentNumber;
			}
			set {
				if ((value != this._identityDocumentNumber)) {
					this.OnPropertyChanging("IdentityDocumentNumber", this._identityDocumentNumber);
					this._identityDocumentNumber = value;
					this.OnPropertyChanged("IdentityDocumentNumber");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="CellPhone", Storage="_numerTelefonuKomórkowego", FieldType="Text")]
		public string NumerTelefonuKomórkowego {
			get {
				return this._numerTelefonuKomórkowego;
			}
			set {
				if ((value != this._numerTelefonuKomórkowego)) {
					this.OnPropertyChanging("NumerTelefonuKomórkowego", this._numerTelefonuKomórkowego);
					this._numerTelefonuKomórkowego = value;
					this.OnPropertyChanged("NumerTelefonuKomórkowego");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="PartnerTitle", Storage="_vendorName", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="JTI Partner")]
		public Partner VendorName {
			get {
				return this._vendorName.GetEntity();
			}
			set {
				this._vendorName.SetEntity(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="DriverTitle", Storage="_shippingDriversTeam", ReadOnly=true, MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Backward, List="Drivers Team")]
		public Microsoft.SharePoint.Linq.EntitySet<ShippingDriversTeam> ShippingDriversTeam {
			get {
				return this._shippingDriversTeam;
			}
			set {
				this._shippingDriversTeam.Assign(value);
			}
		}
		
		private void OnVendorNameChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("VendorName", this._vendorName.Clone());
		}
		
		private void OnVendorNameChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("VendorName");
		}
		
		private void OnVendorNameSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Partner> e) {
		}
		
		private void OnShippingDriversTeamChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("ShippingDriversTeam", this._shippingDriversTeam.Clone());
		}
		
		private void OnShippingDriversTeamChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("ShippingDriversTeam");
		}
		
		private void OnShippingDriversTeamSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingDriversTeam> e) {
			if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
				e.Item.Driver = this;
			}
			else {
				e.Item.Driver = null;
			}
		}
	}
	
	/// <summary>
	/// Drivers Team
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="ShippingDriversTeam", Id="0x01000A5D8B5F3F67453882811C27556D5D30")]
	public partial class ShippingDriversTeam : Element {
		
		private Microsoft.SharePoint.Linq.EntityRef<Driver> _driver;
		
		private Microsoft.SharePoint.Linq.EntityRef<ShippingOperationInbound> _shippingIndex;
		
		private Microsoft.SharePoint.Linq.EntitySet<ShippingOperationInbound> _shippingOperationInbound;
		
		private Microsoft.SharePoint.Linq.EntitySet<ShippingOperationOutbound> _shippingOperationOutbound;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public ShippingDriversTeam() {
			this._driver = new Microsoft.SharePoint.Linq.EntityRef<Driver>();
			this._driver.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Driver>>(this.OnDriverSync);
			this._driver.OnChanged += new System.EventHandler(this.OnDriverChanged);
			this._driver.OnChanging += new System.EventHandler(this.OnDriverChanging);
			this._shippingIndex = new Microsoft.SharePoint.Linq.EntityRef<ShippingOperationInbound>();
			this._shippingIndex.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound>>(this.OnShippingIndexSync);
			this._shippingIndex.OnChanged += new System.EventHandler(this.OnShippingIndexChanged);
			this._shippingIndex.OnChanging += new System.EventHandler(this.OnShippingIndexChanging);
			this._shippingOperationInbound = new Microsoft.SharePoint.Linq.EntitySet<ShippingOperationInbound>();
			this._shippingOperationInbound.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound>>(this.OnShippingOperationInboundSync);
			this._shippingOperationInbound.OnChanged += new System.EventHandler(this.OnShippingOperationInboundChanged);
			this._shippingOperationInbound.OnChanging += new System.EventHandler(this.OnShippingOperationInboundChanging);
			this._shippingOperationOutbound = new Microsoft.SharePoint.Linq.EntitySet<ShippingOperationOutbound>();
			this._shippingOperationOutbound.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationOutbound>>(this.OnShippingOperationOutboundSync);
			this._shippingOperationOutbound.OnChanged += new System.EventHandler(this.OnShippingOperationOutboundChanged);
			this._shippingOperationOutbound.OnChanging += new System.EventHandler(this.OnShippingOperationOutboundChanging);
			this.OnCreated();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
		public override string Tytuł {
			get {
				throw new System.InvalidOperationException("Pole Title zostało usunięte z typu zawartości ShippingDriversTeam.");
			}
			set {
				throw new System.InvalidOperationException("Pole Title zostało usunięte z typu zawartości ShippingDriversTeam.");
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="DriverTitle", Storage="_driver", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Driver")]
		public Driver Driver {
			get {
				return this._driver.GetEntity();
			}
			set {
				this._driver.SetEntity(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="ShippingIndex", Storage="_shippingIndex", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Shipping")]
		public ShippingOperationInbound ShippingIndex {
			get {
				return this._shippingIndex.GetEntity();
			}
			set {
				this._shippingIndex.SetEntity(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="ShippingDriversTeamTitle", Storage="_shippingOperationInbound", ReadOnly=true, MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Backward, List="Shipping")]
		public Microsoft.SharePoint.Linq.EntitySet<ShippingOperationInbound> ShippingOperationInbound {
			get {
				return this._shippingOperationInbound;
			}
			set {
				this._shippingOperationInbound.Assign(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="ShippingSecurityEscortTeamTitle", Storage="_shippingOperationOutbound", ReadOnly=true, MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Backward, List="Shipping")]
		public Microsoft.SharePoint.Linq.EntitySet<ShippingOperationOutbound> ShippingOperationOutbound {
			get {
				return this._shippingOperationOutbound;
			}
			set {
				this._shippingOperationOutbound.Assign(value);
			}
		}
		
		private void OnDriverChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("Driver", this._driver.Clone());
		}
		
		private void OnDriverChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("Driver");
		}
		
		private void OnDriverSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Driver> e) {
			if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
				e.Item.ShippingDriversTeam.Add(this);
			}
			else {
				e.Item.ShippingDriversTeam.Remove(this);
			}
		}
		
		private void OnShippingIndexChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("ShippingIndex", this._shippingIndex.Clone());
		}
		
		private void OnShippingIndexChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("ShippingIndex");
		}
		
		private void OnShippingIndexSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound> e) {
		}
		
		private void OnShippingOperationInboundChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("ShippingOperationInbound", this._shippingOperationInbound.Clone());
		}
		
		private void OnShippingOperationInboundChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("ShippingOperationInbound");
		}
		
		private void OnShippingOperationInboundSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound> e) {
			if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
				e.Item.DriversTeam = this;
			}
			else {
				e.Item.DriversTeam = null;
			}
		}
		
		private void OnShippingOperationOutboundChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("ShippingOperationOutbound", this._shippingOperationOutbound.Clone());
		}
		
		private void OnShippingOperationOutboundChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("ShippingOperationOutbound");
		}
		
		private void OnShippingOperationOutboundSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationOutbound> e) {
			if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
				e.Item.SecurityEscortTeam = this;
			}
			else {
				e.Item.SecurityEscortTeam = null;
			}
		}
	}
	
	/// <summary>
	/// Utwórz nowy element listy.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Partner", Id="0x010017A675502BE747DB9FB9DCB304429EEF")]
	public partial class Partner : Element {
		
		private string _vendorNumberFromSAP;
		
		private string _adresEMail;
		
		private string _telefonSłużbowy;
		
		private string _numerTelefonuKomórkowego;
		
		private System.Nullable<ServiceType> _serviceType;
		
		private System.Nullable<int> _shepherdUserIdentyfikator;
		
		private string _shepherdUserTitle;
		
		private Microsoft.SharePoint.Linq.EntityRef<Warehouse> _warehouse;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public Partner() {
			this._warehouse = new Microsoft.SharePoint.Linq.EntityRef<Warehouse>();
			this._warehouse.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Warehouse>>(this.OnWarehouseSync);
			this._warehouse.OnChanged += new System.EventHandler(this.OnWarehouseChanged);
			this._warehouse.OnChanging += new System.EventHandler(this.OnWarehouseChanging);
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="VendorNumber", Storage="_vendorNumberFromSAP", FieldType="Text")]
		public string VendorNumberFromSAP {
			get {
				return this._vendorNumberFromSAP;
			}
			set {
				if ((value != this._vendorNumberFromSAP)) {
					this.OnPropertyChanging("VendorNumberFromSAP", this._vendorNumberFromSAP);
					this._vendorNumberFromSAP = value;
					this.OnPropertyChanged("VendorNumberFromSAP");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EMail", Storage="_adresEMail", FieldType="Text")]
		public string AdresEMail {
			get {
				return this._adresEMail;
			}
			set {
				if ((value != this._adresEMail)) {
					this.OnPropertyChanging("AdresEMail", this._adresEMail);
					this._adresEMail = value;
					this.OnPropertyChanged("AdresEMail");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="WorkPhone", Storage="_telefonSłużbowy", FieldType="Text")]
		public string TelefonSłużbowy {
			get {
				return this._telefonSłużbowy;
			}
			set {
				if ((value != this._telefonSłużbowy)) {
					this.OnPropertyChanging("TelefonSłużbowy", this._telefonSłużbowy);
					this._telefonSłużbowy = value;
					this.OnPropertyChanged("TelefonSłużbowy");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="CellPhone", Storage="_numerTelefonuKomórkowego", FieldType="Text")]
		public string NumerTelefonuKomórkowego {
			get {
				return this._numerTelefonuKomórkowego;
			}
			set {
				if ((value != this._numerTelefonuKomórkowego)) {
					this.OnPropertyChanging("NumerTelefonuKomórkowego", this._numerTelefonuKomórkowego);
					this._numerTelefonuKomórkowego = value;
					this.OnPropertyChanged("NumerTelefonuKomórkowego");
				}
			}
		}
		
		/// <summary>
		/// Service
		/// </summary>
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ServiceType", Storage="_serviceType", FieldType="Choice")]
		public System.Nullable<ServiceType> ServiceType {
			get {
				return this._serviceType;
			}
			set {
				if ((value != this._serviceType)) {
					this.OnPropertyChanging("ServiceType", this._serviceType);
					this._serviceType = value;
					this.OnPropertyChanged("ServiceType");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ShepherdUser", Storage="_shepherdUserIdentyfikator", Required=true, FieldType="User", IsLookupId=true)]
		public System.Nullable<int> ShepherdUserIdentyfikator {
			get {
				return this._shepherdUserIdentyfikator;
			}
			set {
				if ((value != this._shepherdUserIdentyfikator)) {
					this.OnPropertyChanging("ShepherdUserIdentyfikator", this._shepherdUserIdentyfikator);
					this._shepherdUserIdentyfikator = value;
					this.OnPropertyChanged("ShepherdUserIdentyfikator");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ShepherdUser", Storage="_shepherdUserTitle", ReadOnly=true, FieldType="User", IsLookupValue=true)]
		public string ShepherdUserTitle {
			get {
				return this._shepherdUserTitle;
			}
			set {
				if ((value != this._shepherdUserTitle)) {
					this.OnPropertyChanging("ShepherdUserTitle", this._shepherdUserTitle);
					this._shepherdUserTitle = value;
					this.OnPropertyChanged("ShepherdUserTitle");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="WarehouseTitle", Storage="_warehouse", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Warehouse")]
		public Warehouse Warehouse {
			get {
				return this._warehouse.GetEntity();
			}
			set {
				this._warehouse.SetEntity(value);
			}
		}
		
		private void OnWarehouseChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("Warehouse", this._warehouse.Clone());
		}
		
		private void OnWarehouseChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("Warehouse");
		}
		
		private void OnWarehouseSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Warehouse> e) {
		}
	}
	
	/// <summary>
	/// Utwórz nowy element listy.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="LoadDescription", Id="0x0100F5C0C5AAA44E47B1A7CCFECEE1E8E94E")]
	public partial class LoadDescription : Element {
		
		private string _deliveryNumber;
		
		private System.Nullable<double> _goodsQuantity;
		
		private System.Nullable<double> _numberOfPallets;
		
		private Microsoft.SharePoint.Linq.EntityRef<ShippingOperationInbound> _shippingIndex;
		
		private System.Nullable<int> _marketIdentyfikator;
		
		private string _marketTitle;
		
		private System.Nullable<int> _palletTypesIdentyfikator;
		
		private string _palletTypesTitle;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public LoadDescription() {
			this._shippingIndex = new Microsoft.SharePoint.Linq.EntityRef<ShippingOperationInbound>();
			this._shippingIndex.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound>>(this.OnShippingIndexSync);
			this._shippingIndex.OnChanged += new System.EventHandler(this.OnShippingIndexChanged);
			this._shippingIndex.OnChanging += new System.EventHandler(this.OnShippingIndexChanging);
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DeliveryNumber", Storage="_deliveryNumber", FieldType="Text")]
		public string DeliveryNumber {
			get {
				return this._deliveryNumber;
			}
			set {
				if ((value != this._deliveryNumber)) {
					this.OnPropertyChanging("DeliveryNumber", this._deliveryNumber);
					this._deliveryNumber = value;
					this.OnPropertyChanged("DeliveryNumber");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GoodsQuantity", Storage="_goodsQuantity", FieldType="Number")]
		public System.Nullable<double> GoodsQuantity {
			get {
				return this._goodsQuantity;
			}
			set {
				if ((value != this._goodsQuantity)) {
					this.OnPropertyChanging("GoodsQuantity", this._goodsQuantity);
					this._goodsQuantity = value;
					this.OnPropertyChanged("GoodsQuantity");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="NumberOfPallets", Storage="_numberOfPallets", FieldType="Number")]
		public System.Nullable<double> NumberOfPallets {
			get {
				return this._numberOfPallets;
			}
			set {
				if ((value != this._numberOfPallets)) {
					this.OnPropertyChanging("NumberOfPallets", this._numberOfPallets);
					this._numberOfPallets = value;
					this.OnPropertyChanged("NumberOfPallets");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="ShippingIndex", Storage="_shippingIndex", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Shipping")]
		public ShippingOperationInbound ShippingIndex {
			get {
				return this._shippingIndex.GetEntity();
			}
			set {
				this._shippingIndex.SetEntity(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MarketTitle", Storage="_marketIdentyfikator", FieldType="Lookup", IsLookupId=true)]
		public System.Nullable<int> MarketIdentyfikator {
			get {
				return this._marketIdentyfikator;
			}
			set {
				if ((value != this._marketIdentyfikator)) {
					this.OnPropertyChanging("MarketIdentyfikator", this._marketIdentyfikator);
					this._marketIdentyfikator = value;
					this.OnPropertyChanged("MarketIdentyfikator");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="MarketTitle", Storage="_marketTitle", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
		public string MarketTitle {
			get {
				return this._marketTitle;
			}
			set {
				if ((value != this._marketTitle)) {
					this.OnPropertyChanging("MarketTitle", this._marketTitle);
					this._marketTitle = value;
					this.OnPropertyChanged("MarketTitle");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PalletTypesTitle", Storage="_palletTypesIdentyfikator", FieldType="Lookup", IsLookupId=true)]
		public System.Nullable<int> PalletTypesIdentyfikator {
			get {
				return this._palletTypesIdentyfikator;
			}
			set {
				if ((value != this._palletTypesIdentyfikator)) {
					this.OnPropertyChanging("PalletTypesIdentyfikator", this._palletTypesIdentyfikator);
					this._palletTypesIdentyfikator = value;
					this.OnPropertyChanged("PalletTypesIdentyfikator");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="PalletTypesTitle", Storage="_palletTypesTitle", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
		public string PalletTypesTitle {
			get {
				return this._palletTypesTitle;
			}
			set {
				if ((value != this._palletTypesTitle)) {
					this.OnPropertyChanging("PalletTypesTitle", this._palletTypesTitle);
					this._palletTypesTitle = value;
					this.OnPropertyChanged("PalletTypesTitle");
				}
			}
		}
		
		private void OnShippingIndexChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("ShippingIndex", this._shippingIndex.Clone());
		}
		
		private void OnShippingIndexChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("ShippingIndex");
		}
		
		private void OnShippingIndexSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound> e) {
		}
	}
	
	/// <summary>
	/// Utwórz nowy element listy.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="ShippingOperationInbound", Id="0x010047C1F2AB865840E598FE69DEC5D5B021")]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(ShippingOperationOutbound))]
	public partial class ShippingOperationInbound : Element {
		
		private System.Nullable<double> _dockNumber;
		
		private System.Nullable<System.DateTime> _startTime;
		
		private System.Nullable<double> _duration;
		
		private System.Nullable<double> _cancelationReason;
		
		private System.Nullable<State> _state;
		
		private Microsoft.SharePoint.Linq.EntityRef<Partner> _vendorName;
		
		private Microsoft.SharePoint.Linq.EntityRef<ShippingPoint> _shippingPoint;
		
		private Microsoft.SharePoint.Linq.EntityRef<Truck> _truckCarRegistrationNumber;
		
		private Microsoft.SharePoint.Linq.EntityRef<Trailer> _trailerRegistrationNumber;
		
		private Microsoft.SharePoint.Linq.EntityRef<ShippingDriversTeam> _driversTeam;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public ShippingOperationInbound() {
			this._vendorName = new Microsoft.SharePoint.Linq.EntityRef<Partner>();
			this._vendorName.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Partner>>(this.OnVendorNameSync);
			this._vendorName.OnChanged += new System.EventHandler(this.OnVendorNameChanged);
			this._vendorName.OnChanging += new System.EventHandler(this.OnVendorNameChanging);
			this._shippingPoint = new Microsoft.SharePoint.Linq.EntityRef<ShippingPoint>();
			this._shippingPoint.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingPoint>>(this.OnShippingPointSync);
			this._shippingPoint.OnChanged += new System.EventHandler(this.OnShippingPointChanged);
			this._shippingPoint.OnChanging += new System.EventHandler(this.OnShippingPointChanging);
			this._truckCarRegistrationNumber = new Microsoft.SharePoint.Linq.EntityRef<Truck>();
			this._truckCarRegistrationNumber.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Truck>>(this.OnTruckCarRegistrationNumberSync);
			this._truckCarRegistrationNumber.OnChanged += new System.EventHandler(this.OnTruckCarRegistrationNumberChanged);
			this._truckCarRegistrationNumber.OnChanging += new System.EventHandler(this.OnTruckCarRegistrationNumberChanging);
			this._trailerRegistrationNumber = new Microsoft.SharePoint.Linq.EntityRef<Trailer>();
			this._trailerRegistrationNumber.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Trailer>>(this.OnTrailerRegistrationNumberSync);
			this._trailerRegistrationNumber.OnChanged += new System.EventHandler(this.OnTrailerRegistrationNumberChanged);
			this._trailerRegistrationNumber.OnChanging += new System.EventHandler(this.OnTrailerRegistrationNumberChanging);
			this._driversTeam = new Microsoft.SharePoint.Linq.EntityRef<ShippingDriversTeam>();
			this._driversTeam.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingDriversTeam>>(this.OnDriversTeamSync);
			this._driversTeam.OnChanged += new System.EventHandler(this.OnDriversTeamChanged);
			this._driversTeam.OnChanging += new System.EventHandler(this.OnDriversTeamChanging);
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="DockNumber", Storage="_dockNumber", FieldType="Number")]
		public System.Nullable<double> DockNumber {
			get {
				return this._dockNumber;
			}
			set {
				if ((value != this._dockNumber)) {
					this.OnPropertyChanging("DockNumber", this._dockNumber);
					this._dockNumber = value;
					this.OnPropertyChanged("DockNumber");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="StartTime", Storage="_startTime", FieldType="DateTime")]
		public System.Nullable<System.DateTime> StartTime {
			get {
				return this._startTime;
			}
			set {
				if ((value != this._startTime)) {
					this.OnPropertyChanging("StartTime", this._startTime);
					this._startTime = value;
					this.OnPropertyChanged("StartTime");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ShippingDuration", Storage="_duration", FieldType="Number")]
		public System.Nullable<double> Duration {
			get {
				return this._duration;
			}
			set {
				if ((value != this._duration)) {
					this.OnPropertyChanging("Duration", this._duration);
					this._duration = value;
					this.OnPropertyChanged("Duration");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="CancelationReason", Storage="_cancelationReason", FieldType="Number")]
		public System.Nullable<double> CancelationReason {
			get {
				return this._cancelationReason;
			}
			set {
				if ((value != this._cancelationReason)) {
					this.OnPropertyChanging("CancelationReason", this._cancelationReason);
					this._cancelationReason = value;
					this.OnPropertyChanged("CancelationReason");
				}
			}
		}
		
		/// <summary>
		/// Direction
		/// </summary>
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ShippingState", Storage="_state", FieldType="Choice")]
		public System.Nullable<State> State {
			get {
				return this._state;
			}
			set {
				if ((value != this._state)) {
					this.OnPropertyChanging("State", this._state);
					this._state = value;
					this.OnPropertyChanged("State");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="PartnerTitle", Storage="_vendorName", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="JTI Partner")]
		public Partner VendorName {
			get {
				return this._vendorName.GetEntity();
			}
			set {
				this._vendorName.SetEntity(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="ShippingPointTitle", Storage="_shippingPoint", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Shipping Point")]
		public ShippingPoint ShippingPoint {
			get {
				return this._shippingPoint.GetEntity();
			}
			set {
				this._shippingPoint.SetEntity(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="TruckTitle", Storage="_truckCarRegistrationNumber", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Truck")]
		public Truck TruckCarRegistrationNumber {
			get {
				return this._truckCarRegistrationNumber.GetEntity();
			}
			set {
				this._truckCarRegistrationNumber.SetEntity(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="TrailerTitle", Storage="_trailerRegistrationNumber", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Trailer")]
		public Trailer TrailerRegistrationNumber {
			get {
				return this._trailerRegistrationNumber.GetEntity();
			}
			set {
				this._trailerRegistrationNumber.SetEntity(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="ShippingDriversTeamTitle", Storage="_driversTeam", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Drivers Team")]
		public ShippingDriversTeam DriversTeam {
			get {
				return this._driversTeam.GetEntity();
			}
			set {
				this._driversTeam.SetEntity(value);
			}
		}
		
		private void OnVendorNameChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("VendorName", this._vendorName.Clone());
		}
		
		private void OnVendorNameChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("VendorName");
		}
		
		private void OnVendorNameSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Partner> e) {
		}
		
		private void OnShippingPointChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("ShippingPoint", this._shippingPoint.Clone());
		}
		
		private void OnShippingPointChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("ShippingPoint");
		}
		
		private void OnShippingPointSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingPoint> e) {
		}
		
		private void OnTruckCarRegistrationNumberChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("TruckCarRegistrationNumber", this._truckCarRegistrationNumber.Clone());
		}
		
		private void OnTruckCarRegistrationNumberChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("TruckCarRegistrationNumber");
		}
		
		private void OnTruckCarRegistrationNumberSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Truck> e) {
			if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
				e.Item.ShippingOperationInbound.Add(this);
			}
			else {
				e.Item.ShippingOperationInbound.Remove(this);
			}
		}
		
		private void OnTrailerRegistrationNumberChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("TrailerRegistrationNumber", this._trailerRegistrationNumber.Clone());
		}
		
		private void OnTrailerRegistrationNumberChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("TrailerRegistrationNumber");
		}
		
		private void OnTrailerRegistrationNumberSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Trailer> e) {
			if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
				e.Item.ShippingOperationInbound.Add(this);
			}
			else {
				e.Item.ShippingOperationInbound.Remove(this);
			}
		}
		
		private void OnDriversTeamChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("DriversTeam", this._driversTeam.Clone());
		}
		
		private void OnDriversTeamChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("DriversTeam");
		}
		
		private void OnDriversTeamSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingDriversTeam> e) {
			if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
				e.Item.ShippingOperationInbound.Add(this);
			}
			else {
				e.Item.ShippingOperationInbound.Remove(this);
			}
		}
	}
	
	/// <summary>
	/// Utwórz nowy element listy.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="ShippingPoint", Id="0x0100CB62286DE09CE54780611F275F43DB47")]
	public partial class ShippingPoint : Element {
		
		private string _description;
		
		private System.Nullable<Direction> _direction;
		
		private Microsoft.SharePoint.Linq.EntityRef<Warehouse> _warehouse;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public ShippingPoint() {
			this._warehouse = new Microsoft.SharePoint.Linq.EntityRef<Warehouse>();
			this._warehouse.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Warehouse>>(this.OnWarehouseSync);
			this._warehouse.OnChanged += new System.EventHandler(this.OnWarehouseChanged);
			this._warehouse.OnChanging += new System.EventHandler(this.OnWarehouseChanging);
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ShippingPointDescription", Storage="_description", FieldType="Text")]
		public string Description {
			get {
				return this._description;
			}
			set {
				if ((value != this._description)) {
					this.OnPropertyChanging("Description", this._description);
					this._description = value;
					this.OnPropertyChanged("Description");
				}
			}
		}
		
		/// <summary>
		/// Direction
		/// </summary>
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Direction", Storage="_direction", FieldType="Choice")]
		public System.Nullable<Direction> Direction {
			get {
				return this._direction;
			}
			set {
				if ((value != this._direction)) {
					this.OnPropertyChanging("Direction", this._direction);
					this._direction = value;
					this.OnPropertyChanged("Direction");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="WarehouseTitle", Storage="_warehouse", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Warehouse")]
		public Warehouse Warehouse {
			get {
				return this._warehouse.GetEntity();
			}
			set {
				this._warehouse.SetEntity(value);
			}
		}
		
		private void OnWarehouseChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("Warehouse", this._warehouse.Clone());
		}
		
		private void OnWarehouseChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("Warehouse");
		}
		
		private void OnWarehouseSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Warehouse> e) {
		}
	}
	
	/// <summary>
	/// Utwórz nowy element listy.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Trailer", Id="0x01009EF7D9CEE9664A48928AD8C8857ADA95")]
	public partial class Trailer : Element {
		
		private string _comments;
		
		private Microsoft.SharePoint.Linq.EntitySet<ShippingOperationInbound> _shippingOperationInbound;
		
		private Microsoft.SharePoint.Linq.EntityRef<Partner> _vendorName;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public Trailer() {
			this._shippingOperationInbound = new Microsoft.SharePoint.Linq.EntitySet<ShippingOperationInbound>();
			this._shippingOperationInbound.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound>>(this.OnShippingOperationInboundSync);
			this._shippingOperationInbound.OnChanged += new System.EventHandler(this.OnShippingOperationInboundChanged);
			this._shippingOperationInbound.OnChanging += new System.EventHandler(this.OnShippingOperationInboundChanging);
			this._vendorName = new Microsoft.SharePoint.Linq.EntityRef<Partner>();
			this._vendorName.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Partner>>(this.OnVendorNameSync);
			this._vendorName.OnChanged += new System.EventHandler(this.OnVendorNameChanged);
			this._vendorName.OnChanging += new System.EventHandler(this.OnVendorNameChanging);
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AdditionalComments", Storage="_comments", FieldType="Text")]
		public string Comments {
			get {
				return this._comments;
			}
			set {
				if ((value != this._comments)) {
					this.OnPropertyChanging("Comments", this._comments);
					this._comments = value;
					this.OnPropertyChanged("Comments");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="TrailerTitle", Storage="_shippingOperationInbound", ReadOnly=true, MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Backward, List="Shipping")]
		public Microsoft.SharePoint.Linq.EntitySet<ShippingOperationInbound> ShippingOperationInbound {
			get {
				return this._shippingOperationInbound;
			}
			set {
				this._shippingOperationInbound.Assign(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="PartnerTitle", Storage="_vendorName", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="JTI Partner")]
		public Partner VendorName {
			get {
				return this._vendorName.GetEntity();
			}
			set {
				this._vendorName.SetEntity(value);
			}
		}
		
		private void OnShippingOperationInboundChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("ShippingOperationInbound", this._shippingOperationInbound.Clone());
		}
		
		private void OnShippingOperationInboundChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("ShippingOperationInbound");
		}
		
		private void OnShippingOperationInboundSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound> e) {
			if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
				e.Item.TrailerRegistrationNumber = this;
			}
			else {
				e.Item.TrailerRegistrationNumber = null;
			}
		}
		
		private void OnVendorNameChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("VendorName", this._vendorName.Clone());
		}
		
		private void OnVendorNameChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("VendorName");
		}
		
		private void OnVendorNameSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Partner> e) {
		}
	}
	
	/// <summary>
	/// Utwórz nowy element listy.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Truck", Id="0x01003E7761AEF97A4C619F44D01B53A56568")]
	public partial class Truck : Element {
		
		private string _comments;
		
		private System.Nullable<VehicleType> _vehicleType;
		
		private Microsoft.SharePoint.Linq.EntitySet<ShippingOperationInbound> _shippingOperationInbound;
		
		private Microsoft.SharePoint.Linq.EntityRef<Partner> _vendorName;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public Truck() {
			this._shippingOperationInbound = new Microsoft.SharePoint.Linq.EntitySet<ShippingOperationInbound>();
			this._shippingOperationInbound.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound>>(this.OnShippingOperationInboundSync);
			this._shippingOperationInbound.OnChanged += new System.EventHandler(this.OnShippingOperationInboundChanged);
			this._shippingOperationInbound.OnChanging += new System.EventHandler(this.OnShippingOperationInboundChanging);
			this._vendorName = new Microsoft.SharePoint.Linq.EntityRef<Partner>();
			this._vendorName.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Partner>>(this.OnVendorNameSync);
			this._vendorName.OnChanged += new System.EventHandler(this.OnVendorNameChanged);
			this._vendorName.OnChanging += new System.EventHandler(this.OnVendorNameChanging);
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="AdditionalComments", Storage="_comments", FieldType="Text")]
		public string Comments {
			get {
				return this._comments;
			}
			set {
				if ((value != this._comments)) {
					this.OnPropertyChanging("Comments", this._comments);
					this._comments = value;
					this.OnPropertyChanged("Comments");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="VehicleType", Storage="_vehicleType", FieldType="Choice")]
		public System.Nullable<VehicleType> VehicleType {
			get {
				return this._vehicleType;
			}
			set {
				if ((value != this._vehicleType)) {
					this.OnPropertyChanging("VehicleType", this._vehicleType);
					this._vehicleType = value;
					this.OnPropertyChanged("VehicleType");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="TruckTitle", Storage="_shippingOperationInbound", ReadOnly=true, MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Backward, List="Shipping")]
		public Microsoft.SharePoint.Linq.EntitySet<ShippingOperationInbound> ShippingOperationInbound {
			get {
				return this._shippingOperationInbound;
			}
			set {
				this._shippingOperationInbound.Assign(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="PartnerTitle", Storage="_vendorName", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="JTI Partner")]
		public Partner VendorName {
			get {
				return this._vendorName.GetEntity();
			}
			set {
				this._vendorName.SetEntity(value);
			}
		}
		
		private void OnShippingOperationInboundChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("ShippingOperationInbound", this._shippingOperationInbound.Clone());
		}
		
		private void OnShippingOperationInboundChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("ShippingOperationInbound");
		}
		
		private void OnShippingOperationInboundSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound> e) {
			if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
				e.Item.TruckCarRegistrationNumber = this;
			}
			else {
				e.Item.TruckCarRegistrationNumber = null;
			}
		}
		
		private void OnVendorNameChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("VendorName", this._vendorName.Clone());
		}
		
		private void OnVendorNameChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("VendorName");
		}
		
		private void OnVendorNameSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<Partner> e) {
		}
	}
	
	/// <summary>
	/// Utwórz nowy element listy.
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="Warehouse", Id="0x01001E57547208B49B46B4AA7CB4536B1A55")]
	public partial class Warehouse : Element {
		
		private System.Nullable<int> _commodityIdentyfikator;
		
		private string _commodityTitle;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public Warehouse() {
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="CommodityTitle", Storage="_commodityIdentyfikator", FieldType="Lookup", IsLookupId=true)]
		public System.Nullable<int> CommodityIdentyfikator {
			get {
				return this._commodityIdentyfikator;
			}
			set {
				if ((value != this._commodityIdentyfikator)) {
					this.OnPropertyChanging("CommodityIdentyfikator", this._commodityIdentyfikator);
					this._commodityIdentyfikator = value;
					this.OnPropertyChanged("CommodityIdentyfikator");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="CommodityTitle", Storage="_commodityTitle", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
		public string CommodityTitle {
			get {
				return this._commodityTitle;
			}
			set {
				if ((value != this._commodityTitle)) {
					this.OnPropertyChanging("CommodityTitle", this._commodityTitle);
					this._commodityTitle = value;
					this.OnPropertyChanged("CommodityTitle");
				}
			}
		}
	}
	
	/// <summary>
	/// Time Slot
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="TimeSlot", Id="0x0102008B8977AFA9104B18B4B25D7C06A4A3AA")]
	[Microsoft.SharePoint.Linq.DerivedEntityClassAttribute(Type=typeof(TimeSlotTimeSlot))]
	public partial class TimeSlot : Wydarzenie {
		
		private System.Nullable<System.DateTime> _actualTime;
		
		private System.Nullable<System.DateTime> _actualTimeSpan;
		
		private System.Nullable<System.DateTime> _timeSpan;
		
		private System.Nullable<bool> _occupied;
		
		private Microsoft.SharePoint.Linq.EntityRef<ShippingOperationInbound> _shippingIndex;
		
		private Microsoft.SharePoint.Linq.EntityRef<ShippingPoint> _shippingPoint;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public TimeSlot() {
			this._shippingIndex = new Microsoft.SharePoint.Linq.EntityRef<ShippingOperationInbound>();
			this._shippingIndex.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound>>(this.OnShippingIndexSync);
			this._shippingIndex.OnChanged += new System.EventHandler(this.OnShippingIndexChanged);
			this._shippingIndex.OnChanging += new System.EventHandler(this.OnShippingIndexChanging);
			this._shippingPoint = new Microsoft.SharePoint.Linq.EntityRef<ShippingPoint>();
			this._shippingPoint.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingPoint>>(this.OnShippingPointSync);
			this._shippingPoint.OnChanged += new System.EventHandler(this.OnShippingPointChanged);
			this._shippingPoint.OnChanging += new System.EventHandler(this.OnShippingPointChanging);
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ShippingActualTime", Storage="_actualTime", FieldType="DateTime")]
		public System.Nullable<System.DateTime> ActualTime {
			get {
				return this._actualTime;
			}
			set {
				if ((value != this._actualTime)) {
					this.OnPropertyChanging("ActualTime", this._actualTime);
					this._actualTime = value;
					this.OnPropertyChanged("ActualTime");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ShipingActualTimeSpan", Storage="_actualTimeSpan", FieldType="DateTime")]
		public System.Nullable<System.DateTime> ActualTimeSpan {
			get {
				return this._actualTimeSpan;
			}
			set {
				if ((value != this._actualTimeSpan)) {
					this.OnPropertyChanging("ActualTimeSpan", this._actualTimeSpan);
					this._actualTimeSpan = value;
					this.OnPropertyChanged("ActualTimeSpan");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="ShipingTimeSpan", Storage="_timeSpan", FieldType="DateTime")]
		public System.Nullable<System.DateTime> TimeSpan {
			get {
				return this._timeSpan;
			}
			set {
				if ((value != this._timeSpan)) {
					this.OnPropertyChanging("TimeSpan", this._timeSpan);
					this._timeSpan = value;
					this.OnPropertyChanged("TimeSpan");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="Occupied", Storage="_occupied", FieldType="Boolean")]
		public System.Nullable<bool> Occupied {
			get {
				return this._occupied;
			}
			set {
				if ((value != this._occupied)) {
					this.OnPropertyChanging("Occupied", this._occupied);
					this._occupied = value;
					this.OnPropertyChanged("Occupied");
				}
			}
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
		public override string Lokalizacja {
			get {
				throw new System.InvalidOperationException("Pole Location zostało usunięte z typu zawartości TimeSlot.");
			}
			set {
				throw new System.InvalidOperationException("Pole Location zostało usunięte z typu zawartości TimeSlot.");
			}
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
		public override string Description {
			get {
				throw new System.InvalidOperationException("Pole Comments zostało usunięte z typu zawartości TimeSlot.");
			}
			set {
				throw new System.InvalidOperationException("Pole Comments zostało usunięte z typu zawartości TimeSlot.");
			}
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
		public override System.Nullable<bool> WydarzenieCałodzienne {
			get {
				throw new System.InvalidOperationException("Pole fAllDayEvent zostało usunięte z typu zawartości TimeSlot.");
			}
			set {
				throw new System.InvalidOperationException("Pole fAllDayEvent zostało usunięte z typu zawartości TimeSlot.");
			}
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
		public override System.Nullable<bool> Cykl {
			get {
				throw new System.InvalidOperationException("Pole fRecurrence zostało usunięte z typu zawartości TimeSlot.");
			}
			set {
				throw new System.InvalidOperationException("Pole fRecurrence zostało usunięte z typu zawartości TimeSlot.");
			}
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
		public override System.Nullable<bool> ObszarRoboczy {
			get {
				throw new System.InvalidOperationException("Pole WorkspaceLink zostało usunięte z typu zawartości TimeSlot.");
			}
			set {
				throw new System.InvalidOperationException("Pole WorkspaceLink zostało usunięte z typu zawartości TimeSlot.");
			}
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		[Microsoft.SharePoint.Linq.RemovedColumnAttribute()]
		public override System.Nullable<Kategoria> Kategoria {
			get {
				throw new System.InvalidOperationException("Pole Category zostało usunięte z typu zawartości TimeSlot.");
			}
			set {
				throw new System.InvalidOperationException("Pole Category zostało usunięte z typu zawartości TimeSlot.");
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="ShippingIndex", Storage="_shippingIndex", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Shipping")]
		public ShippingOperationInbound ShippingIndex {
			get {
				return this._shippingIndex.GetEntity();
			}
			set {
				this._shippingIndex.SetEntity(value);
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="ShippingPointTitle", Storage="_shippingPoint", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Shipping Point")]
		public ShippingPoint ShippingPoint {
			get {
				return this._shippingPoint.GetEntity();
			}
			set {
				this._shippingPoint.SetEntity(value);
			}
		}
		
		private void OnShippingIndexChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("ShippingIndex", this._shippingIndex.Clone());
		}
		
		private void OnShippingIndexChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("ShippingIndex");
		}
		
		private void OnShippingIndexSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingOperationInbound> e) {
		}
		
		private void OnShippingPointChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("ShippingPoint", this._shippingPoint.Clone());
		}
		
		private void OnShippingPointChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("ShippingPoint");
		}
		
		private void OnShippingPointSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingPoint> e) {
		}
	}
	
	/// <summary>
	/// Shipping Operation - Outbound
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="ShippingOperationOutbound", Id="0x010047C1F2AB865840E598FE69DEC5D5B02100F3822278C9B04CA38278624C533B88DC")]
	public partial class ShippingOperationOutbound : ShippingOperationInbound {
		
		private string _securityEscortPO;
		
		private string _goodsHandlingPO;
		
		private System.Nullable<bool> _securityEscortRequired;
		
		private System.Nullable<System.DateTime> _estimateDeliveryTime;
		
		private System.Nullable<int> _securitySealProtocolIdentyfikator;
		
		private System.Nullable<int> _securityEscortIdentyfikator;
		
		private string _securityEscortTitle;
		
		private Microsoft.SharePoint.Linq.EntityRef<ShippingDriversTeam> _securityEscortTeam;
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public ShippingOperationOutbound() {
			this._securityEscortTeam = new Microsoft.SharePoint.Linq.EntityRef<ShippingDriversTeam>();
			this._securityEscortTeam.OnSync += new System.EventHandler<Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingDriversTeam>>(this.OnSecurityEscortTeamSync);
			this._securityEscortTeam.OnChanged += new System.EventHandler(this.OnSecurityEscortTeamChanged);
			this._securityEscortTeam.OnChanging += new System.EventHandler(this.OnSecurityEscortTeamChanging);
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="SecurityEscrotPO", Storage="_securityEscortPO", FieldType="Text")]
		public string SecurityEscortPO {
			get {
				return this._securityEscortPO;
			}
			set {
				if ((value != this._securityEscortPO)) {
					this.OnPropertyChanging("SecurityEscortPO", this._securityEscortPO);
					this._securityEscortPO = value;
					this.OnPropertyChanged("SecurityEscortPO");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="GoodsHandlingPO", Storage="_goodsHandlingPO", FieldType="Text")]
		public string GoodsHandlingPO {
			get {
				return this._goodsHandlingPO;
			}
			set {
				if ((value != this._goodsHandlingPO)) {
					this.OnPropertyChanging("GoodsHandlingPO", this._goodsHandlingPO);
					this._goodsHandlingPO = value;
					this.OnPropertyChanged("GoodsHandlingPO");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="SecuirtyEscortRequired", Storage="_securityEscortRequired", FieldType="Boolean")]
		public System.Nullable<bool> SecurityEscortRequired {
			get {
				return this._securityEscortRequired;
			}
			set {
				if ((value != this._securityEscortRequired)) {
					this.OnPropertyChanging("SecurityEscortRequired", this._securityEscortRequired);
					this._securityEscortRequired = value;
					this.OnPropertyChanged("SecurityEscortRequired");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EstimateDeliveryTime", Storage="_estimateDeliveryTime", FieldType="DateTime")]
		public System.Nullable<System.DateTime> EstimateDeliveryTime {
			get {
				return this._estimateDeliveryTime;
			}
			set {
				if ((value != this._estimateDeliveryTime)) {
					this.OnPropertyChanging("EstimateDeliveryTime", this._estimateDeliveryTime);
					this._estimateDeliveryTime = value;
					this.OnPropertyChanged("EstimateDeliveryTime");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="SecuritySealProtocolIndex", Storage="_securitySealProtocolIdentyfikator", FieldType="Lookup", IsLookupId=true)]
		public System.Nullable<int> SecuritySealProtocolIdentyfikator {
			get {
				return this._securitySealProtocolIdentyfikator;
			}
			set {
				if ((value != this._securitySealProtocolIdentyfikator)) {
					this.OnPropertyChanging("SecuritySealProtocolIdentyfikator", this._securitySealProtocolIdentyfikator);
					this._securitySealProtocolIdentyfikator = value;
					this.OnPropertyChanged("SecuritySealProtocolIdentyfikator");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="SecurityEscortCatalogTitle", Storage="_securityEscortIdentyfikator", FieldType="Lookup", IsLookupId=true)]
		public System.Nullable<int> SecurityEscortIdentyfikator {
			get {
				return this._securityEscortIdentyfikator;
			}
			set {
				if ((value != this._securityEscortIdentyfikator)) {
					this.OnPropertyChanging("SecurityEscortIdentyfikator", this._securityEscortIdentyfikator);
					this._securityEscortIdentyfikator = value;
					this.OnPropertyChanged("SecurityEscortIdentyfikator");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="SecurityEscortCatalogTitle", Storage="_securityEscortTitle", ReadOnly=true, FieldType="Lookup", IsLookupValue=true)]
		public string SecurityEscortTitle {
			get {
				return this._securityEscortTitle;
			}
			set {
				if ((value != this._securityEscortTitle)) {
					this.OnPropertyChanging("SecurityEscortTitle", this._securityEscortTitle);
					this._securityEscortTitle = value;
					this.OnPropertyChanged("SecurityEscortTitle");
				}
			}
		}
		
		[Microsoft.SharePoint.Linq.AssociationAttribute(Name="ShippingSecurityEscortTeamTitle", Storage="_securityEscortTeam", MultivalueType=Microsoft.SharePoint.Linq.AssociationType.Single, List="Drivers Team")]
		public ShippingDriversTeam SecurityEscortTeam {
			get {
				return this._securityEscortTeam.GetEntity();
			}
			set {
				this._securityEscortTeam.SetEntity(value);
			}
		}
		
		private void OnSecurityEscortTeamChanging(object sender, System.EventArgs e) {
			this.OnPropertyChanging("SecurityEscortTeam", this._securityEscortTeam.Clone());
		}
		
		private void OnSecurityEscortTeamChanged(object sender, System.EventArgs e) {
			this.OnPropertyChanged("SecurityEscortTeam");
		}
		
		private void OnSecurityEscortTeamSync(object sender, Microsoft.SharePoint.Linq.AssociationChangedEventArgs<ShippingDriversTeam> e) {
			if ((Microsoft.SharePoint.Linq.AssociationChangedState.Added == e.State)) {
				e.Item.ShippingOperationOutbound.Add(this);
			}
			else {
				e.Item.ShippingOperationOutbound.Remove(this);
			}
		}
	}
	
	/// <summary>
	/// Time Slot
	/// </summary>
	[Microsoft.SharePoint.Linq.ContentTypeAttribute(Name="TimeSlot", Id="0x0102008B8977AFA9104B18B4B25D7C06A4A3AA", List="TimeSlot")]
	public partial class TimeSlotTimeSlot : TimeSlot {
		
		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate();
		partial void OnCreated();
		#endregion
		
		public TimeSlotTimeSlot() {
			this.OnCreated();
		}
		
		[Microsoft.SharePoint.Linq.ColumnAttribute(Name="EventDate", Storage="_startTime", Required=true, FieldType="DateTime")]
		public override System.Nullable<System.DateTime> StartTime {
			get {
				return this._startTime;
			}
			set {
				if ((value != this._startTime)) {
					this.OnPropertyChanging("StartTime", this._startTime);
					this._startTime = value;
					this.OnPropertyChanged("StartTime");
				}
			}
		}
	}
	
	public enum Kategoria : int {
		
		None = 0,
		
		Invalid = 1,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(1) Category1")]
		_1Category1 = 2,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(2) Category2")]
		_2Category2 = 4,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="(3) Category3")]
		_3Category3 = 8,
	}
	
	public enum ServiceType : int {
		
		None = 0,
		
		Invalid = 1,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Vendor")]
		Vendor = 2,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Forwarder")]
		Forwarder = 4,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Security Escort Provider")]
		SecurityEscortProvider = 8,
	}
	
	public enum State : int {
		
		None = 0,
		
		Invalid = 1,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Canceled")]
		Canceled = 2,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Completed")]
		Completed = 4,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Confirmed")]
		Confirmed = 8,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Creation")]
		Creation = 16,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Delayed")]
		Delayed = 32,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Scheduled")]
		Scheduled = 64,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Underway")]
		Underway = 128,
	}
	
	public enum Direction : int {
		
		None = 0,
		
		Invalid = 1,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Inbound")]
		Inbound = 2,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Outbound")]
		Outbound = 4,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Both directions")]
		BothDirections = 8,
	}
	
	public enum VehicleType : int {
		
		None = 0,
		
		Invalid = 1,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Truck")]
		Truck = 2,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Van")]
		Van = 4,
		
		[Microsoft.SharePoint.Linq.ChoiceAttribute(Value="Security Escort Car")]
		SecurityEscortCar = 8,
	}
}
