//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace CAS.SmartFactory.xml.DocumentsFactory.BalanceSheet {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/BalanceSheetContent.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/BalanceSheetContent.xsd", IsNullable=false)]
    public partial class BalanceSheetContent {
        
        private System.DateTime documentDateField;
        
        private string documentNoField;
        
        private System.DateTime situationAtDateField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private BalanceBatchContent[] balanceBatchField;
        
        private JSOContent jSOXField;
        
        private BalanceCutfillerContent[] balanceCutfillerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DocumentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentNo {
            get {
                return this.documentNoField;
            }
            set {
                this.documentNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SituationAtDate {
            get {
                return this.situationAtDateField;
            }
            set {
                this.situationAtDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BalanceBatchContent[] BalanceBatch {
            get {
                return this.balanceBatchField;
            }
            set {
                this.balanceBatchField = value;
            }
        }
        
        /// <remarks/>
        public JSOContent JSOX {
            get {
                return this.jSOXField;
            }
            set {
                this.jSOXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BalanceCutfillerContent[] BalanceCutfiller {
            get {
                return this.balanceCutfillerField;
            }
            set {
                this.balanceCutfillerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/BalanceSheetContent.xsd")]
    public partial class BalanceBatchContent {
        
        private BalanceIPRContent[] balanceIPRField;
        
        private decimal totalIPRBookField;
        
        private decimal totalTobaccoStartedField;
        
        private decimal totalSHWasteOveruseCSNotStartedField;
        
        private decimal totalDustCSNotStartedField;
        
        private decimal totalTobaccoAvailableField;
        
        private decimal totalTobaccoInWarehouseField;
        
        private decimal totalTobaccoInCigarettesWarehouseField;
        
        private decimal totalTobaccoInCigarettesProductionField;
        
        private decimal totalTobaccoInCutfillerWarehouseField;
        
        private decimal totalBalanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BalanceIPRContent[] BalanceIPR {
            get {
                return this.balanceIPRField;
            }
            set {
                this.balanceIPRField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalIPRBook {
            get {
                return this.totalIPRBookField;
            }
            set {
                this.totalIPRBookField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalTobaccoStarted {
            get {
                return this.totalTobaccoStartedField;
            }
            set {
                this.totalTobaccoStartedField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalSHWasteOveruseCSNotStarted {
            get {
                return this.totalSHWasteOveruseCSNotStartedField;
            }
            set {
                this.totalSHWasteOveruseCSNotStartedField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalDustCSNotStarted {
            get {
                return this.totalDustCSNotStartedField;
            }
            set {
                this.totalDustCSNotStartedField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalTobaccoAvailable {
            get {
                return this.totalTobaccoAvailableField;
            }
            set {
                this.totalTobaccoAvailableField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalTobaccoInWarehouse {
            get {
                return this.totalTobaccoInWarehouseField;
            }
            set {
                this.totalTobaccoInWarehouseField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalTobaccoInCigarettesWarehouse {
            get {
                return this.totalTobaccoInCigarettesWarehouseField;
            }
            set {
                this.totalTobaccoInCigarettesWarehouseField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalTobaccoInCigarettesProduction {
            get {
                return this.totalTobaccoInCigarettesProductionField;
            }
            set {
                this.totalTobaccoInCigarettesProductionField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalTobaccoInCutfillerWarehouse {
            get {
                return this.totalTobaccoInCutfillerWarehouseField;
            }
            set {
                this.totalTobaccoInCutfillerWarehouseField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalBalance {
            get {
                return this.totalBalanceField;
            }
            set {
                this.totalBalanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/BalanceSheetContent.xsd")]
    public partial class BalanceIPRContent {
        
        private string entryDocumentNoField;
        
        private string sKUField;
        
        private string batchField;
        
        private decimal iPRBookField;
        
        private decimal tobaccoStartedField;
        
        private decimal sHWasteOveruseCSNotStartedField;
        
        private decimal dustCSNotStartedField;
        
        private decimal tobaccoAvailableField;
        
        /// <remarks/>
        public string EntryDocumentNo {
            get {
                return this.entryDocumentNoField;
            }
            set {
                this.entryDocumentNoField = value;
            }
        }
        
        /// <remarks/>
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
        
        /// <remarks/>
        public string Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
            }
        }
        
        /// <remarks/>
        public decimal IPRBook {
            get {
                return this.iPRBookField;
            }
            set {
                this.iPRBookField = value;
            }
        }
        
        /// <remarks/>
        public decimal TobaccoStarted {
            get {
                return this.tobaccoStartedField;
            }
            set {
                this.tobaccoStartedField = value;
            }
        }
        
        /// <remarks/>
        public decimal SHWasteOveruseCSNotStarted {
            get {
                return this.sHWasteOveruseCSNotStartedField;
            }
            set {
                this.sHWasteOveruseCSNotStartedField = value;
            }
        }
        
        /// <remarks/>
        public decimal DustCSNotStarted {
            get {
                return this.dustCSNotStartedField;
            }
            set {
                this.dustCSNotStartedField = value;
            }
        }
        
        /// <remarks/>
        public decimal TobaccoAvailable {
            get {
                return this.tobaccoAvailableField;
            }
            set {
                this.tobaccoAvailableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/BalanceSheetContent.xsd")]
    public partial class BalanceCutfillerContent {
        
        private string ctfBatchField;
        
        private string ctfSKUField;
        
        private decimal ctfBatchQuantityField;
        
        private decimal ctfOnStockField;
        
        private string tobaccoBatchField;
        
        private string tobaccoSKUField;
        
        private decimal tobaccoBatchQuantityField;
        
        private decimal tobaccoKgField;
        
        /// <remarks/>
        public string CtfBatch {
            get {
                return this.ctfBatchField;
            }
            set {
                this.ctfBatchField = value;
            }
        }
        
        /// <remarks/>
        public string CtfSKU {
            get {
                return this.ctfSKUField;
            }
            set {
                this.ctfSKUField = value;
            }
        }
        
        /// <remarks/>
        public decimal CtfBatchQuantity {
            get {
                return this.ctfBatchQuantityField;
            }
            set {
                this.ctfBatchQuantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal CtfOnStock {
            get {
                return this.ctfOnStockField;
            }
            set {
                this.ctfOnStockField = value;
            }
        }
        
        /// <remarks/>
        public string TobaccoBatch {
            get {
                return this.tobaccoBatchField;
            }
            set {
                this.tobaccoBatchField = value;
            }
        }
        
        /// <remarks/>
        public string TobaccoSKU {
            get {
                return this.tobaccoSKUField;
            }
            set {
                this.tobaccoSKUField = value;
            }
        }
        
        /// <remarks/>
        public decimal TobaccoBatchQuantity {
            get {
                return this.tobaccoBatchQuantityField;
            }
            set {
                this.tobaccoBatchQuantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal TobaccoKg {
            get {
                return this.tobaccoKgField;
            }
            set {
                this.tobaccoKgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/BalanceSheetContent.xsd")]
    public partial class JSOXCustomsSummaryContent {
        
        private string exportOrFreeCirculationSADField;
        
        private string entryDocumentNoField;
        
        private System.DateTime sADDateField;
        
        private string invoiceNoField;
        
        private string compensationGoodField;
        
        private string procedureField;
        
        private decimal quantityField;
        
        private decimal balanceField;
        
        private string sadConsignmentNoField;
        
        /// <remarks/>
        public string ExportOrFreeCirculationSAD {
            get {
                return this.exportOrFreeCirculationSADField;
            }
            set {
                this.exportOrFreeCirculationSADField = value;
            }
        }
        
        /// <remarks/>
        public string EntryDocumentNo {
            get {
                return this.entryDocumentNoField;
            }
            set {
                this.entryDocumentNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SADDate {
            get {
                return this.sADDateField;
            }
            set {
                this.sADDateField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public string CompensationGood {
            get {
                return this.compensationGoodField;
            }
            set {
                this.compensationGoodField = value;
            }
        }
        
        /// <remarks/>
        public string Procedure {
            get {
                return this.procedureField;
            }
            set {
                this.procedureField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public string SadConsignmentNo {
            get {
                return this.sadConsignmentNoField;
            }
            set {
                this.sadConsignmentNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/BalanceSheetContent.xsd")]
    public partial class JSOXCustomsSummaryContentOGLGroup {
        
        private JSOXCustomsSummaryContent[] jSOXCustomsSummaryArrayField;
        
        private decimal subtotalQuantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("JSOXCustomsSummary", IsNullable=false)]
        public JSOXCustomsSummaryContent[] JSOXCustomsSummaryArray {
            get {
                return this.jSOXCustomsSummaryArrayField;
            }
            set {
                this.jSOXCustomsSummaryArrayField = value;
            }
        }
        
        /// <remarks/>
        public decimal SubtotalQuantity {
            get {
                return this.subtotalQuantityField;
            }
            set {
                this.subtotalQuantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/BalanceSheetContent.xsd")]
    public partial class JSOXCustomsSummaryContentList {
        
        private JSOXCustomsSummaryContentOGLGroup[] jSOXCustomsSummaryOGLGroupArrayField;
        
        private decimal subtotalQuantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("JSOXCustomsSummaryOGLGroup", IsNullable=false)]
        public JSOXCustomsSummaryContentOGLGroup[] JSOXCustomsSummaryOGLGroupArray {
            get {
                return this.jSOXCustomsSummaryOGLGroupArrayField;
            }
            set {
                this.jSOXCustomsSummaryOGLGroupArrayField = value;
            }
        }
        
        /// <remarks/>
        public decimal SubtotalQuantity {
            get {
                return this.subtotalQuantityField;
            }
            set {
                this.subtotalQuantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SmartFactory/xml/DocumentsFactory/BalanceSheetContent.xsd")]
    public partial class JSOContent {
        
        private JSOXCustomsSummaryContentList jSOXCustomsSummaryListField;
        
        private System.DateTime previousMonthDateField;
        
        private decimal previousMonthQuantityField;
        
        private System.DateTime introducingDateStartField;
        
        private System.DateTime introducingDateEndField;
        
        private decimal introducingQuantityField;
        
        private System.DateTime outboundDateStartField;
        
        private System.DateTime outboundDateEndField;
        
        private decimal outboundQuantityField;
        
        private System.DateTime balanceDateField;
        
        private decimal balanceQuantityField;
        
        private System.DateTime situationDateField;
        
        private decimal situationQuantityField;
        
        private decimal reassumeQuantityField;
        
        /// <remarks/>
        public JSOXCustomsSummaryContentList JSOXCustomsSummaryList {
            get {
                return this.jSOXCustomsSummaryListField;
            }
            set {
                this.jSOXCustomsSummaryListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PreviousMonthDate {
            get {
                return this.previousMonthDateField;
            }
            set {
                this.previousMonthDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal PreviousMonthQuantity {
            get {
                return this.previousMonthQuantityField;
            }
            set {
                this.previousMonthQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime IntroducingDateStart {
            get {
                return this.introducingDateStartField;
            }
            set {
                this.introducingDateStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime IntroducingDateEnd {
            get {
                return this.introducingDateEndField;
            }
            set {
                this.introducingDateEndField = value;
            }
        }
        
        /// <remarks/>
        public decimal IntroducingQuantity {
            get {
                return this.introducingQuantityField;
            }
            set {
                this.introducingQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime OutboundDateStart {
            get {
                return this.outboundDateStartField;
            }
            set {
                this.outboundDateStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime OutboundDateEnd {
            get {
                return this.outboundDateEndField;
            }
            set {
                this.outboundDateEndField = value;
            }
        }
        
        /// <remarks/>
        public decimal OutboundQuantity {
            get {
                return this.outboundQuantityField;
            }
            set {
                this.outboundQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BalanceDate {
            get {
                return this.balanceDateField;
            }
            set {
                this.balanceDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal BalanceQuantity {
            get {
                return this.balanceQuantityField;
            }
            set {
                this.balanceQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SituationDate {
            get {
                return this.situationDateField;
            }
            set {
                this.situationDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal SituationQuantity {
            get {
                return this.situationQuantityField;
            }
            set {
                this.situationQuantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal ReassumeQuantity {
            get {
                return this.reassumeQuantityField;
            }
            set {
                this.reassumeQuantityField = value;
            }
        }
    }
}
