//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace CAS.SmartFactory.CW.Interoperability.DocumentsFactory.CheckList {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/CheckList" +
        ".xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/CheckList" +
        ".xsd", IsNullable=false)]
    public partial class CheckList {
        
        private ArrayOfContentsContentArray[] checkListContentArayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ContentArray", IsNullable=false)]
        public ArrayOfContentsContentArray[] CheckListContentAray {
            get {
                return this.checkListContentArayField;
            }
            set {
                this.checkListContentArayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/CheckList" +
        ".xsd")]
    public partial class ArrayOfContentsContentArray {
        
        private string oGLNumberField;
        
        private System.DateTime oGLDateField;
        
        private double packageToClearField;
        
        /// <remarks/>
        public string OGLNumber {
            get {
                return this.oGLNumberField;
            }
            set {
                this.oGLNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime OGLDate {
            get {
                return this.oGLDateField;
            }
            set {
                this.oGLDateField = value;
            }
        }
        
        /// <remarks/>
        public double PackageToClear {
            get {
                return this.packageToClearField;
            }
            set {
                this.packageToClearField = value;
            }
        }
    }
}
