//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.5448
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CAS.SmartFactory.xml.erp {
    using System.Xml.Serialization;
    
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/jti/ipr/Batch.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cas.eu/schemas/jti/ipr/Batch.xsd", IsNullable=false)]
    public partial class Batch {
        
        private BatchMaterial[] materialField;
        
        private BatchStatus statusField;
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("Material")]
        public BatchMaterial[] Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
        
        /// <uwagi/>
        public BatchStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/jti/ipr/Batch.xsd")]
    public partial class BatchMaterial {
        
        private string material_descriptionField;
        
        private string materialField;
        
        private string batchField;
        
        private string material_groupField;
        
        private string stor__LocField;
        
        private decimal quantityField;
        
        private string mvmt_TypeField;
        
        private string mB_TCODEField;
        
        private decimal quantity_calculatedField;
        
        private decimal quantity_calculated_without_scrapping_peField;
        
        private string unitField;
        
        /// <uwagi/>
        public string Material_description {
            get {
                return this.material_descriptionField;
            }
            set {
                this.material_descriptionField = value;
            }
        }
        
        /// <uwagi/>
        public string Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
        
        /// <uwagi/>
        public string Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
            }
        }
        
        /// <uwagi/>
        public string material_group {
            get {
                return this.material_groupField;
            }
            set {
                this.material_groupField = value;
            }
        }
        
        /// <uwagi/>
        public string Stor__Loc {
            get {
                return this.stor__LocField;
            }
            set {
                this.stor__LocField = value;
            }
        }
        
        /// <uwagi/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <uwagi/>
        public string Mvmt_Type {
            get {
                return this.mvmt_TypeField;
            }
            set {
                this.mvmt_TypeField = value;
            }
        }
        
        /// <uwagi/>
        public string MB_TCODE {
            get {
                return this.mB_TCODEField;
            }
            set {
                this.mB_TCODEField = value;
            }
        }
        
        /// <uwagi/>
        public decimal Quantity_calculated {
            get {
                return this.quantity_calculatedField;
            }
            set {
                this.quantity_calculatedField = value;
            }
        }
        
        /// <uwagi/>
        public decimal Quantity_calculated_without_scrapping_pe {
            get {
                return this.quantity_calculated_without_scrapping_peField;
            }
            set {
                this.quantity_calculated_without_scrapping_peField = value;
            }
        }
        
        /// <uwagi/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/jti/ipr/Batch.xsd")]
    public enum BatchStatus {
        
        /// <uwagi/>
        Final,
        
        /// <uwagi/>
        Intermediate,
        
        /// <uwagi/>
        Progress,
    }
}
