CREATE TABLE [dbo].[BalanceIPR] (
    [Archival]                       BIT            NULL,
    [Author]                         NVARCHAR (MAX) NULL,
    [Balance]                        FLOAT (53)     NULL,
    [BalanceBatchIndex]              INT            NULL,
    [BalanceIPR2JSOXIndex]           INT            NULL,
    [Batch]                          NVARCHAR (MAX) NULL,
    [Created]                        DATETIME       NULL,
    [CustomsProcedure]               NVARCHAR (MAX) NULL,
    [DocumentNo]                     NVARCHAR (MAX) NULL,
    [DustCSNotStarted]               FLOAT (53)     NULL,
    [DustCSStarted]                  FLOAT (53)     NULL,
    [Editor]                         NVARCHAR (MAX) NULL,
    [ID]                             INT            NOT NULL,
    [InvoiceNo]                      NVARCHAR (MAX) NULL,
    [IPRBook]                        FLOAT (53)     NULL,
    [IPRIndex]                       INT            NULL,
    [Modified]                       DATETIME       NULL,
    [OGLIntroduction]                NVARCHAR (MAX) NULL,
    [OveruseCSNotStarted]            FLOAT (53)     NULL,
    [OveruseCSStarted]               FLOAT (53)     NULL,
    [PureTobaccoCSNotStarted]        FLOAT (53)     NULL,
    [PureTobaccoCSStarted]           FLOAT (53)     NULL,
    [SHMentholCSNotStarted]          FLOAT (53)     NULL,
    [SHMentholCSStarted]             FLOAT (53)     NULL,
    [SHWasteOveruseCSNotStarted]     FLOAT (53)     NULL,
    [SKU]                            NVARCHAR (MAX) NULL,
    [Title]                          NVARCHAR (MAX) NOT NULL,
    [TobaccoAvailable]               FLOAT (53)     NULL,
    [TobaccoCSFinished]              FLOAT (53)     NULL,
    [TobaccoEnteredIntoIPR]          FLOAT (53)     NULL,
    [TobaccoInFGCSNotStarted]        FLOAT (53)     NULL,
    [TobaccoInFGCSStarted]           FLOAT (53)     NULL,
    [TobaccoStarted]                 FLOAT (53)     NULL,
    [TobaccoToBeUsedInTheProduction] FLOAT (53)     NULL,
    [TobaccoUsedInTheProduction]     FLOAT (53)     NULL,
    [Version]                        INT            NULL,
    [WasteCSNotStarted]              FLOAT (53)     NULL,
    [WasteCSStarted]                 FLOAT (53)     NULL,
	[OnlySQL]						 BIT			NOT NULL,
	[UIVersionString]		         NVARCHAR(max)	NULL,
    CONSTRAINT [PK_BalanceIPR_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_BalanceIPR_BalanceBatch] FOREIGN KEY ([BalanceBatchIndex]) REFERENCES [dbo].[BalanceBatch] ([ID]),
    CONSTRAINT [FK_BalanceIPR_IPR] FOREIGN KEY ([IPRIndex]) REFERENCES [dbo].[IPR] ([ID]),
    CONSTRAINT [FK_BalanceIPR_JSOXLibrary] FOREIGN KEY ([BalanceIPR2JSOXIndex]) REFERENCES [dbo].[JSOXLibrary] ([ID])
);

