CREATE TABLE [dbo].[BalanceIPR] (
    [Archival]               BIT             NULL,
    [Balance]                FLOAT           NULL,
    [BalanceBatchIndex]      INT             NULL,
    [BalanceIPR2JSOXIndex]   INT             NULL,
    [Batch]                  NVARCHAR(255)   NULL,
    [Created]                DATETIME        NULL,
    [CreatedBy]              NVARCHAR(255)   NULL,
    [CustomsProcedure]       NVARCHAR(255)   NULL,
    [DocumentNo]             NVARCHAR(255)   NULL,
    [DustCSNotStarted]       FLOAT           NULL,
    [DustCSStarted]          FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [InvoiceNo]              NVARCHAR(255)   NULL,
    [IPRBook]                FLOAT           NULL,
    [IPRIndex]               INT             NULL,
    [Modified]               DATETIME        NULL,
    [ModifiedBy]             NVARCHAR(255)   NULL,
    [OGLIntroduction]        NVARCHAR(255)   NULL,
    [OveruseCSNotStarted]    FLOAT           NULL,
    [OveruseCSStarted]       FLOAT           NULL,
    [owshiddenversion]       INT             NULL,
    [PureTobaccoCSNotStarted] FLOAT           NULL,
    [PureTobaccoCSStarted]   FLOAT           NULL,
    [SHMentholCSNotStarted]  FLOAT           NULL,
    [SHMentholCSStarted]     FLOAT           NULL,
    [SHWasteOveruseCSNotStarted] FLOAT           NULL,
    [SKU]                    NVARCHAR(255)   NULL,
    [Title]                  NVARCHAR(255)   NOT NULL,
    [TobaccoAvailable]       FLOAT           NULL,
    [TobaccoCSFinished]      FLOAT           NULL,
    [TobaccoEnteredIntoIPR]  FLOAT           NULL,
    [TobaccoInFGCSNotStarted] FLOAT           NULL,
    [TobaccoInFGCSStarted]   FLOAT           NULL,
    [TobaccoStarted]         FLOAT           NULL,
    [TobaccoToBeUsedInTheProduction] FLOAT           NULL,
    [TobaccoUsedInTheProduction] FLOAT           NULL,
    [WasteCSNotStarted]      FLOAT           NULL,
    [WasteCSStarted]         FLOAT           NULL,
    CONSTRAINT [PK_BalanceIPR_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_BalanceIPR_BalanceBatch] FOREIGN KEY ([BalanceBatchIndex]) REFERENCES [dbo].[BalanceBatch] ([ID]),
    CONSTRAINT [FK_BalanceIPR_IPR] FOREIGN KEY ([IPRIndex]) REFERENCES [dbo].[IPR] ([ID]),
    CONSTRAINT [FK_BalanceIPR_JSOXLibrary] FOREIGN KEY ([BalanceIPR2JSOXIndex]) REFERENCES [dbo].[JSOXLibrary] ([ID])
);

