CREATE TABLE [dbo].[Batch] (
    [Archival]                 BIT            NULL,
    [Author]                   NVARCHAR (MAX) NULL,
    [Batch]                    NVARCHAR (MAX) NULL,
    [BatchDustCooeficiency]    FLOAT (53)     NULL,
    [BatchLibraryIndex]        INT            NULL,
    [BatchSHCooeficiency]      FLOAT (53)     NULL,
    [BatchStatus]              NVARCHAR (MAX) NULL,
    [BatchWasteCooeficiency]   FLOAT (53)     NULL,
    [CalculatedOveruse]        FLOAT (53)     NULL,
    [CFTProductivityNormMax]   FLOAT (53)     NULL,
    [CFTProductivityNormMin]   FLOAT (53)     NULL,
    [CFTProductivityRateMax]   FLOAT (53)     NULL,
    [CFTProductivityRateMin]   FLOAT (53)     NULL,
    [CFTProductivityVersion]   FLOAT (53)     NULL,
    [Created]                  DATETIME       NULL,
    [CTFUsageMax]              FLOAT (53)     NULL,
    [CTFUsageMin]              FLOAT (53)     NULL,
    [Dust]                     FLOAT (53)     NULL,
    [DustCooeficiencyVersion]  FLOAT (53)     NULL,
    [Editor]                   NVARCHAR (MAX) NULL,
    [FGQuantity]               FLOAT (53)     NULL,
    [FGQuantityAvailable]      FLOAT (53)     NULL,
    [FGQuantityBlocked]        FLOAT (53)     NULL,
    [FGQuantityPrevious]       FLOAT (53)     NULL,
    [ID]                       INT            NOT NULL,
    [MaterialQuantity]         FLOAT (53)     NULL,
    [MaterialQuantityPrevious] FLOAT (53)     NULL,
    [Modified]                 DATETIME       NULL,
    [Overuse]                  FLOAT (53)     NULL,
    [ProductType]              NVARCHAR (MAX) NULL,
    [SHCooeficiencyVersion]    FLOAT (53)     NULL,
    [SHMenthol]                FLOAT (53)     NULL,
    [SKU]                      NVARCHAR (MAX) NULL,
    [SKUIndex]                 INT            NULL,
    [Title]                    NVARCHAR (MAX) NOT NULL,
    [Tobacco]                  FLOAT (53)     NULL,
    [UsageMax]                 FLOAT (53)     NULL,
    [UsageMin]                 FLOAT (53)     NULL,
    [UsageVersion]             FLOAT (53)     NULL,
    [Version]                  INT            NULL,
    [Waste]                    FLOAT (53)     NULL,
    [WasteCooeficiencyVersion] FLOAT (53)     NULL,
	[OnlySQL]				   BIT			  NOT NULL,
	[UIVersionString]		   NVARCHAR(max)  NULL,
    CONSTRAINT [PK_Batch_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Batch_BatchLibrary] FOREIGN KEY ([BatchLibraryIndex]) REFERENCES [dbo].[BatchLibrary] ([ID]),
    CONSTRAINT [FK_Batch_SKU] FOREIGN KEY ([SKUIndex]) REFERENCES [dbo].[SKU] ([ID])
);

