CREATE TABLE [dbo].[Batch] (
    [Batch]                    NVARCHAR (255) NOT NULL,
    [BatchDustCooeficiency]    FLOAT (53)     NOT NULL,
    [BatchLibraryIndex]        INT            NOT NULL,
    [BatchSHCooeficiency]      FLOAT (53)     NOT NULL,
    [BatchStatus]              NVARCHAR (255) NOT NULL,
    [BatchWasteCooeficiency]   FLOAT (53)     NOT NULL,
    [CalculatedOveruse]        FLOAT (53)     NOT NULL,
    [CFTProductivityNormMax]   NVARCHAR (255) NOT NULL,
    [CFTProductivityNormMin]   NVARCHAR (255) NOT NULL,
    [CFTProductivityRateMax]   FLOAT (53)     NOT NULL,
    [CFTProductivityRateMin]   FLOAT (53)     NOT NULL,
    [CFTProductivityVersion]   FLOAT (53)     NOT NULL,
    [Created]                  DATETIME       NOT NULL,
    [CreatedBy]                NVARCHAR (255) NOT NULL,
    [CTFUsageMax]              FLOAT (53)     NOT NULL,
    [CTFUsageMin]              FLOAT (53)     NOT NULL,
    [Dust]                     FLOAT (53)     NOT NULL,
    [DustCooeficiencyVersion]  FLOAT (53)     NOT NULL,
    [FGQuantity]               FLOAT (53)     NOT NULL,
    [FGQuantityAvailable]      FLOAT (53)     NOT NULL,
    [FGQuantityBlocked]        FLOAT (53)     NOT NULL,
    [FGQuantityPrevious]       FLOAT (53)     NOT NULL,
    [ID]                       INT            NOT NULL,
    [MaterialQuantity]         FLOAT (53)     NOT NULL,
    [MaterialQuantityPrevious] FLOAT (53)     NOT NULL,
    [Modified]                 DATETIME       NOT NULL,
    [ModifiedBy]               NVARCHAR (255) NOT NULL,
    [Overuse]                  FLOAT (53)     NOT NULL,
    [ProductType]              NVARCHAR (255) NOT NULL,
    [SHCooeficiencyVersion]    FLOAT (53)     NOT NULL,
    [SHMenthol]                FLOAT (53)     NOT NULL,
    [SKU]                      NVARCHAR (255) NOT NULL,
    [SKUIndex]                 INT            NOT NULL,
    [Title]                    NVARCHAR (255) NOT NULL,
    [Tobacco]                  FLOAT (53)     NOT NULL,
    [UsageMax]                 FLOAT (53)     NOT NULL,
    [UsageMin]                 FLOAT (53)     NOT NULL,
    [UsageVersion]             FLOAT (53)     NOT NULL,
    [Waste]                    FLOAT (53)     NOT NULL,
    [WasteCooeficiencyVersion] FLOAT (53)     NOT NULL,
    CONSTRAINT [PK_Batch_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Batch_BatchLibrary] FOREIGN KEY ([BatchLibraryIndex]) REFERENCES [dbo].[BatchLibrary] ([ID]),
    CONSTRAINT [FK_Batch_SKU] FOREIGN KEY ([SKUIndex]) REFERENCES [dbo].[SKU] ([ID])
);

