CREATE TABLE [dbo].[Disposal] (
    [Archival]               BIT             NULL,
    [ClearingType]           NVARCHAR(255)   NULL,
    [Created]                DATETIME        NULL,
    [CreatedBy]              NVARCHAR(255)   NULL,
    [CustomsProcedure]       NVARCHAR(255)   NULL,
    [CustomsStatus]          NVARCHAR(255)   NULL,
    [Disposal2BatchIndex]    INT             NULL,
    [Disposal2ClearenceIndex] INT             NULL,
    [Disposal2InvoiceContentIndex] INT             NULL,
    [Disposal2IPRIndex]      INT             NULL,
    [Disposal2MaterialIndex] INT             NULL,
    [Disposal2PCNID]         INT             NULL,
    [DisposalStatus]         NVARCHAR(255)   NULL,
    [DutyAndVAT]             FLOAT           NULL,
    [DutyPerSettledAmount]   FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [InvoiceNo]              NVARCHAR(255)   NULL,
    [IPRDocumentNo]          NVARCHAR(255)   NULL,
    [JSOXCustomsSummaryIndex] INT             NULL,
    [JSOXReportID]           FLOAT           NULL,
    [Modified]               DATETIME        NULL,
    [ModifiedBy]             NVARCHAR(255)   NULL,
    [owshiddenversion]       INT             NULL,
    [RemainingQuantity]      FLOAT           NULL,
    [SadConsignmentNo]       NVARCHAR(255)   NULL,
    [SADDate]                DATETIME        NULL,
    [SADDocumentNo]          NVARCHAR(255)   NULL,
    [SettledQuantity]        FLOAT           NULL,
    [SPNo]                   FLOAT           NULL,
    [Title]                  NVARCHAR(255)   NOT NULL,
    [TobaccoValue]           FLOAT           NULL,
    [VATPerSettledAmount]    FLOAT           NULL,
    CONSTRAINT [PK_Disposal_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Disposal_Batch] FOREIGN KEY ([Disposal2BatchIndex]) REFERENCES [dbo].[Batch] ([ID]),
    CONSTRAINT [FK_Disposal_Clearence] FOREIGN KEY ([Disposal2ClearenceIndex]) REFERENCES [dbo].[Clearence] ([ID]),
    CONSTRAINT [FK_Disposal_InvoiceContent] FOREIGN KEY ([Disposal2InvoiceContentIndex]) REFERENCES [dbo].[InvoiceContent] ([ID]),
    CONSTRAINT [FK_Disposal_IPR] FOREIGN KEY ([Disposal2IPRIndex]) REFERENCES [dbo].[IPR] ([ID]),
    CONSTRAINT [FK_Disposal_JSOXCustomsSummary] FOREIGN KEY ([JSOXCustomsSummaryIndex]) REFERENCES [dbo].[JSOXCustomsSummary] ([ID]),
    CONSTRAINT [FK_Disposal_Material] FOREIGN KEY ([Disposal2MaterialIndex]) REFERENCES [dbo].[Material] ([ID]),
    CONSTRAINT [FK_Disposal_PCNCode] FOREIGN KEY ([Disposal2PCNID]) REFERENCES [dbo].[PCNCode] ([ID])
);

