CREATE TABLE [dbo].[Disposal] (
    [ClearingType]                 NVARCHAR (255) NOT NULL,
    [Created]                      DATETIME       NOT NULL,
    [CreatedBy]                    NVARCHAR (255) NOT NULL,
    [CustomsProcedure]             NVARCHAR (255) NOT NULL,
    [CustomsStatus]                NVARCHAR (255) NOT NULL,
    [Disposal2BatchIndex]          INT            NOT NULL,
    [Disposal2ClearenceIndex]      INT            NOT NULL,
    [Disposal2InvoiceContentIndex] INT            NOT NULL,
    [Disposal2IPRIndex]            INT            NOT NULL,
    [Disposal2MaterialIndex]       INT            NOT NULL,
    [Disposal2PCNID]               INT            NOT NULL,
    [DisposalStatus]               NVARCHAR (255) NOT NULL,
    [DutyAndVAT]                   FLOAT (53)     NOT NULL,
    [DutyPerSettledAmount]         FLOAT (53)     NOT NULL,
    [ID]                           INT            NOT NULL,
    [InvoiceNo]                    NVARCHAR (255) NOT NULL,
    [IPRDocumentNo]                NVARCHAR (255) NOT NULL,
    [JSOXCustomsSummaryIndex]      INT            NOT NULL,
    [JSOXReportID]                 FLOAT (53)     NOT NULL,
    [Modified]                     DATETIME       NOT NULL,
    [ModifiedBy]                   NVARCHAR (255) NOT NULL,
    [RemainingQuantity]            FLOAT (53)     NOT NULL,
    [SadConsignmentNo]             NVARCHAR (255) NOT NULL,
    [SADDate]                      DATETIME       NOT NULL,
    [SADDocumentNo]                NVARCHAR (255) NOT NULL,
    [SettledQuantity]              FLOAT (53)     NOT NULL,
    [SPNo]                         FLOAT (53)     NOT NULL,
    [Title]                        NVARCHAR (255) NOT NULL,
    [TobaccoValue]                 FLOAT (53)     NOT NULL,
    [VATPerSettledAmount]          FLOAT (53)     NOT NULL,
    CONSTRAINT [PK_Disposal_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Disposal_Batch] FOREIGN KEY ([Disposal2BatchIndex]) REFERENCES [dbo].[Batch] ([ID]),
    CONSTRAINT [FK_Disposal_Clearence] FOREIGN KEY ([Disposal2ClearenceIndex]) REFERENCES [dbo].[Clearence] ([ID]),
    CONSTRAINT [FK_Disposal_InvoiceContent] FOREIGN KEY ([Disposal2InvoiceContentIndex]) REFERENCES [dbo].[InvoiceContent] ([ID]),
    CONSTRAINT [FK_Disposal_IPR] FOREIGN KEY ([Disposal2IPRIndex]) REFERENCES [dbo].[IPR] ([ID]),
    CONSTRAINT [FK_Disposal_JSOXCustomsSummary] FOREIGN KEY ([JSOXCustomsSummaryIndex]) REFERENCES [dbo].[JSOXCustomsSummary] ([ID]),
    CONSTRAINT [FK_Disposal_Material] FOREIGN KEY ([Disposal2MaterialIndex]) REFERENCES [dbo].[Material] ([ID]),
    CONSTRAINT [FK_Disposal_PCNCode] FOREIGN KEY ([Disposal2PCNID]) REFERENCES [dbo].[PCNCode] ([ID])
);

