CREATE TABLE [dbo].[IPR] (
    [AccountBalance]         FLOAT           NOT NULL,
    [AccountClosed]          BIT             NOT NULL,
    [Archival]               BIT             NULL,
    [Batch]                  NVARCHAR(255)   NULL,
    [Cartons]                FLOAT           NULL,
    [ClearenceIndex]         INT             NULL,
    [ClosingDate]            DATETIME        NULL,
    [ConsentPeriod]          FLOAT           NULL,
    [Created]                DATETIME        NULL,
    [CreatedBy]              NVARCHAR(255)   NULL,
    [Currency]               NVARCHAR(255)   NULL,
    [CustomsDebtDate]        DATETIME        NULL,
    [DocumentNo]             NVARCHAR(255)   NULL,
    [Duty]                   FLOAT           NULL,
    [DutyName]               NVARCHAR(255)   NULL,
    [Grade]                  NVARCHAR(255)   NULL,
    [GrossMass]              FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [InvoiceNo]              NVARCHAR(255)   NULL,
    [IPR2ConsentTitle]       INT             NULL,
    [IPR2JSOXIndex]          INT             NULL,
    [IPR2PCNPCN]             INT             NULL,
    [IPRClosi]               NVARCHAR(255)   NULL,
    [IPRDutyPerUnit]         FLOAT           NULL,
    [IPRLibraryIndex]        INT             NULL,
    [IPRUnitPrice]           FLOAT           NULL,
    [IPRVATPerUnit]          FLOAT           NULL,
    [Modified]               DATETIME        NULL,
    [ModifiedBy]             NVARCHAR(255)   NULL,
    [NetMass]                FLOAT           NULL,
    [OGLValidTo]             DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [ProductivityRateMax]    FLOAT           NULL,
    [ProductivityRateMin]    FLOAT           NULL,
    [SKU]                    NVARCHAR(255)   NULL,
    [Title]                  NVARCHAR(255)   NOT NULL,
    [TobaccoName]            NVARCHAR(255)   NULL,
    [TobaccoNotAllocated]    FLOAT           NULL,
    [ValidFromDate]          DATETIME        NULL,
    [ValidToDate]            DATETIME        NULL,
    [Value]                  FLOAT           NULL,
    [VAT]                    FLOAT           NULL,
    [VATName]                NVARCHAR(255)   NULL,
    CONSTRAINT [PK_IPR_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IPR_Clearence] FOREIGN KEY ([ClearenceIndex]) REFERENCES [dbo].[Clearence] ([ID]),
    CONSTRAINT [FK_IPR_Consent] FOREIGN KEY ([IPR2ConsentTitle]) REFERENCES [dbo].[Consent] ([ID]),
    CONSTRAINT [FK_IPR_IPRLibrary] FOREIGN KEY ([IPRLibraryIndex]) REFERENCES [dbo].[IPRLibrary] ([ID]),
    CONSTRAINT [FK_IPR_JSOXLibrary] FOREIGN KEY ([IPR2JSOXIndex]) REFERENCES [dbo].[JSOXLibrary] ([ID]),
    CONSTRAINT [FK_IPR_PCNCode] FOREIGN KEY ([IPR2PCNPCN]) REFERENCES [dbo].[PCNCode] ([ID])
);

