CREATE TABLE [dbo].[Material] (
    [Archival]            BIT            NULL,
    [Author]              NVARCHAR (MAX) NULL,
    [Batch]               NVARCHAR (MAX) NULL,
    [Created]             DATETIME       NULL,
    [Dust]                FLOAT (53)     NULL,
    [Editor]              NVARCHAR (MAX) NULL,
    [FGQuantity]          FLOAT (53)     NULL,
    [ID]                  INT            NOT NULL,
    [Material2BatchIndex] INT            NULL,
    [Modified]            DATETIME       NULL,
    [Overuse]             FLOAT (53)     NULL,
    [ProductID]           NVARCHAR (MAX) NULL,
    [ProductType]         NVARCHAR (MAX) NULL,
    [SHMenthol]           FLOAT (53)     NULL,
    [SKU]                 NVARCHAR (MAX) NULL,
    [SKUDescription]      NVARCHAR (MAX) NULL,
    [StorLoc]             NVARCHAR (MAX) NULL,
    [Title]               NVARCHAR (MAX) NOT NULL,
    [Tobacco]             FLOAT (53)     NULL,
    [TobaccoQuantity]     FLOAT (53)     NULL,
    [Units]               NVARCHAR (MAX) NULL,
    [Version]             INT            NULL,
    [Waste]               FLOAT (53)     NULL,
    CONSTRAINT [PK_Material_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Material_Batch] FOREIGN KEY ([Material2BatchIndex]) REFERENCES [dbo].[Batch] ([ID])
);

