CREATE TABLE [dbo].[BalanceBatch] (
    [Archival]               BIT             NULL,
    [Balance]                FLOAT           NULL,
    [Balance2JSOXLibraryIndex] INT             NULL,
    [Batch]                  NVARCHAR(255)   NULL,
    [Created]                DATETIME        NULL,
    [CreatedBy]              NVARCHAR(255)   NULL,
    [DocumentNo]             NVARCHAR(255)   NULL,
    [DustCSNotStarted]       FLOAT           NULL,
    [DustCSStarted]          FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [IPRBook]                FLOAT           NULL,
    [Modified]               DATETIME        NULL,
    [ModifiedBy]             NVARCHAR(255)   NULL,
    [OveruseCSNotStarted]    FLOAT           NULL,
    [OveruseCSStarted]       FLOAT           NULL,
    [owshiddenversion]       INT             NULL,
    [PureTobaccoCSNotStarted] FLOAT           NULL,
    [PureTobaccoCSStarted]   FLOAT           NULL,
    [SHMentholCSNotStarted]  FLOAT           NULL,
    [SHMentholCSStarted]     FLOAT           NULL,
    [SHWasteOveruseCSNotStarted] FLOAT           NULL,
    [SKU]                    NVARCHAR(255)   NULL,
    [Title]                  NVARCHAR(255)   NULL,
    [TobaccoAvailable]       FLOAT           NULL,
    [TobaccoCSFinished]      FLOAT           NULL,
    [TobaccoEnteredIntoIPR]  FLOAT           NULL,
    [TobaccoInCigarettesProduction] FLOAT           NULL,
    [TobaccoInCigarettesWarehouse] FLOAT           NULL,
    [TobaccoInCutfillerWarehouse] FLOAT           NULL,
    [TobaccoInFGCSNotStarted] FLOAT           NULL,
    [TobaccoInFGCSStarted]   FLOAT           NULL,
    [TobaccoInWarehouse]     FLOAT           NULL,
    [TobaccoStarted]         FLOAT           NULL,
    [TobaccoToBeUsedInTheProduction] FLOAT           NULL,
    [TobaccoUsedInTheProduction] FLOAT           NULL,
    [WasteCSNotStarted]      FLOAT           NULL,
    [WasteCSStarted]         FLOAT           NULL,
    CONSTRAINT [PK_BalanceBatch_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_BalanceBatch_JSOXLibrary] FOREIGN KEY ([Balance2JSOXLibraryIndex]) REFERENCES [dbo].[JSOXLibrary] ([ID])
);

