CREATE TABLE [dbo].[Batch] (
    [Archival]               BIT             NULL,
    [Batch]                  NVARCHAR(255)   NULL,
    [BatchDustCooeficiency]  FLOAT           NULL,
    [BatchLibraryIndex]      INT             NULL,
    [BatchSHCooeficiency]    FLOAT           NULL,
    [BatchStatus]            NVARCHAR(255)   NULL,
    [BatchWasteCooeficiency] FLOAT           NULL,
    [CalculatedOveruse]      FLOAT           NULL,
    [CFTProductivityNormMax] FLOAT           NULL,
    [CFTProductivityNormMin] FLOAT           NULL,
    [CFTProductivityRateMax] FLOAT           NULL,
    [CFTProductivityRateMin] FLOAT           NULL,
    [CFTProductivityVersion] FLOAT           NULL,
    [Created]                DATETIME        NULL,
    [CreatedBy]              NVARCHAR(255)   NULL,
    [CTFUsageMax]            FLOAT           NULL,
    [CTFUsageMin]            FLOAT           NULL,
    [Dust]                   FLOAT           NULL,
    [DustCooeficiencyVersion] FLOAT           NULL,
    [FGQuantity]             FLOAT           NULL,
    [FGQuantityAvailable]    FLOAT           NULL,
    [FGQuantityBlocked]      FLOAT           NULL,
    [FGQuantityPrevious]     FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [MaterialQuantity]       FLOAT           NULL,
    [MaterialQuantityPrevious] FLOAT           NULL,
    [Modified]               DATETIME        NULL,
    [ModifiedBy]             NVARCHAR(255)   NULL,
    [Overuse]                FLOAT           NULL,
    [ProductType]            NVARCHAR(255)   NULL,
    [SHCooeficiencyVersion]  FLOAT           NULL,
    [SHMenthol]              FLOAT           NULL,
    [SKU]                    NVARCHAR(255)   NULL,
    [SKUIndex]               INT             NULL,
    [Title]                  NVARCHAR(255)   NOT NULL,
    [Tobacco]                FLOAT           NULL,
    [UsageMax]               FLOAT           NULL,
    [UsageMin]               FLOAT           NULL,
    [UsageVersion]           FLOAT           NULL,
    [Waste]                  FLOAT           NULL,
    [WasteCooeficiencyVersion] FLOAT           NULL,
    CONSTRAINT [PK_Batch_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Batch_BatchLibrary] FOREIGN KEY ([BatchLibraryIndex]) REFERENCES [dbo].[BatchLibrary] ([ID]),
    CONSTRAINT [FK_Batch_SKU] FOREIGN KEY ([SKUIndex]) REFERENCES [dbo].[SKU] ([ID])
);

