CREATE TABLE [dbo].[Disposal] (
    [Archival]                     BIT            NULL,
    [Author]                       NVARCHAR (MAX) NULL,
    [ClearingType]                 NVARCHAR (MAX) NULL,
    [Created]                      DATETIME       NULL,
    [CustomsProcedure]             NVARCHAR (MAX) NULL,
    [CustomsStatus]                NVARCHAR (MAX) NULL,
    [Disposal2BatchIndex]          INT            NULL,
    [Disposal2ClearenceIndex]      INT            NULL,
    [Disposal2InvoiceContentIndex] INT            NULL,
    [Disposal2IPRIndex]            INT            NULL,
    [Disposal2MaterialIndex]       INT            NULL,
    [Disposal2PCNID]               INT            NULL,
    [DisposalStatus]               NVARCHAR (MAX) NULL,
    [DutyAndVAT]                   FLOAT (53)     NULL,
    [DutyPerSettledAmount]         FLOAT (53)     NULL,
    [Editor]                       NVARCHAR (MAX) NULL,
    [ID]                           INT            NOT NULL,
    [InvoiceNo]                    NVARCHAR (MAX) NULL,
    [IPRDocumentNo]                NVARCHAR (MAX) NULL,
    [JSOXCustomsSummaryIndex]      INT            NULL,
    [JSOXReportID]                 FLOAT (53)     NULL,
    [Modified]                     DATETIME       NULL,
    [RemainingQuantity]            FLOAT (53)     NULL,
    [SadConsignmentNo]             NVARCHAR (MAX) NULL,
    [SADDate]                      DATETIME       NULL,
    [SADDocumentNo]                NVARCHAR (MAX) NULL,
    [SettledQuantity]              FLOAT (53)     NULL,
    [SPNo]                         FLOAT (53)     NULL,
    [Title]                        NVARCHAR (MAX) NOT NULL,
    [TobaccoValue]                 FLOAT (53)     NULL,
    [VATPerSettledAmount]          FLOAT (53)     NULL,
    [Version]                      INT            NULL,
    CONSTRAINT [PK_Disposal_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Disposal_Batch] FOREIGN KEY ([Disposal2BatchIndex]) REFERENCES [dbo].[Batch] ([ID]),
    CONSTRAINT [FK_Disposal_Clearence] FOREIGN KEY ([Disposal2ClearenceIndex]) REFERENCES [dbo].[Clearence] ([ID]),
    CONSTRAINT [FK_Disposal_InvoiceContent] FOREIGN KEY ([Disposal2InvoiceContentIndex]) REFERENCES [dbo].[InvoiceContent] ([ID]),
    CONSTRAINT [FK_Disposal_IPR] FOREIGN KEY ([Disposal2IPRIndex]) REFERENCES [dbo].[IPR] ([ID]),
    CONSTRAINT [FK_Disposal_JSOXCustomsSummary] FOREIGN KEY ([JSOXCustomsSummaryIndex]) REFERENCES [dbo].[JSOXCustomsSummary] ([ID]),
    CONSTRAINT [FK_Disposal_Material] FOREIGN KEY ([Disposal2MaterialIndex]) REFERENCES [dbo].[Material] ([ID]),
    CONSTRAINT [FK_Disposal_PCNCode] FOREIGN KEY ([Disposal2PCNID]) REFERENCES [dbo].[PCNCode] ([ID])
);

