CREATE TABLE [dbo].[IPR] (
    [AccountBalance]      FLOAT (53)     NOT NULL,
    [AccountClosed]       BIT            NOT NULL,
    [Archival]            BIT            NULL,
    [Author]              NVARCHAR (MAX) NULL,
    [Batch]               NVARCHAR (MAX) NULL,
    [Cartons]             FLOAT (53)     NULL,
    [ClearenceIndex]      INT            NULL,
    [ClosingDate]         DATETIME       NULL,
    [ConsentPeriod]       FLOAT (53)     NULL,
    [Created]             DATETIME       NULL,
    [Currency]            NVARCHAR (MAX) NULL,
    [CustomsDebtDate]     DATETIME       NULL,
    [DocumentNo]          NVARCHAR (MAX) NULL,
    [Duty]                FLOAT (53)     NULL,
    [DutyName]            NVARCHAR (MAX) NULL,
    [Editor]              NVARCHAR (MAX) NULL,
    [Grade]               NVARCHAR (MAX) NULL,
    [GrossMass]           FLOAT (53)     NULL,
    [ID]                  INT            NOT NULL,
    [InvoiceNo]           NVARCHAR (MAX) NULL,
    [IPR2ConsentTitle]    INT            NULL,
    [IPR2JSOXIndex]       INT            NULL,
    [IPR2PCNPCN]          INT            NULL,
    [IPRDutyPerUnit]      FLOAT (53)     NULL,
    [IPRLibraryIndex]     INT            NULL,
    [IPRUnitPrice]        FLOAT (53)     NULL,
    [IPRVATPerUnit]       FLOAT (53)     NULL,
    [Modified]            DATETIME       NULL,
    [NetMass]             FLOAT (53)     NULL,
    [OGLValidTo]          DATETIME       NULL,
    [ProductivityRateMax] FLOAT (53)     NULL,
    [ProductivityRateMin] FLOAT (53)     NULL,
    [SKU]                 NVARCHAR (MAX) NULL,
    [Title]               NVARCHAR (MAX) NOT NULL,
    [TobaccoName]         NVARCHAR (MAX) NULL,
    [TobaccoNotAllocated] FLOAT (53)     NULL,
    [ValidFromDate]       DATETIME       NULL,
    [ValidToDate]         DATETIME       NULL,
    [Value]               FLOAT (53)     NULL,
    [VAT]                 FLOAT (53)     NULL,
    [VATName]             NVARCHAR (MAX) NULL,
    [Version]             INT            NULL,
	[OnlySQL]			  BIT			 NOT NULL,
	[UIVersionString]	  NVARCHAR(max)	 NULL,
    CONSTRAINT [PK_IPR_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IPR_Clearence] FOREIGN KEY ([ClearenceIndex]) REFERENCES [dbo].[Clearence] ([ID]),
    CONSTRAINT [FK_IPR_Consent] FOREIGN KEY ([IPR2ConsentTitle]) REFERENCES [dbo].[Consent] ([ID]),
    CONSTRAINT [FK_IPR_IPRLibrary] FOREIGN KEY ([IPRLibraryIndex]) REFERENCES [dbo].[IPRLibrary] ([ID]),
    CONSTRAINT [FK_IPR_JSOXLibrary] FOREIGN KEY ([IPR2JSOXIndex]) REFERENCES [dbo].[JSOXLibrary] ([ID]),
    CONSTRAINT [FK_IPR_PCNCode] FOREIGN KEY ([IPR2PCNPCN]) REFERENCES [dbo].[PCNCode] ([ID])
);

