CREATE TABLE [dbo].[IPR] (
    [AccountBalance]      FLOAT (53)     NOT NULL,
    [Batch]               NVARCHAR (255) NOT NULL,
    [Cartons]             FLOAT (53)     NOT NULL,
    [ClearenceIndex]      INT            NOT NULL,
    [ClosingDate]         DATETIME       NOT NULL,
    [ConsentPeriod]       FLOAT (53)     NOT NULL,
    [Created]             DATETIME       NOT NULL,
    [CreatedBy]           NVARCHAR (255) NOT NULL,
    [Currency]            NVARCHAR (255) NOT NULL,
    [CustomsDebtDate]     DATETIME       NOT NULL,
    [DocumentNo]          NVARCHAR (255) NOT NULL,
    [Duty]                FLOAT (53)     NOT NULL,
    [DutyName]            NVARCHAR (255) NOT NULL,
    [Grade]               NVARCHAR (255) NOT NULL,
    [GrossMass]           FLOAT (53)     NOT NULL,
    [ID]                  INT            NOT NULL,
    [InvoiceNo]           NVARCHAR (255) NOT NULL,
    [IPR2ConsentTitle]    INT            NOT NULL,
    [IPR2JSOXIndex]       INT            NOT NULL,
    [IPR2PCNPCN]          INT            NOT NULL,
    [IPRDutyPerUnit]      FLOAT (53)     NOT NULL,
    [IPRLibraryIndex]     INT            NOT NULL,
    [IPRUnitPrice]        FLOAT (53)     NOT NULL,
    [IPRVATPerUnit]       FLOAT (53)     NOT NULL,
    [Modified]            DATETIME       NOT NULL,
    [ModifiedBy]          NVARCHAR (255) NOT NULL,
    [NetMass]             FLOAT (53)     NOT NULL,
    [OGLValidTo]          DATETIME       NOT NULL,
    [ProductivityRateMax] FLOAT (53)     NOT NULL,
    [ProductivityRateMin] FLOAT (53)     NOT NULL,
    [SKU]                 NVARCHAR (255) NOT NULL,
    [Title]               NVARCHAR (255) NOT NULL,
    [TobaccoName]         NVARCHAR (255) NOT NULL,
    [TobaccoNotAllocated] FLOAT (53)     NOT NULL,
    [ValidFromDate]       DATETIME       NOT NULL,
    [ValidToDate]         DATETIME       NOT NULL,
    [Value]               FLOAT (53)     NOT NULL,
    [VAT]                 FLOAT (53)     NOT NULL,
    [VATName]             NVARCHAR (255) NOT NULL,
    CONSTRAINT [PK_IPR_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IPR_Clearence] FOREIGN KEY ([ClearenceIndex]) REFERENCES [dbo].[Clearence] ([ID]),
    CONSTRAINT [FK_IPR_Consent] FOREIGN KEY ([IPR2ConsentTitle]) REFERENCES [dbo].[Consent] ([ID]),
    CONSTRAINT [FK_IPR_IPRLibrary] FOREIGN KEY ([IPRLibraryIndex]) REFERENCES [dbo].[IPRLibrary] ([ID]),
    CONSTRAINT [FK_IPR_JSOXLibrary] FOREIGN KEY ([IPR2JSOXIndex]) REFERENCES [dbo].[JSOXLibrary] ([ID]),
    CONSTRAINT [FK_IPR_PCNCode] FOREIGN KEY ([IPR2PCNPCN]) REFERENCES [dbo].[PCNCode] ([ID])
);

