CREATE TABLE [dbo].[JSOXLibrary] (
    [Author]                NVARCHAR (MAX) NULL,
    [BalanceDate]           DATETIME       NULL,
    [BalanceQuantity]       FLOAT (53)     NULL,
    [Created]               DATETIME       NULL,
    [DocumentCreatedBy]     NVARCHAR (MAX) NULL,
    [Editor]                NVARCHAR (MAX) NULL,
    [FileName]              NVARCHAR (MAX) NOT NULL,
    [ID]                    INT            NOT NULL,
    [IntroducingDateEnd]    DATETIME       NULL,
    [IntroducingDateStart]  DATETIME       NULL,
    [IntroducingQuantity]   FLOAT (53)     NULL,
    [JSOXLibraryReadOnly]   BIT            NULL,
    [Modified]              DATETIME       NULL,
    [DocumentModifiedBy]    NVARCHAR (MAX) NULL,
    [OutboundDateEnd]       DATETIME       NULL,
    [OutboundDateStart]     DATETIME       NULL,
    [OutboundQuantity]      FLOAT (53)     NULL,
    [PreviousMonthDate]     DATETIME       NULL,
    [PreviousMonthQuantity] FLOAT (53)     NULL,
    [ReassumeQuantity]      FLOAT (53)     NULL,
    [SituationDate]         DATETIME       NULL,
    [SituationQuantity]     FLOAT (53)     NULL,
    [Title]                 NVARCHAR (MAX) NULL,
    [Version]               INT            NULL,
	[OnlySQL]				BIT			   NOT NULL,
    CONSTRAINT [PK_JSOXLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC)
);

