CREATE TABLE [dbo].[Material] (
    [Archival]               BIT             NULL,
    [Batch]                  NVARCHAR(255)   NULL,
    [Created]                DATETIME        NULL,
    [CreatedBy]              NVARCHAR(255)   NULL,
    [Dust]                   FLOAT           NULL,
    [FGQuantity]             FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [Material2BatchIndex]    INT             NULL,
    [Modified]               DATETIME        NULL,
    [ModifiedBy]             NVARCHAR(255)   NULL,
    [Overuse]                FLOAT           NULL,
    [ProductID]              NVARCHAR(255)   NULL,
    [ProductType]            NVARCHAR(255)   NULL,
    [SHMenthol]              FLOAT           NULL,
    [SKU]                    NVARCHAR(255)   NULL,
    [SKUDescription]         NVARCHAR(255)   NULL,
    [StorLoc]                NVARCHAR(255)   NULL,
    [Title]                  NVARCHAR(255)   NOT NULL,
    [Tobacco]                FLOAT           NULL,
    [TobaccoQuantity]        FLOAT           NULL,
    [Units]                  NVARCHAR(255)   NULL,
    [Waste]                  FLOAT           NULL,
    CONSTRAINT [PK_Material_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Material_Batch] FOREIGN KEY ([Material2BatchIndex]) REFERENCES [dbo].[Batch] ([ID])
);

