CREATE TABLE [dbo].[SKU] (
    [Archival]               BIT             NULL,
    [BlendPurpose]           NVARCHAR(255)   NULL,
    [Brand]                  NVARCHAR(255)   NULL,
    [CigaretteLenght]        NVARCHAR(255)   NULL,
    [Created]                DATETIME        NULL,
    [CreatedBy]              NVARCHAR(255)   NULL,
    [Family]                 NVARCHAR(255)   NULL,
    [FilterLenght]           NVARCHAR(255)   NULL,
    [FormatIndex]            INT             NULL,
    [ID]                     INT             NOT NULL,
    [IPRMaterial]            BIT             NULL,
    [Menthol]                NVARCHAR(255)   NULL,
    [MentholMaterial]        BIT             NULL,
    [Modified]               DATETIME        NULL,
    [ModifiedBy]             NVARCHAR(255)   NULL,
    [PrimeMarket]            NVARCHAR(255)   NULL,
    [ProductType]            NVARCHAR(255)   NULL,
    [SKU]                    NVARCHAR(255)   NULL,
    [SKULibraryIndex]        INT             NULL,
    [Title]                  NVARCHAR(255)   NOT NULL,
    [Units]                  NVARCHAR(255)   NULL,
    CONSTRAINT [PK_SKU_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SKU_SKULibrary] FOREIGN KEY ([SKULibraryIndex]) REFERENCES [dbo].[SKULibrary] ([ID]),
    CONSTRAINT [FK_SKU_SPFormat] FOREIGN KEY ([FormatIndex]) REFERENCES [dbo].[SPFormat] ([ID])
);

