CREATE TABLE [dbo].[StockEntry] (
    [Archival]               BIT             NULL,
    [Batch]                  NVARCHAR(255)   NULL,
    [BatchIndex]             INT             NULL,
    [Blocked]                FLOAT           NULL,
    [Created]                DATETIME        NULL,
    [CreatedBy]              NVARCHAR(255)   NULL,
    [ID]                     INT             NOT NULL,
    [InQualityInsp]          FLOAT           NULL,
    [IPRType]                BIT             NULL,
    [Modified]               DATETIME        NULL,
    [ModifiedBy]             NVARCHAR(255)   NULL,
    [owshiddenversion]       INT             NULL,
    [ProductType]            NVARCHAR(255)   NULL,
    [Quantity]               FLOAT           NULL,
    [RestrictedUse]          FLOAT           NULL,
    [SKU]                    NVARCHAR(255)   NULL,
    [StockLibraryIndex]      INT             NULL,
    [StorLoc]                NVARCHAR(255)   NULL,
    [Title]                  NVARCHAR(255)   NOT NULL,
    [Units]                  NVARCHAR(255)   NULL,
    [Unrestricted]           FLOAT           NULL,
    CONSTRAINT [PK_StockEntry_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_StockEntry_Batch] FOREIGN KEY ([BatchIndex]) REFERENCES [dbo].[Batch] ([ID]),
    CONSTRAINT [FK_StockEntry_StockLibrary] FOREIGN KEY ([StockLibraryIndex]) REFERENCES [dbo].[StockLibrary] ([ID])
);

