if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'Route')
  drop table  Route;
CREATE TABLE [dbo].[Route] (
    [Author]                 NVARCHAR(max)   NULL,
    [CarrierTitle]           INT             NULL,
    [Created]                DATETIME        NULL,
    [CurrencyTitle]          INT             NULL,
    [DepartureCity]          NVARCHAR(max)   NULL,
    [DeparturePort]          NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FreightPayerTitle]      INT             NULL,
    [GoodsHandlingPO]        NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Incoterm]               NVARCHAR(max)   NULL,
    [MaterialMaster]         NVARCHAR(max)   NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [PartnerTitle]           INT             NULL,
    [RemarkMM]               NVARCHAR(max)   NULL,
    [Route2BusinessDescriptionTitle] INT             NULL,
    [Route2CityTitle]        INT             NULL,
    [Route2Commodity]        INT             NULL,
    [SAPDestinationPlantTitle] INT             NULL,
    [ShipmentTypeTitle]      INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [TransportCosts]         FLOAT           NULL,
    [TransportUnitTypeTitle] INT             NULL,
    [OnlySQL]				 BIT			 NOT NULL,	
	CONSTRAINT [PK_Route_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
    CONSTRAINT [FK_Route_Carrier] FOREIGN KEY ([CarrierTitle]) REFERENCES [dbo].[Carrier] ([ID]),
    CONSTRAINT [FK_Route_Currency] FOREIGN KEY ([CurrencyTitle]) REFERENCES [dbo].[Currency] ([ID]),
    CONSTRAINT [FK_Route_FreightPayer] FOREIGN KEY ([FreightPayerTitle]) REFERENCES [dbo].[FreightPayer] ([ID]),
    CONSTRAINT [FK_Route_Partner] FOREIGN KEY ([PartnerTitle]) REFERENCES [dbo].[Partner] ([ID]),
    CONSTRAINT [FK_Route_BusinessDescription] FOREIGN KEY ([Route2BusinessDescriptionTitle]) REFERENCES [dbo].[BusinessDescription] ([ID]),
    CONSTRAINT [FK_Route_City] FOREIGN KEY ([Route2CityTitle]) REFERENCES [dbo].[City] ([ID]),
    CONSTRAINT [FK_Route_Commodity] FOREIGN KEY ([Route2Commodity]) REFERENCES [dbo].[Commodity] ([ID]),
    CONSTRAINT [FK_Route_SAPDestinationPlant] FOREIGN KEY ([SAPDestinationPlantTitle]) REFERENCES [dbo].[SAPDestinationPlant] ([ID]),
    CONSTRAINT [FK_Route_ShipmentType] FOREIGN KEY ([ShipmentTypeTitle]) REFERENCES [dbo].[ShipmentType] ([ID]),
    CONSTRAINT [FK_Route_TransportUnitType] FOREIGN KEY ([TransportUnitTypeTitle]) REFERENCES [dbo].[TransportUnitType] ([ID]),
);
