//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.5448
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038 and modified manualy.
// 
namespace CAS.SmartFactory.Deployment
{
  using System.Xml.Serialization;
  using System.ComponentModel;

  /// <uwagi/>
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cas.eu/schemas/SharePoint/Deployment/ApplicationState.xsd")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://cas.eu/schemas/SharePoint/Deployment/ApplicationState.xsd", IsNullable = true)]
  public partial class InstallationStateData
  {

    private string siteCollectionURLField;

    private string ownerLoginField;

    private string ownerEmailField;

    private bool siteCollectionCreatedField;

    private bool siteCollectionSolutionsDeployedField;

    private bool siteCollectionFeturesActivatedField;

    private bool farmSolutionsDeployedField;

    private bool farmFeaturesActivatedField;

    private string xmlWebApplicationURLField;

    private string xmlSiteCollectionFetureIdField;

    private string xmlFarmFetureIdField;

    private string xmlSolutionIDField;

    /// <summary>
    /// Gets or sets the web application URL.
    /// </summary>
    /// <value>
    /// A String that contains the URL for the site collection, for example, Site_Name or sites/Site_Name. 
    /// It may either be server-relative or absolute for typical sites.
    /// </value>
    [Browsable(true)]
    [ReadOnly(true)]
    [Category("User")]
    public string SiteCollectionURL
    {
      get
      {
        return this.siteCollectionURLField;
      }
      set
      {
        this.siteCollectionURLField = value;
      }
    }
    /// <summary>
    /// Gets or sets the owner login.
    /// </summary>
    /// <value>
    /// A String that contains the user name of the owner of the site collection (for example, Domain\User). In Active 
    /// Directory Domain Services account creation mode, the ownerLogin parameter must contain a value even if 
    /// the value does not correspond to an actual user name.
    /// </value>
    [Browsable(true)]
    [ReadOnly(true)]
    [Category("User")]
    public string OwnerLogin
    {
      get
      {
        return this.ownerLoginField;
      }
      set
      {
        this.ownerLoginField = value;
      }
    }
    /// <summary>
    /// Gets or sets the owner email.
    /// </summary>
    /// <value>
    /// A String that contains the e-mail address of the owner of the site collection.
    /// </value>
    [Browsable(true)]
    [ReadOnly(true)]
    [Category("User")]
    public string OwnerEmail
    {
      get
      {
        return this.ownerEmailField;
      }
      set
      {
        this.ownerEmailField = value;
      }
    }
    /// <summary>
    /// Gets or sets a value indicating whether site collection has been created.
    /// </summary>
    /// <value>
    /// 	<c>true</c> if [site collection created]; otherwise, <c>false</c>.
    /// </value>
    [Browsable(true)]
    [ReadOnly(true)]
    [Category("Installation")]
    public bool SiteCollectionCreated
    {
      get
      {
        return this.siteCollectionCreatedField;
      }
      set
      {
        this.siteCollectionCreatedField = value;
      }
    }
    /// <summary>
    /// Gets or sets a value indicating whether site collection solutions have been deployed.
    /// </summary>
    /// <value>
    /// 	<c>true</c> if site collection solutions deployed; otherwise, <c>false</c>.
    /// </value>
    [Browsable(true)]
    [ReadOnly(true)]
    [Category("Installation")]
    public bool SiteCollectionSolutionsDeployed
    {
      get
      {
        return this.siteCollectionSolutionsDeployedField;
      }
      set
      {
        this.siteCollectionSolutionsDeployedField = value;
      }
    }
    /// <summary>
    /// Gets or sets a value indicating whether site collection fetures have been activated.
    /// </summary>
    /// <value>
    /// 	<c>true</c> if site collection fetures activated; otherwise, <c>false</c>.
    /// </value>
    [Browsable(true)]
    [ReadOnly(true)]
    [Category("Installation")]
    public bool SiteCollectionFeturesActivated
    {
      get
      {
        return this.siteCollectionFeturesActivatedField;
      }
      set
      {
        this.siteCollectionFeturesActivatedField = value;
      }
    }
    /// <summary>
    /// Gets or sets a value indicating whether farm solutions have been deployed.
    /// </summary>
    /// <value>
    /// 	<c>true</c> if farm solutions deployed; otherwise, <c>false</c>.
    /// </value>
    [Browsable(true)]
    [ReadOnly(true)]
    [Category("Installation")]
    public bool FarmSolutionsDeployed
    {
      get
      {
        return this.farmSolutionsDeployedField;
      }
      set
      {
        this.farmSolutionsDeployedField = value;
      }
    }
    /// <summary>
    /// Gets or sets a value indicating whether farm features have been activated.
    /// </summary>
    /// <value>
    /// 	<c>true</c> if farm features activated; otherwise, <c>false</c>.
    /// </value>
    [Browsable(true)]
    [ReadOnly(true)]
    [Category("Installation")]
    public bool FarmFeaturesActivated
    {
      get
      {
        return this.farmFeaturesActivatedField;
      }
      set
      {
        this.farmFeaturesActivatedField = value;
      }
    }

    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
    [Browsable(false)]
    public string XmlWebApplicationURL
    {
      get
      {
        return this.xmlWebApplicationURLField;
      }
      set
      {
        this.xmlWebApplicationURLField = value;
      }
    }

    /// <uwagi/>
    [Browsable(false)]
    public string XmlSiteCollectionFetureId
    {
      get
      {
        return this.xmlSiteCollectionFetureIdField;
      }
      set
      {
        this.xmlSiteCollectionFetureIdField = value;
      }
    }

    /// <uwagi/>
    [Browsable(false)]
    public string XmlFarmFetureId
    {
      get
      {
        return this.xmlFarmFetureIdField;
      }
      set
      {
        this.xmlFarmFetureIdField = value;
      }
    }

    /// <uwagi/>
    [Browsable(false)]
    public string XmlSolutionID
    {
      get
      {
        return this.xmlSolutionIDField;
      }
      set
      {
        this.xmlSolutionIDField = value;
      }
    }
  }
}
