//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.5448
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CAS.SmartFactory.Deployment {
    using System.Xml.Serialization;
    
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SharePoint/Deployment/2/ApplicationState.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cas.eu/schemas/SharePoint/Deployment/2/ApplicationState.xsd", IsNullable=true)]
    public partial class InstallationStateData {
        
        private string ownerLoginField;
        
        private string ownerEmailField;
        
        private string siteCollectionURLField;
        
        private bool siteCollectionCreatedField;
        
        private string xmlWebApplicationURLField;
        
        private Solution[] solutionsField;
        
        /// <uwagi/>
        public string OwnerLogin {
            get {
                return this.ownerLoginField;
            }
            set {
                this.ownerLoginField = value;
            }
        }
        
        /// <uwagi/>
        public string OwnerEmail {
            get {
                return this.ownerEmailField;
            }
            set {
                this.ownerEmailField = value;
            }
        }
        
        /// <uwagi/>
        public string SiteCollectionURL {
            get {
                return this.siteCollectionURLField;
            }
            set {
                this.siteCollectionURLField = value;
            }
        }
        
        /// <uwagi/>
        public bool SiteCollectionCreated {
            get {
                return this.siteCollectionCreatedField;
            }
            set {
                this.siteCollectionCreatedField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string XmlWebApplicationURL {
            get {
                return this.xmlWebApplicationURLField;
            }
            set {
                this.xmlWebApplicationURLField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Solution[] Solutions {
            get {
                return this.solutionsField;
            }
            set {
                this.solutionsField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SharePoint/Deployment/2/ApplicationState.xsd")]
    public partial class Solution {
        
        private int priorityField;
        
        private string fileNameField;
        
        private string fetureIdField;
        
        private bool activatedField;
        
        private bool deployedField;
        
        private FeatureDefinitionScope featureDefinitionScopeField;
        
        private string solutionIDField;

        /// <summary>
        /// Initializes a new instance of the <see cref="Solution"/> class.
        /// </summary>
        public Solution() {
            this.activatedField = false;
            this.deployedField = false;
        }
        
        /// <uwagi/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <uwagi/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <uwagi/>
        public string FetureId {
            get {
                return this.fetureIdField;
            }
            set {
                this.fetureIdField = value;
            }
        }
        
        /// <uwagi/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Activated {
            get {
                return this.activatedField;
            }
            set {
                this.activatedField = value;
            }
        }
        
        /// <uwagi/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Deployed {
            get {
                return this.deployedField;
            }
            set {
                this.deployedField = value;
            }
        }
        
        /// <uwagi/>
        public FeatureDefinitionScope FeatureDefinitionScope {
            get {
                return this.featureDefinitionScopeField;
            }
            set {
                this.featureDefinitionScopeField = value;
            }
        }
        
        /// <uwagi/>
        public string SolutionID {
            get {
                return this.solutionIDField;
            }
            set {
                this.solutionIDField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cas.eu/schemas/SharePoint/Deployment/2/ApplicationState.xsd")]
    public enum FeatureDefinitionScope {
        
        /// <uwagi/>
        None,
        
        /// <uwagi/>
        Farm,
        
        /// <uwagi/>
        Site,
    }
}
