//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.18052
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace CAS.SmartFactory.CW.Interoperability.DocumentsFactory.AccountsReport {
    using System.Xml.Serialization;
    
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/AccountsR" +
        "eportContent.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/AccountsR" +
        "eportContent.xsd", IsNullable=false)]
    public partial class AccountsReportContent {
        
        private string documentNameField;
        
        private System.DateTime documentDateField;
        
        private string consentNoField;
        
        private System.DateTime consentDateField;
        
        private System.DateTime reportDateField;
        
        private ArrayOfAccounts4CurrencyAccountsArray[] accountsColectionField;
        
        /// <uwagi/>
        public string DocumentName {
            get {
                return this.documentNameField;
            }
            set {
                this.documentNameField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DocumentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
            }
        }
        
        /// <uwagi/>
        public string ConsentNo {
            get {
                return this.consentNoField;
            }
            set {
                this.consentNoField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ConsentDate {
            get {
                return this.consentDateField;
            }
            set {
                this.consentDateField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ReportDate {
            get {
                return this.reportDateField;
            }
            set {
                this.reportDateField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AccountsArray", IsNullable=false)]
        public ArrayOfAccounts4CurrencyAccountsArray[] AccountsColection {
            get {
                return this.accountsColectionField;
            }
            set {
                this.accountsColectionField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/AccountsR" +
        "eportContent.xsd")]
    public partial class ArrayOfAccounts4CurrencyAccountsArray {
        
        private double totalNetMassField;
        
        private double totalValueField;
        
        private string totalCurrencyField;
        
        private ArrayOfAccountsDetails[] accountsDetailsField;
        
        /// <uwagi/>
        public double TotalNetMass {
            get {
                return this.totalNetMassField;
            }
            set {
                this.totalNetMassField = value;
            }
        }
        
        /// <uwagi/>
        public double TotalValue {
            get {
                return this.totalValueField;
            }
            set {
                this.totalValueField = value;
            }
        }
        
        /// <uwagi/>
        public string TotalCurrency {
            get {
                return this.totalCurrencyField;
            }
            set {
                this.totalCurrencyField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Details", IsNullable=false)]
        public ArrayOfAccountsDetails[] AccountsDetails {
            get {
                return this.accountsDetailsField;
            }
            set {
                this.accountsDetailsField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cas.eu/schemas/SmartFactory/CW/Interoperability/DocumentsFactory/AccountsR" +
        "eportContent.xsd")]
    public partial class ArrayOfAccountsDetails {
        
        private int noField;
        
        private string documentNoField;
        
        private System.DateTime customsDebtDateField;
        
        private string tobaccoNameField;
        
        private string gradeField;
        
        private string sKUField;
        
        private string batchField;
        
        private string cNTarrifCodeField;
        
        private double netMassField;
        
        private double valueField;
        
        private string currencyField;
        
        /// <uwagi/>
        public int No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <uwagi/>
        public string DocumentNo {
            get {
                return this.documentNoField;
            }
            set {
                this.documentNoField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime CustomsDebtDate {
            get {
                return this.customsDebtDateField;
            }
            set {
                this.customsDebtDateField = value;
            }
        }
        
        /// <uwagi/>
        public string TobaccoName {
            get {
                return this.tobaccoNameField;
            }
            set {
                this.tobaccoNameField = value;
            }
        }
        
        /// <uwagi/>
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
        
        /// <uwagi/>
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
        
        /// <uwagi/>
        public string Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
            }
        }
        
        /// <uwagi/>
        public string CNTarrifCode {
            get {
                return this.cNTarrifCodeField;
            }
            set {
                this.cNTarrifCodeField = value;
            }
        }
        
        /// <uwagi/>
        public double NetMass {
            get {
                return this.netMassField;
            }
            set {
                this.netMassField = value;
            }
        }
        
        /// <uwagi/>
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <uwagi/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
    }
}
