USE IPRARCHIV
CREATE TABLE [dbo].[ActivityLog] (
    [ActivityPriority]       NVARCHAR(max)   NULL,
    [ActivitySource]         NVARCHAR(max)   NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Body]                   NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [Expires]                DATETIME        NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_ActivityLog_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[JSOXLibrary] (
    [Author]                 NVARCHAR(max)   NULL,
    [BalanceDate]            DATETIME        NULL,
    [BalanceQuantity]        FLOAT           NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [IntroducingDateEnd]     DATETIME        NULL,
    [IntroducingDateStart]   DATETIME        NULL,
    [IntroducingQuantity]    FLOAT           NULL,
    [JSOXLibraryReadOnly]    BIT             NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [OutboundDateEnd]        DATETIME        NULL,
    [OutboundDateStart]      DATETIME        NULL,
    [OutboundQuantity]       FLOAT           NULL,
    [owshiddenversion]       INT             NULL,
    [PreviousMonthDate]      DATETIME        NULL,
    [PreviousMonthQuantity]  FLOAT           NULL,
    [ReassumeQuantity]       FLOAT           NULL,
    [SituationDate]          DATETIME        NULL,
    [SituationQuantity]      FLOAT           NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_JSOXLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[BalanceBatch] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Balance]                FLOAT           NULL,
    [Balance2JSOXLibraryIndex] INT             NULL,
    [Batch]                  NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [DocumentNo]             NVARCHAR(max)   NULL,
    [DustCSNotStarted]       FLOAT           NULL,
    [DustCSStarted]          FLOAT           NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [IPRBook]                FLOAT           NULL,
    [Modified]               DATETIME        NULL,
    [OveruseCSNotStarted]    FLOAT           NULL,
    [OveruseCSStarted]       FLOAT           NULL,
    [owshiddenversion]       INT             NULL,
    [PureTobaccoCSNotStarted] FLOAT           NULL,
    [PureTobaccoCSStarted]   FLOAT           NULL,
    [SHMentholCSNotStarted]  FLOAT           NULL,
    [SHMentholCSStarted]     FLOAT           NULL,
    [SHWasteOveruseCSNotStarted] FLOAT           NULL,
    [SKU]                    NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [TobaccoAvailable]       FLOAT           NULL,
    [TobaccoCSFinished]      FLOAT           NULL,
    [TobaccoEnteredIntoIPR]  FLOAT           NULL,
    [TobaccoInCigarettesProduction] FLOAT           NULL,
    [TobaccoInCigarettesWarehouse] FLOAT           NULL,
    [TobaccoInCutfillerWarehouse] FLOAT           NULL,
    [TobaccoInFGCSNotStarted] FLOAT           NULL,
    [TobaccoInFGCSStarted]   FLOAT           NULL,
    [TobaccoInWarehouse]     FLOAT           NULL,
    [TobaccoStarted]         FLOAT           NULL,
    [TobaccoToBeUsedInTheProduction] FLOAT           NULL,
    [TobaccoUsedInTheProduction] FLOAT           NULL,
    [WasteCSNotStarted]      FLOAT           NULL,
    [WasteCSStarted]         FLOAT           NULL,
      CONSTRAINT [PK_BalanceBatch_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_BalanceBatch_JSOXLibrary] FOREIGN KEY ([Balance2JSOXLibraryIndex]) REFERENCES [dbo].[JSOXLibrary] ([ID]),
);
CREATE TABLE [dbo].[SADDocumentLibrary] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [SADDocumentLibraryComments] NVARCHAR(max)   NULL,
    [SADDocumentLibraryOK]   BIT             NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_SADDocumentLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[SADDocument] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Currency]               NVARCHAR(max)   NULL,
    [CustomsDebtDate]        DATETIME        NULL,
    [DocumentNumber]         NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ExchangeRate]           FLOAT           NULL,
    [GrossMass]              FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [NetMass]                FLOAT           NULL,
    [owshiddenversion]       INT             NULL,
    [ReferenceNumber]        NVARCHAR(max)   NULL,
    [SADDocumenLibrarytIndex] INT             NULL,
    [SystemID]               NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_SADDocument_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_SADDocument_SADDocumentLibrary] FOREIGN KEY ([SADDocumenLibrarytIndex]) REFERENCES [dbo].[SADDocumentLibrary] ([ID]),
);
CREATE TABLE [dbo].[SADGood] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [GoodsDescription]       NVARCHAR(max)   NULL,
    [GrossMass]              FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [ItemNo]                 FLOAT           NULL,
    [Modified]               DATETIME        NULL,
    [NetMass]                FLOAT           NULL,
    [owshiddenversion]       INT             NULL,
    [PCNTariffCode]          NVARCHAR(max)   NULL,
    [SADDocumentIndex]       INT             NULL,
    [SPProcedure]            NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [TotalAmountInvoiced]    FLOAT           NULL,
      CONSTRAINT [PK_SADGood_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_SADGood_SADDocument] FOREIGN KEY ([SADDocumentIndex]) REFERENCES [dbo].[SADDocument] ([ID]),
);
CREATE TABLE [dbo].[SADConsignment] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_SADConsignment_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[Clearence] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Clearence2SadGoodID]    INT             NULL,
    [ClearenceProcedure]     NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [DocumentNo]             NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [ProcedureCode]          NVARCHAR(max)   NULL,
    [ReferenceNumber]        NVARCHAR(max)   NULL,
    [SADConsignmentLibraryIndex] INT             NULL,
    [SPStatus]               BIT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_Clearence_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_Clearence_SADGood] FOREIGN KEY ([Clearence2SadGoodID]) REFERENCES [dbo].[SADGood] ([ID]),
      CONSTRAINT [FK_Clearence_SADConsignment] FOREIGN KEY ([SADConsignmentLibraryIndex]) REFERENCES [dbo].[SADConsignment] ([ID]),
);
CREATE TABLE [dbo].[Consent] (
    [Author]                 NVARCHAR(max)   NULL,
    [ConsentDate]            DATETIME        NULL,
    [ConsentPeriod]          FLOAT           NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [IsIPR]                  BIT             NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [ProductivityRateMax]    FLOAT           NULL,
    [ProductivityRateMin]    FLOAT           NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [ValidFromDate]          DATETIME        NULL,
    [ValidToDate]            DATETIME        NULL,
      CONSTRAINT [PK_Consent_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[PCNCode] (
    [Author]                 NVARCHAR(max)   NULL,
    [CompensationGood]       NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Disposal]               BIT             NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [ProductCodeNumber]      NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_PCNCode_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[IPRLibrary] (
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [DocumentNo]             NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_IPRLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[IPR] (
    [AccountBalance]         FLOAT           NOT NULL,
    [AccountClosed]          BIT             NOT NULL,
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Batch]                  NVARCHAR(max)   NULL,
    [Cartons]                FLOAT           NULL,
    [ClearenceIndex]         INT             NULL,
    [ClosingDate]            DATETIME        NULL,
    [ConsentPeriod]          FLOAT           NULL,
    [Created]                DATETIME        NULL,
    [Currency]               NVARCHAR(max)   NULL,
    [CustomsDebtDate]        DATETIME        NULL,
    [DocumentNo]             NVARCHAR(max)   NULL,
    [Duty]                   FLOAT           NULL,
    [DutyName]               NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [Grade]                  NVARCHAR(max)   NULL,
    [GrossMass]              FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [InvoiceNo]              NVARCHAR(max)   NULL,
    [IPR2ConsentTitle]       INT             NULL,
    [IPR2JSOXIndex]          INT             NULL,
    [IPR2PCNPCN]             INT             NULL,
    [IPRDutyPerUnit]         FLOAT           NULL,
    [IPRLibraryIndex]        INT             NULL,
    [IPRUnitPrice]           FLOAT           NULL,
    [IPRVATPerUnit]          FLOAT           NULL,
    [Modified]               DATETIME        NULL,
    [NetMass]                FLOAT           NULL,
    [OGLValidTo]             DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [ProductivityRateMax]    FLOAT           NULL,
    [ProductivityRateMin]    FLOAT           NULL,
    [SKU]                    NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [TobaccoName]            NVARCHAR(max)   NULL,
    [TobaccoNotAllocated]    FLOAT           NULL,
    [ValidFromDate]          DATETIME        NULL,
    [ValidToDate]            DATETIME        NULL,
    [Value]                  FLOAT           NULL,
    [VAT]                    FLOAT           NULL,
    [VATName]                NVARCHAR(max)   NULL,
      CONSTRAINT [PK_IPR_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_IPR_Clearence] FOREIGN KEY ([ClearenceIndex]) REFERENCES [dbo].[Clearence] ([ID]),
      CONSTRAINT [FK_IPR_Consent] FOREIGN KEY ([IPR2ConsentTitle]) REFERENCES [dbo].[Consent] ([ID]),
      CONSTRAINT [FK_IPR_JSOXLibrary] FOREIGN KEY ([IPR2JSOXIndex]) REFERENCES [dbo].[JSOXLibrary] ([ID]),
      CONSTRAINT [FK_IPR_PCNCode] FOREIGN KEY ([IPR2PCNPCN]) REFERENCES [dbo].[PCNCode] ([ID]),
      CONSTRAINT [FK_IPR_IPRLibrary] FOREIGN KEY ([IPRLibraryIndex]) REFERENCES [dbo].[IPRLibrary] ([ID]),
);
CREATE TABLE [dbo].[BalanceIPR] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Balance]                FLOAT           NULL,
    [BalanceBatchIndex]      INT             NULL,
    [BalanceIPR2JSOXIndex]   INT             NULL,
    [Batch]                  NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [CustomsProcedure]       NVARCHAR(max)   NULL,
    [DocumentNo]             NVARCHAR(max)   NULL,
    [DustCSNotStarted]       FLOAT           NULL,
    [DustCSStarted]          FLOAT           NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [InvoiceNo]              NVARCHAR(max)   NULL,
    [IPRBook]                FLOAT           NULL,
    [IPRIndex]               INT             NULL,
    [Modified]               DATETIME        NULL,
    [OGLIntroduction]        NVARCHAR(max)   NULL,
    [OveruseCSNotStarted]    FLOAT           NULL,
    [OveruseCSStarted]       FLOAT           NULL,
    [owshiddenversion]       INT             NULL,
    [PureTobaccoCSNotStarted] FLOAT           NULL,
    [PureTobaccoCSStarted]   FLOAT           NULL,
    [SHMentholCSNotStarted]  FLOAT           NULL,
    [SHMentholCSStarted]     FLOAT           NULL,
    [SHWasteOveruseCSNotStarted] FLOAT           NULL,
    [SKU]                    NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [TobaccoAvailable]       FLOAT           NULL,
    [TobaccoCSFinished]      FLOAT           NULL,
    [TobaccoEnteredIntoIPR]  FLOAT           NULL,
    [TobaccoInFGCSNotStarted] FLOAT           NULL,
    [TobaccoInFGCSStarted]   FLOAT           NULL,
    [TobaccoStarted]         FLOAT           NULL,
    [TobaccoToBeUsedInTheProduction] FLOAT           NULL,
    [TobaccoUsedInTheProduction] FLOAT           NULL,
    [WasteCSNotStarted]      FLOAT           NULL,
    [WasteCSStarted]         FLOAT           NULL,
      CONSTRAINT [PK_BalanceIPR_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_BalanceIPR_BalanceBatch] FOREIGN KEY ([BalanceBatchIndex]) REFERENCES [dbo].[BalanceBatch] ([ID]),
      CONSTRAINT [FK_BalanceIPR_JSOXLibrary] FOREIGN KEY ([BalanceIPR2JSOXIndex]) REFERENCES [dbo].[JSOXLibrary] ([ID]),
      CONSTRAINT [FK_BalanceIPR_IPR] FOREIGN KEY ([IPRIndex]) REFERENCES [dbo].[IPR] ([ID]),
);
CREATE TABLE [dbo].[BatchLibrary] (
    [Author]                 NVARCHAR(max)   NULL,
    [BatchLibraryComments]   NVARCHAR(max)   NULL,
    [BatchLibraryOK]         BIT             NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_BatchLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[SPFormat] (
    [Author]                 NVARCHAR(max)   NULL,
    [CigaretteLenght]        NVARCHAR(max)   NOT NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FilterLenght]           NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_SPFormat_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[SKU] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [BlendPurpose]           NVARCHAR(max)   NULL,
    [Brand]                  NVARCHAR(max)   NULL,
    [CigaretteLenght]        NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [Family]                 NVARCHAR(max)   NULL,
    [FilterLenght]           NVARCHAR(max)   NULL,
    [FormatIndex]            INT             NULL,
    [ID]                     INT             NOT NULL,
    [IPRMaterial]            BIT             NULL,
    [Menthol]                NVARCHAR(max)   NULL,
    [MentholMaterial]        BIT             NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [PrimeMarket]            NVARCHAR(max)   NULL,
    [ProductType]            NVARCHAR(max)   NULL,
    [SKU]                    NVARCHAR(max)   NULL,
    [SKULibraryIndex]        INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [Units]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_SKU_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_SKU_SPFormat] FOREIGN KEY ([FormatIndex]) REFERENCES [dbo].[SPFormat] ([ID]),
);
CREATE TABLE [dbo].[Batch] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Batch]                  NVARCHAR(max)   NULL,
    [BatchDustCooeficiency]  FLOAT           NULL,
    [BatchLibraryIndex]      INT             NULL,
    [BatchSHCooeficiency]    FLOAT           NULL,
    [BatchStatus]            NVARCHAR(max)   NULL,
    [BatchWasteCooeficiency] FLOAT           NULL,
    [CalculatedOveruse]      FLOAT           NULL,
    [CFTProductivityNormMax] FLOAT           NULL,
    [CFTProductivityNormMin] FLOAT           NULL,
    [CFTProductivityRateMax] FLOAT           NULL,
    [CFTProductivityRateMin] FLOAT           NULL,
    [CFTProductivityVersion] FLOAT           NULL,
    [Created]                DATETIME        NULL,
    [CTFUsageMax]            FLOAT           NULL,
    [CTFUsageMin]            FLOAT           NULL,
    [Dust]                   FLOAT           NULL,
    [DustCooeficiencyVersion] FLOAT           NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FGQuantity]             FLOAT           NULL,
    [FGQuantityAvailable]    FLOAT           NULL,
    [FGQuantityBlocked]      FLOAT           NULL,
    [FGQuantityPrevious]     FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [MaterialQuantity]       FLOAT           NULL,
    [MaterialQuantityPrevious] FLOAT           NULL,
    [Modified]               DATETIME        NULL,
    [Overuse]                FLOAT           NULL,
    [owshiddenversion]       INT             NULL,
    [ProductType]            NVARCHAR(max)   NULL,
    [SHCooeficiencyVersion]  FLOAT           NULL,
    [SHMenthol]              FLOAT           NULL,
    [SKU]                    NVARCHAR(max)   NULL,
    [SKUIndex]               INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [Tobacco]                FLOAT           NULL,
    [UsageMax]               FLOAT           NULL,
    [UsageMin]               FLOAT           NULL,
    [UsageVersion]           FLOAT           NULL,
    [Waste]                  FLOAT           NULL,
    [WasteCooeficiencyVersion] FLOAT           NULL,
      CONSTRAINT [PK_Batch_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_Batch_BatchLibrary] FOREIGN KEY ([BatchLibraryIndex]) REFERENCES [dbo].[BatchLibrary] ([ID]),
      CONSTRAINT [FK_Batch_SKU] FOREIGN KEY ([SKUIndex]) REFERENCES [dbo].[SKU] ([ID]),
);
CREATE TABLE [dbo].[BinCardLibrary] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_BinCardLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[CustomsUnion] (
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [EUPrimeMarket]          NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_CustomsUnion_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[CustomsWarehouseLibrary] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_CustomsWarehouseLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[Vendor] (
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [WorkAddress]            NVARCHAR(max)   NULL,
    [WorkCity]               NVARCHAR(max)   NULL,
    [WorkCountry]            NVARCHAR(max)   NULL,
    [WorkZip]                NVARCHAR(max)   NULL,
      CONSTRAINT [PK_Vendor_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[CustomsWarehouse] (
    [AccountBalance]         FLOAT           NOT NULL,
    [AccountClosed]          BIT             NOT NULL,
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Batch]                  NVARCHAR(max)   NULL,
    [ClosingDate]            DATETIME        NULL,
    [Created]                DATETIME        NULL,
    [Currency]               NVARCHAR(max)   NULL,
    [CustomsDebtDate]        DATETIME        NULL,
    [CW_CertificateOfAuthenticity] NVARCHAR(max)   NULL,
    [CW_CertificateOfOrgin]  NVARCHAR(max)   NULL,
    [CW_COADate]             DATETIME        NULL,
    [CW_CODate]              DATETIME        NULL,
    [CW_MassPerPackage]      FLOAT           NULL,
    [CW_PackageKg]           FLOAT           NULL,
    [CW_PackageUnits]        FLOAT           NULL,
    [CW_PzNo]                NVARCHAR(max)   NULL,
    [CW_Quantity]            FLOAT           NULL,
    [CW_UnitPrice]           FLOAT           NULL,
    [CWC_EntryDate]          DATETIME        NULL,
    [CWL_CW2BinCardTitle]    INT             NULL,
    [CWL_CW2ClearenceID]     INT             NULL,
    [CWL_CW2ConsentTitle]    INT             NULL,
    [CWL_CW2CWLibraryID]     INT             NULL,
    [CWL_CW2PCNID]           INT             NULL,
    [CWL_CW2VendorTitle]     INT             NULL,
    [DocumentNo]             NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [Grade]                  NVARCHAR(max)   NULL,
    [GrossMass]              FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [InvoiceNo]              NVARCHAR(max)   NULL,
    [Modified]               DATETIME        NULL,
    [NetMass]                FLOAT           NULL,
    [owshiddenversion]       INT             NULL,
    [SKU]                    NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [TobaccoName]            NVARCHAR(max)   NULL,
    [TobaccoNotAllocated]    FLOAT           NULL,
    [Units]                  NVARCHAR(max)   NULL,
    [ValidToDate]            DATETIME        NULL,
    [Value]                  FLOAT           NULL,
      CONSTRAINT [PK_CustomsWarehouse_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_CustomsWarehouse_BinCardLibrary] FOREIGN KEY ([CWL_CW2BinCardTitle]) REFERENCES [dbo].[BinCardLibrary] ([ID]),
      CONSTRAINT [FK_CustomsWarehouse_Clearence] FOREIGN KEY ([CWL_CW2ClearenceID]) REFERENCES [dbo].[Clearence] ([ID]),
      CONSTRAINT [FK_CustomsWarehouse_Consent] FOREIGN KEY ([CWL_CW2ConsentTitle]) REFERENCES [dbo].[Consent] ([ID]),
      CONSTRAINT [FK_CustomsWarehouse_CustomsWarehouseLibrary] FOREIGN KEY ([CWL_CW2CWLibraryID]) REFERENCES [dbo].[CustomsWarehouseLibrary] ([ID]),
      CONSTRAINT [FK_CustomsWarehouse_PCNCode] FOREIGN KEY ([CWL_CW2PCNID]) REFERENCES [dbo].[PCNCode] ([ID]),
      CONSTRAINT [FK_CustomsWarehouse_Vendor] FOREIGN KEY ([CWL_CW2VendorTitle]) REFERENCES [dbo].[Vendor] ([ID]),
);
CREATE TABLE [dbo].[DisposalRequestLibrary] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [ClearenceProcedure]     NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_DisposalRequestLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[CustomsWarehouseDisposal] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [ClearingType]           NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [CustomsProcedure]       NVARCHAR(max)   NULL,
    [CustomsStatus]          NVARCHAR(max)   NULL,
    [CW_AddedKg]             FLOAT           NULL,
    [CW_DeclaredNetMass]     FLOAT           NULL,
    [CW_PackageToClear]      FLOAT           NULL,
    [CW_RemainingPackage]    FLOAT           NULL,
    [CW_RemainingTobaccoValue] FLOAT           NULL,
    [CW_SettledGrossMass]    FLOAT           NULL,
    [CW_SettledNetMass]      FLOAT           NULL,
    [CW_Wz1]                 NVARCHAR(max)   NULL,
    [CW_Wz2]                 NVARCHAR(max)   NULL,
    [CW_Wz3]                 NVARCHAR(max)   NULL,
    [CW_WZNoSupplemented]    BIT             NULL,
    [CWL_CWDisposal2ClearanceID] INT             NULL,
    [CWL_CWDisposal2CustomsWarehouseID] INT             NULL,
    [CWL_CWDisposal2DisposalRequestLibraryID] INT             NULL,
    [CWL_CWDisposal2PCNTID]  INT             NULL,
    [DutyAndVAT]             FLOAT           NULL,
    [DutyPerSettledAmount]   FLOAT           NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [RemainingQuantity]      FLOAT           NULL,
    [SADDate]                DATETIME        NULL,
    [SADDocumentNo]          NVARCHAR(max)   NULL,
    [SKUDescription]         NVARCHAR(max)   NULL,
    [SPNo]                   FLOAT           NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [TobaccoValue]           FLOAT           NULL,
    [VATPerSettledAmount]    FLOAT           NULL,
      CONSTRAINT [PK_CustomsWarehouseDisposal_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_CustomsWarehouseDisposal_Clearence] FOREIGN KEY ([CWL_CWDisposal2ClearanceID]) REFERENCES [dbo].[Clearence] ([ID]),
      CONSTRAINT [FK_CustomsWarehouseDisposal_CustomsWarehouse] FOREIGN KEY ([CWL_CWDisposal2CustomsWarehouseID]) REFERENCES [dbo].[CustomsWarehouse] ([ID]),
      CONSTRAINT [FK_CustomsWarehouseDisposal_DisposalRequestLibrary] FOREIGN KEY ([CWL_CWDisposal2DisposalRequestLibraryID]) REFERENCES [dbo].[DisposalRequestLibrary] ([ID]),
      CONSTRAINT [FK_CustomsWarehouseDisposal_PCNCode] FOREIGN KEY ([CWL_CWDisposal2PCNTID]) REFERENCES [dbo].[PCNCode] ([ID]),
);
CREATE TABLE [dbo].[CustomsWarehouseReportLibrary] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_CustomsWarehouseReportLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[CutfillerCoefficient] (
    [Author]                 NVARCHAR(max)   NULL,
    [CFTProductivityNormMax] FLOAT           NULL,
    [CFTProductivityNormMin] FLOAT           NULL,
    [CFTProductivityRateMax] FLOAT           NULL,
    [CFTProductivityRateMin] FLOAT           NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_CutfillerCoefficient_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[CWLibrary] (
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_CWLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[CW] (
    [AccountBalance]         FLOAT           NOT NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Batch]                  NVARCHAR(max)   NULL,
    [ClosingDate]            DATETIME        NULL,
    [ConsentPeriod]          FLOAT           NULL,
    [Created]                DATETIME        NULL,
    [Currency]               NVARCHAR(max)   NULL,
    [CustomsDebtDate]        DATETIME        NULL,
    [CW2ConsentTitle]        INT             NULL,
    [CW2CWLibraryID]         INT             NULL,
    [CW2PCNID]               INT             NULL,
    [CWCertificate]          NVARCHAR(max)   NULL,
    [CWMassPerPackage]       FLOAT           NULL,
    [CWPackageKg]            FLOAT           NULL,
    [CWPackageUnits]         FLOAT           NULL,
    [CWPzNo]                 NVARCHAR(max)   NULL,
    [CWQuantity]             FLOAT           NULL,
    [CWUnitPrice]            FLOAT           NULL,
    [DocumentNo]             NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [EntryDate]              DATETIME        NULL,
    [Grade]                  NVARCHAR(max)   NULL,
    [GrossMass]              FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [InvoiceNo]              NVARCHAR(max)   NULL,
    [Modified]               DATETIME        NULL,
    [NetMass]                FLOAT           NULL,
    [owshiddenversion]       INT             NULL,
    [SKU]                    NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [TobaccoName]            NVARCHAR(max)   NULL,
    [Units]                  NVARCHAR(max)   NULL,
    [ValidFromDate]          DATETIME        NULL,
    [ValidToDate]            DATETIME        NULL,
    [Value]                  FLOAT           NULL,
      CONSTRAINT [PK_CW_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_CW_Consent] FOREIGN KEY ([CW2ConsentTitle]) REFERENCES [dbo].[Consent] ([ID]),
      CONSTRAINT [FK_CW_CWLibrary] FOREIGN KEY ([CW2CWLibraryID]) REFERENCES [dbo].[CWLibrary] ([ID]),
      CONSTRAINT [FK_CW_PCNCode] FOREIGN KEY ([CW2PCNID]) REFERENCES [dbo].[PCNCode] ([ID]),
);
CREATE TABLE [dbo].[CWDisposal] (
    [Author]                 NVARCHAR(max)   NULL,
    [Batch]                  NVARCHAR(max)   NULL,
    [ClearingType]           NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Currency]               NVARCHAR(max)   NULL,
    [CustomsProcedure]       NVARCHAR(max)   NULL,
    [CustomsStatus]          NVARCHAR(max)   NULL,
    [CWAddedKg]              FLOAT           NULL,
    [CWDeclaredNetMass]      FLOAT           NULL,
    [CWDisposal2PCNTID]      INT             NULL,
    [CWRemainingPackage]     FLOAT           NULL,
    [CWRemainingTobaccoValue] FLOAT           NULL,
    [CWSettledGrossMass]     FLOAT           NULL,
    [CWSettledNetMass]       FLOAT           NULL,
    [CWWz1]                  NVARCHAR(max)   NULL,
    [CWWz2]                  NVARCHAR(max)   NULL,
    [CWWz3]                  NVARCHAR(max)   NULL,
    [DutyAndVAT]             FLOAT           NULL,
    [DutyPerSettledAmount]   FLOAT           NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [EntryDate]              DATETIME        NULL,
    [Grade]                  NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [RemainingQuantity]      FLOAT           NULL,
    [SADDate]                DATETIME        NULL,
    [SADDocumentNo]          NVARCHAR(max)   NULL,
    [SKU]                    NVARCHAR(max)   NULL,
    [SPNo]                   FLOAT           NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [TobaccoName]            NVARCHAR(max)   NULL,
    [TobaccoValue]           FLOAT           NULL,
    [VATPerSettledAmount]    FLOAT           NULL,
      CONSTRAINT [PK_CWDisposal_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_CWDisposal_PCNCode] FOREIGN KEY ([CWDisposal2PCNTID]) REFERENCES [dbo].[PCNCode] ([ID]),
);
CREATE TABLE [dbo].[InvoiceLibrary] (
    [Author]                 NVARCHAR(max)   NULL,
    [BillDoc]                NVARCHAR(max)   NULL,
    [ClearenceIndex]         INT             NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [InvoiceCreationDate]    DATETIME        NULL,
    [InvoiceLibraryReadOnly] BIT             NULL,
    [InvoiceLibraryStatus]   BIT             NULL,
    [IsExport]               BIT             NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_InvoiceLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_InvoiceLibrary_Clearence] FOREIGN KEY ([ClearenceIndex]) REFERENCES [dbo].[Clearence] ([ID]),
);
CREATE TABLE [dbo].[InvoiceContent] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [InvoiceContent2BatchIndex] INT             NULL,
    [InvoiceContentStatus]   NVARCHAR(max)   NULL,
    [InvoiceIndex]           INT             NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [ProductType]            NVARCHAR(max)   NULL,
    [Quantity]               FLOAT           NULL,
    [SKUDescription]         NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [Units]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_InvoiceContent_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_InvoiceContent_Batch] FOREIGN KEY ([InvoiceContent2BatchIndex]) REFERENCES [dbo].[Batch] ([ID]),
      CONSTRAINT [FK_InvoiceContent_InvoiceLibrary] FOREIGN KEY ([InvoiceIndex]) REFERENCES [dbo].[InvoiceLibrary] ([ID]),
);
CREATE TABLE [dbo].[Material] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Batch]                  NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Dust]                   FLOAT           NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FGQuantity]             FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [Material2BatchIndex]    INT             NULL,
    [Modified]               DATETIME        NULL,
    [Overuse]                FLOAT           NULL,
    [owshiddenversion]       INT             NULL,
    [ProductID]              NVARCHAR(max)   NULL,
    [ProductType]            NVARCHAR(max)   NULL,
    [SHMenthol]              FLOAT           NULL,
    [SKU]                    NVARCHAR(max)   NULL,
    [SKUDescription]         NVARCHAR(max)   NULL,
    [StorLoc]                NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [Tobacco]                FLOAT           NULL,
    [TobaccoQuantity]        FLOAT           NULL,
    [Units]                  NVARCHAR(max)   NULL,
    [Waste]                  FLOAT           NULL,
      CONSTRAINT [PK_Material_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_Material_Batch] FOREIGN KEY ([Material2BatchIndex]) REFERENCES [dbo].[Batch] ([ID]),
);
CREATE TABLE [dbo].[JSOXCustomsSummary] (
    [Author]                 NVARCHAR(max)   NULL,
    [CompensationGood]       NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [CustomsProcedure]       NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ExportOrFreeCirculationSAD] NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [IntroducingSADDate]     DATETIME        NULL,
    [IntroducingSADNo]       NVARCHAR(max)   NULL,
    [InvoiceNo]              NVARCHAR(max)   NULL,
    [JSOXCustomsSummary2JSOXIndex] INT             NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [RemainingQuantity]      FLOAT           NULL,
    [SADDate]                DATETIME        NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [TotalAmount]            FLOAT           NULL,
      CONSTRAINT [PK_JSOXCustomsSummary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_JSOXCustomsSummary_JSOXLibrary] FOREIGN KEY ([JSOXCustomsSummary2JSOXIndex]) REFERENCES [dbo].[JSOXLibrary] ([ID]),
);
CREATE TABLE [dbo].[Disposal] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [ClearingType]           NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [CustomsProcedure]       NVARCHAR(max)   NULL,
    [CustomsStatus]          NVARCHAR(max)   NULL,
    [Disposal2BatchIndex]    INT             NULL,
    [Disposal2ClearenceIndex] INT             NULL,
    [Disposal2InvoiceContentIndex] INT             NULL,
    [Disposal2IPRIndex]      INT             NULL,
    [Disposal2MaterialIndex] INT             NULL,
    [Disposal2PCNID]         INT             NULL,
    [DisposalStatus]         NVARCHAR(max)   NULL,
    [DutyAndVAT]             FLOAT           NULL,
    [DutyPerSettledAmount]   FLOAT           NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [InvoiceNo]              NVARCHAR(max)   NULL,
    [IPRDocumentNo]          NVARCHAR(max)   NULL,
    [JSOXCustomsSummaryIndex] INT             NULL,
    [JSOXReportID]           FLOAT           NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [RemainingQuantity]      FLOAT           NULL,
    [SadConsignmentNo]       NVARCHAR(max)   NULL,
    [SADDate]                DATETIME        NULL,
    [SADDocumentNo]          NVARCHAR(max)   NULL,
    [SettledQuantity]        FLOAT           NULL,
    [SPNo]                   FLOAT           NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [TobaccoValue]           FLOAT           NULL,
    [VATPerSettledAmount]    FLOAT           NULL,
      CONSTRAINT [PK_Disposal_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_Disposal_Batch] FOREIGN KEY ([Disposal2BatchIndex]) REFERENCES [dbo].[Batch] ([ID]),
      CONSTRAINT [FK_Disposal_Clearence] FOREIGN KEY ([Disposal2ClearenceIndex]) REFERENCES [dbo].[Clearence] ([ID]),
      CONSTRAINT [FK_Disposal_InvoiceContent] FOREIGN KEY ([Disposal2InvoiceContentIndex]) REFERENCES [dbo].[InvoiceContent] ([ID]),
      CONSTRAINT [FK_Disposal_IPR] FOREIGN KEY ([Disposal2IPRIndex]) REFERENCES [dbo].[IPR] ([ID]),
      CONSTRAINT [FK_Disposal_Material] FOREIGN KEY ([Disposal2MaterialIndex]) REFERENCES [dbo].[Material] ([ID]),
      CONSTRAINT [FK_Disposal_PCNCode] FOREIGN KEY ([Disposal2PCNID]) REFERENCES [dbo].[PCNCode] ([ID]),
      CONSTRAINT [FK_Disposal_JSOXCustomsSummary] FOREIGN KEY ([JSOXCustomsSummaryIndex]) REFERENCES [dbo].[JSOXCustomsSummary] ([ID]),
);
CREATE TABLE [dbo].[DisposalDeclaration] (
    [AddedToClearDeclared]   FLOAT           NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [CWDescription]          NVARCHAR(max)   NULL,
    [DecalredToCleared]      FLOAT           NULL,
    [DisposalsDeclaration2BatchIndex] INT             NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [EntryDate]              DATETIME        NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [PackageAvailable]       FLOAT           NULL,
    [PackageToCleared]       FLOAT           NULL,
    [QuantityAvailable]      FLOAT           NULL,
    [QuantityToCleared]      FLOAT           NULL,
    [SPNo]                   FLOAT           NULL,
    [SPProcedure]            NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_DisposalDeclaration_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_DisposalDeclaration_Batch] FOREIGN KEY ([DisposalsDeclaration2BatchIndex]) REFERENCES [dbo].[Batch] ([ID]),
);
CREATE TABLE [dbo].[Dust] (
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [DustRatio]              FLOAT           NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [ProductType]            NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_Dust_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[SADDuties] (
    [Amount]                 FLOAT           NULL,
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [DutyType]               NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [SADDuties2SADGoodID]    INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_SADDuties_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_SADDuties_SADGood] FOREIGN KEY ([SADDuties2SADGoodID]) REFERENCES [dbo].[SADGood] ([ID]),
);
CREATE TABLE [dbo].[SADPackage] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [ItemNo]                 FLOAT           NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [Package]                NVARCHAR(max)   NULL,
    [SADPackage2SADGoodID]   INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_SADPackage_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_SADPackage_SADGood] FOREIGN KEY ([SADPackage2SADGoodID]) REFERENCES [dbo].[SADGood] ([ID]),
);
CREATE TABLE [dbo].[SADQuantity] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [ItemNo]                 FLOAT           NULL,
    [Modified]               DATETIME        NULL,
    [NetMass]                FLOAT           NULL,
    [owshiddenversion]       INT             NULL,
    [SADQuantity2SADGoodID]  INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [Units]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_SADQuantity_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_SADQuantity_SADGood] FOREIGN KEY ([SADQuantity2SADGoodID]) REFERENCES [dbo].[SADGood] ([ID]),
);
CREATE TABLE [dbo].[SADRequiredDocuments] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Code]                   NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [Number]                 NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [SADRequiredDoc2SADGoodID] INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_SADRequiredDocuments_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_SADRequiredDocuments_SADGood] FOREIGN KEY ([SADRequiredDoc2SADGoodID]) REFERENCES [dbo].[SADGood] ([ID]),
);
CREATE TABLE [dbo].[Settings] (
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [KeyValue]               NVARCHAR(max)   NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_Settings_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[SHMenthol] (
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [ProductType]            NVARCHAR(max)   NOT NULL,
    [SHMentholRatio]         FLOAT           NOT NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_SHMenthol_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[StatementLibrary] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [CWL_Statement2DisposalRequestID] INT             NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_StatementLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_StatementLibrary_DisposalRequestLibrary] FOREIGN KEY ([CWL_Statement2DisposalRequestID]) REFERENCES [dbo].[DisposalRequestLibrary] ([ID]),
);
CREATE TABLE [dbo].[StockLibrary] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Created_x0020_By]       NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FileLeafRef]            NVARCHAR(max)   NOT NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [Modified_x0020_By]      NVARCHAR(max)   NULL,
    [owshiddenversion]       INT             NULL,
    [Stock2JSOXLibraryIndex] INT             NULL,
    [Title]                  NVARCHAR(max)   NULL,
      CONSTRAINT [PK_StockLibrary_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_StockLibrary_JSOXLibrary] FOREIGN KEY ([Stock2JSOXLibraryIndex]) REFERENCES [dbo].[JSOXLibrary] ([ID]),
);
CREATE TABLE [dbo].[StockEntry] (
    [Archival]               BIT             NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [Batch]                  NVARCHAR(max)   NULL,
    [BatchIndex]             INT             NULL,
    [Blocked]                FLOAT           NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [InQualityInsp]          FLOAT           NULL,
    [IPRType]                BIT             NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [ProductType]            NVARCHAR(max)   NULL,
    [Quantity]               FLOAT           NULL,
    [RestrictedUse]          FLOAT           NULL,
    [SKU]                    NVARCHAR(max)   NULL,
    [StockLibraryIndex]      INT             NULL,
    [StorLoc]                NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [Units]                  NVARCHAR(max)   NULL,
    [Unrestricted]           FLOAT           NULL,
      CONSTRAINT [PK_StockEntry_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_StockEntry_Batch] FOREIGN KEY ([BatchIndex]) REFERENCES [dbo].[Batch] ([ID]),
      CONSTRAINT [FK_StockEntry_StockLibrary] FOREIGN KEY ([StockLibraryIndex]) REFERENCES [dbo].[StockLibrary] ([ID]),
);
CREATE TABLE [dbo].[Usage] (
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [CTFUsageMax]            FLOAT           NULL,
    [CTFUsageMin]            FLOAT           NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [FormatIndex]            INT             NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [UsageMax]               FLOAT           NULL,
    [UsageMin]               FLOAT           NULL,
      CONSTRAINT [PK_Usage_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
      CONSTRAINT [FK_Usage_SPFormat] FOREIGN KEY ([FormatIndex]) REFERENCES [dbo].[SPFormat] ([ID]),
);
CREATE TABLE [dbo].[Warehouse] (
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [ProductType]            NVARCHAR(max)   NOT NULL,
    [SPProcedure]            NVARCHAR(max)   NOT NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [WarehouseName]          NVARCHAR(max)   NOT NULL,
      CONSTRAINT [PK_Warehouse_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[Waste] (
    [Author]                 NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [ProductType]            NVARCHAR(max)   NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [WasteRatio]             FLOAT           NULL,
      CONSTRAINT [PK_Waste_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[History] (
    [ID]                     INT IDENTITY(1,1) NOT NULL,
    [ListName]               NVARCHAR(255)   NOT NULL,
    [ItemID]                 INT             NOT NULL,
    [FieldName]              NVARCHAR(255)   NOT NULL,
    [FieldValue]             NVARCHAR(255)   NOT NULL,
    [Modified]               DATETIME        NOT NULL,
    [ModifiedBy]             NVARCHAR(255)   NOT NULL,
      CONSTRAINT [PK_History_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[ArchivingLogs] (
    [ID]                     INT IDENTITY(1,1) NOT NULL,
    [ListName]               NVARCHAR(255)   NOT NULL,
    [ItemID]                 INT             NOT NULL,
    [Date]                   DATETIME        NOT NULL,
    [UserName]               NVARCHAR(255)   NOT NULL,
      CONSTRAINT [PK_ArchivingLogs_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
CREATE TABLE [dbo].[ArchivingOperationLogs] (
    [ID]                     INT IDENTITY(1,1) NOT NULL,
    [Operation]              NVARCHAR(255)   NOT NULL,
    [Date]                   DATETIME        NOT NULL,
    [UserName]               NVARCHAR(255)   NOT NULL,
      CONSTRAINT [PK_ArchivingOperationLogs_ID] PRIMARY KEY CLUSTERED ([ID] ASC) 
);
